### ISSUE TITLE
Create routes for different ideas pages

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#10]
https://beta.dailyidea.com/ideas/all
https://beta.dailyidea.com/ideas/me
https://beta.dailyidea.com/ideas/username
https://beta.dailyidea.com/ideas/liked
https://beta.dailyidea.com/ideas/popular

These will be useful for the pages that we are trying to link to internally from within the app.

**Comment by aldarund** [comment]
popular - we dotn have such functionality

**Comment by aldarund** [comment]
https://beta.dailyidea.com/ideas/all
https://beta.dailyidea.com/ideas/me
https://beta.dailyidea.com/ideas/liked
this works

**Comment by aldarund** [comment]
https://beta.dailyidea.com/ideas/username - we dont have username. what do u mean here>?

**Comment by aldarund** [comment]
@ezl ping

**Comment by ezl** [comment]
Ah oops, I didn't see this. Thanks for pinging me, @aldarund.

What I mean is that there should be a public route for anyone to view all the ideas by a specific user, and it should be relatively human friendly.

**Comment by aldarund** [comment]
generat random unqiue slug for each user ?

**Comment by ezl** [comment]
hmmm. yes.

for now, just generate a random slug for each user. Make sure this user is explicitly stored and we access the user's ideas by doing a lookup for the user by slug.

Then, in the future, this will make it so that we can explicitly set slugs or let users select slugs (if we build that UX later).

**Comment by ezl** [comment]
don't know how to test yet -- saving for when chatting with dmitry.

"liked" doesn't work though (separate ticket)

**Comment by ezl** [comment]
unable to sign off now until at least the /liked page works
