### ISSUE TITLE
Create a template for social media posts

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#1007]
Hey @Watson-B, one of the ideas to grow DailyIdea is to regularly post content on social media.
To do that, I would kindly ask you think of a Facebook post and Instagram post templates.
The scope:
- The templates should be simple, editable files
- Fixed background and GFX, easily to edit the content
- The content would be the title of the idea and the poster name
- Include "dailyidea.com" somewhere

Let me know if I can help somehow. :)

**Comment by Watson-B** [comment]
Sounds good, I will work on it.
