### ISSUE TITLE
Verify domain for Pixel

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#1036]
We'll need to verify our domain for FB pixel. There are 3 methods to do so:

![image](https://user-images.githubusercontent.com/16639403/126470031-e179aa74-91d2-4298-9cc2-768e9560c24d.png)

Please let me know which one of the 3 works best for you @vedmant and I'll share the implementation details.

**Comment by vedmant** [comment]
@ikosovec Could you copy paste the tag itself?

**Comment by ikosovec** [comment]
Yes, if we decide to implement it via the meta tag. I was asking which one of these 3 you would like ^^.
Here's the meta tag:
For dailyidea.com:
`<meta name="facebook-domain-verification" content="8081vtbrutquxkbvp533v5wq1wumar" />`

For profiles.dailyidea.com
`<meta name="facebook-domain-verification" content="am2mk1ows1xtcs1a5aqm8d3a3ohb7w" />`

And the instructions (in case you need them):
![image](https://user-images.githubusercontent.com/16639403/126475334-56e3d0f2-e782-40e5-b764-f4f35264609b.png)

**Comment by vedmant** [comment]
@ikosovec I never worked with profiles.dailyidea.com domain. @ezl what it's built on, is it also on AWS?

**Comment by vedmant** [comment]
@ikosovec I published update, it should be deployed to production soon.

**Comment by ikosovec** [comment]
@vedmant this is working now for dailyidea.com

We'll set it up on profiles through Webflow.
