### ISSUE TITLE
on server error show styled page

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#117]
right now, showing a nuxt default server error page

**Comment by aldarund** [comment]
@ezl please provide design for this :)

**Comment by ezl** [comment]
For now, can you just copy the 404 page, but change the copy to:

500

Oops!
Our server can't figure out what to do. Sorry about that. 

<link to home>Go back to the home page</link>

**Comment by aldarund** [comment]
we can show styled page. But it cant be same as client error. E.g. there wont be any vue js working etc. It must be pure static html file not having any js logic or anything

**Comment by ezl** [comment]
@aldarund I don't think I understand.

The default nuxt error page I'm seeing on server errors appears to be a nuxt page -- so doesn't that mean that vue js is working?

**Comment by aldarund** [comment]
@ezl there two kind of error pages. One is when error happens on client. When this happens -> vue works and error page can be displyaed. On the other hand there can be errors that happen during SSR and than this page is displayed https://img.lichter.io/blog/customize-server-error-page/default-nuxt-server-error-page-full.jpg
When error happens during ssr its means we cant properly render page so we cant make vue work. So we can only serve full static page without vue functionality
https://blog.lichter.io/posts/nuxtjs-change-server-error-page/#completely-replace-the-error-page

> HTML means: no Vue/Nuxt logic, only pure HTML and CSS. Of course, you can add javascript (eg. error reporting tools) and so on if you want.

**Comment by ezl** [comment]
Got it. I understand now.

Can we just create the 404 page in static html/css, but change the text to say 500?

https://beta.dailyidea.com/43qkerjasd4h3qeuaksdthisshouldbreak
