### ISSUE TITLE
Limit max allowed limit for queries at api limit

### ISSUE THREAD

**Issue by aldarund** [ezl/dailyidea.com#121]
so user wont be able to request for example 2500 ideas to scan them all at once and cause dynamodb  usage

**Comment by ezl** [comment]
good idea. 👍

**Comment by ezl** [comment]
(future)

**Comment by ezl** [comment]
@aldarund just confirming this was actually completed? (i see you moved it to "merged" but i didn't see the PR)

**Comment by aldarund** [comment]
it was, there was PR or i committed directly don't remember
