### ISSUE TITLE
set font

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#13]
try to mimic the fonts in the actual designs. if not possible, use open sans as default font

**Comment by patelravi** [comment]
@ezl to mimic the fonts as specified in designs, we will need to take fonts from adobe or else we can use open sans as you mentioned.

**Comment by patelravi** [comment]
Its deployment issue as discussed with @aldarund 
Will be resolved after deployment font issues resolved.
Hence labeling this task as back-end task instead of front-end.
