### ISSUE TITLE
fix idea detail page.

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#136]
markup is all screwed up
vertical lines aren't aligned correctly
can't comment

make comments section be 30% width and idea be 70%

**Comment by aldarund** [comment]
is there new design for this page? or just fix current one? if there new better to do it instead of fixing current

**Comment by ezl** [comment]
no new design yet -- reviewing this shortly. put this in waiting for review for me for specific feedback to make it easier for you.

**Comment by ezl** [comment]
https://monosnap.com/file/o7bMDj2L2ksOJub08dGwM0BVu0PhHr

Specific changes @aldarund ^

**Comment by ezl** [comment]
oops, not supposed to close.

**Comment by ezl** [comment]
On completion, please also confirm that a user can leave comments on the idea detail page.
