### ISSUE TITLE
Edit idea page: style changes

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#142]
1. Use same styles as Create idea page (no boxes, just lines and content)
2. completely hide comments section while editing.

**Comment by ezl** [comment]
i see this was moved, @aldarund but i checked on beta.dailyidea.com and it doesn't seem to be complete. still see lines and comments on edit idea.

review together? or perhaps this commit didn't get pushed?

**Comment by ezl** [comment]
reassigning.

**Comment by GildedHonour** [comment]
For the "body" - done.
For the "title" and "tags" - not yet.

**Comment by GildedHonour** [comment]
The comments box is on the right. Editing is done is place, on the left side. Do we really need to hide the comments box? @ezl 

<img width="1250" alt="Captura de pantalla 2020-03-16 a la(s) 15 17 52" src="https://user-images.githubusercontent.com/2032888/76744018-7cbacd00-676b-11ea-8368-f3fccdd488dd.png">

**Comment by ezl** [comment]
@GildedHonour yes.

Can you think of any good reason to have the comments box visible?

**Comment by GildedHonour** [comment]
@ezl since the page isn't getting reloaded when "edit/save" is pressed, and editing is done in place, if the comment box will disappear and then reappear, that'll be not bad, but perhaps strange.
