### ISSUE TITLE
Make unauthenticated "save idea" work

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#147]
Use a flow that mirrors the "unauthenticated comment attempt" that was just executed by @aldarund recently (https://github.com/ezl/dailyidea.com/issues/56)

if an unauthenticated user tries to save an idea, we don't ask them to log in/signup. Instead, we just:

# First

1. ask them for their email. ("What's your email address so you can find your saved ideas later? (Just so I know how to find this for you in the future.)")

# If email matches an existing user:

1. if user is existing user, say: "Welcome back, {{name}}. We sent you a confirmation email. Please check your inbox and click the verification link in the message so we can make sure we're saving this idea to the right account."
2. send them a verification link. This should use a different email template used specifically for this purpose. "Hey Eric, looks like you tried to save this idea: if that's right, please click here to finish saving that to your account: button". {magic link goes back to idea page and confirms action}
3. when they click the verification link, it takes them back to the idea page, and saves the idea.
4. Show a success message that says: "Yay! Welcome back {name}. We saved that idea for you! You can check all your saved ideas on your Saved Ideas page _link_"

# If email does NOT match an existing user

1. If we don't have that user, NOW ask for the person's name: "Almost there - What can we call you?" (placeholder text: First name).
2. "Awesome, {firstname}! We just sent you an email, which we'll just use to make sure we can find your saved ideas later. Please check your inbox and click the link the confirmation link to finish saving this idea."
3. Send them a verification link: "Congrats {firstname}! You're about to save your first idea! Looks like you tried to save this idea: if that's right, please click here to finish saving that to your account: button". {magic link goes back to idea page and confirms action}
4. On clicking verification link, create user, take user back to the page (already logged in) and save the idea to that account. MODAL: "Hooray! you saved your first idea! Welcome to Daily idea. You can <a>browse more ideas</a> or <a>start saving your own ideas</a> whenever you're ready."

**Comment by inflameous48** [comment]
Alternatively, we can let them write down the idea to familiarize themselves with the platform, and when they click save/post we ask them for the email with the flow above. They already committed quite a bit of time when writing that idea, so they would be more likely to sign up.
