### ISSUE TITLE
[Profile] Make it possible to edit profile name and information

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#153]
# Current status

Currently, on the profile page:
https://beta.dailyidea.com/profile

It's not possible to edit profile name or information.

# Changes

1. Make it possible to edit both.
2. Use an "edit" icon (like the one currently next to the name). Clicking on that, should toggle an "edit in place" mode and make a "save" icon visible. Clicking the save icon should save this.
3. properly account for possibility of failure when saving -- so when the payload is en route, make the save icon disabled and indicate that it is waiting, then on success, revert back to the display state. on failure, go back to the edit state and show an error message appropriately.

**Comment by GildedHonour** [comment]
The 'profile name editing' is clear. What's 'the information'?

**Comment by GildedHonour** [comment]
Found -- that's bio

**Comment by ezl** [comment]
👍 -- lmk if you still need help clarifying this issue.

**Comment by GildedHonour** [comment]
That's clear.

**Comment by GildedHonour** [comment]
related #154

**Comment by GildedHonour** [comment]
@ezl 
since we've removed "...or tags" part of the tooltip in #154, should the "tags" field remain?

<img width="672" alt="Captura de pantalla 2020-03-13 a la(s) 00 20 38" src="https://user-images.githubusercontent.com/2032888/76557089-bac99f80-6492-11ea-81a8-b6b02e9ddf59.png">

**Comment by ezl** [comment]
@GildedHonour 

What does that information do? is it used in any way other than to display on the profile page?

If it is not used other than to display on the profile page, remove that field entirely.

If it is used, update this ticket to tell me how it is used in the app and tag me please.

**Comment by GildedHonour** [comment]
The tags are used, they're displayed on a user's profile, I've left the field in the edit mode.
 
<img width="1042" alt="Captura de pantalla 2020-03-16 a la(s) 11 31 03" src="https://user-images.githubusercontent.com/2032888/76727545-3bff8b80-674c-11ea-90f4-d1e09ece85de.png">

**Comment by GildedHonour** [comment]
1. The bug has been fixed.
2. That "edit" icon, next to the name, allows you to edit all: name, bio and tags. Any changes?

**Comment by GildedHonour** [comment]
3. It does that.

<img width="983" alt="Captura de pantalla 2020-03-16 a la(s) 11 42 51" src="https://user-images.githubusercontent.com/2032888/76727983-60a83300-674d-11ea-9521-5f5aa59d11ec.png">

<img width="981" alt="Captura de pantalla 2020-03-16 a la(s) 11 43 38" src="https://user-images.githubusercontent.com/2032888/76727997-6736aa80-674d-11ea-8dca-52da539c7ffe.png">

**Comment by GildedHonour** [comment]
#192

**Comment by ezl** [comment]
ok sounds good. if it does those things, then i consider this done. move this to the Done board in the projects/1 board and I'll QA when all complete.
