### ISSUE TITLE
[Email parser] strip out signatures from email idea parser

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#155]

**Comment by GildedHonour** [comment]
In `back/mail-processing/mail_templates/*.html` I've found this in an html file:

`View all your previous ideas here: {{ BASE_SITE_URL }}/ideas/me`

Is this a signature?


Or does the task refer to striping out signatures dynamically and the file `back/mail-processing/process_incoming_mail.py`?

**Comment by ezl** [comment]
to be honest, I'm not sure if this task is even possible.

The task is ideally to remove user signatures when they send an email.

For example, mine is 

```
--Eric
```

It's not clear to me if this is somehow indicated differently or separable from the actual email content.

In an ideal case, we are also stripping out replies if the received email body contains a thread.

Can you do some cursory research to see if it even seems possible?

@aldarund any insight into feasibility on this?

**Comment by GildedHonour** [comment]
I think there's no fullproof way to detect signature because a signature it's a part of an email placed in the end. But where does it begin precisely? There're ways to guess where - https://stackoverflow.com/questions/1372694/strip-signatures-and-replies-from-emails

Detecting a quoted text in a email is easier - there're standard delimeters - ones used by gmail, iphone, outlook, yahoo, etc... but perphaps that's not fullproof either.

**Comment by ezl** [comment]
Got it. Thanks for doing the research, @GildedHonour.

Let's go with it. I understand it's not foolproof, but it might be better than other things.

Can you:

(A) try it on a few emails -- basically you can try it on ones that I've sent, or use some of your own and see how you think this behaves. If you think it seems ok, lets proceed and

(B) make sure you have the "strip signatures and replies" logic encapsulated in such a way that if we do not like it, it's easy to remove, like by just having a separate method, rather than embedding this logic directly somewhere. (you may already do this, but since we don't know each other yet, just being explicit -- if you have an alternate approach you prefer, feel free to discuss in advance).

@aldarund any objections?

**Comment by GildedHonour** [comment]
(A) I'd use this library - https://github.com/mailgun/talon
More info - https://www.mailgun.com/blog/open-sourcing-our-email-signature-parsing-library/ 

Otherwise out solution would be limited and might be triggered in false positive cases. 

Downside - additional dependency. 


(B) Ok

**Comment by ezl** [comment]
beautiful. love that someone else already did it. also mailgun is reputable
so if it's maintained by them it's as good or better than what we'd make.

I say go ahead and implement and submit a PR.

--Eric

**Comment by aldarund** [comment]
note - talon really big e.g. it have big deps. Right now we fit into  lambda limit. but its near limit, so if we add some more deps we will be out of lambda limit

**Comment by ezl** [comment]
mmm ok -- reopening ticket for discussion.

if it's too big for lambda does that mean we have to self host? or are there bigger lambda type services.

For now, I prefer to optimize for simplicity -- BUT i do think that cleaning emails seems like a really nice user experience.

@aldarund your recommendations on how to balance these competing priorities? Is there a way we can get cleaned emails without changing infrastructure?

**Comment by aldarund** [comment]
its fine for now, just a s remind for future.
Solution could be for example to separate talon as separate lambda

**Comment by ezl** [comment]
got it. ok, then reclosing ticket. :)
