### ISSUE TITLE
Sort out '{env/conf}/.env' files

### ISSUE THREAD

**Issue by GildedHonour** [ezl/dailyidea.com#158]
* At 'front' there's a file `.env`. But at the moment the `front` won't run without an exception unless I create `conf/dev.env` with the identical content. However, if I remove the `.env`, it'll throw an exception also. That is, there're 2 identical files required to run `front`.

* In appsync there's `back/env/dev.env`, whereas in `back/mail-processing` and `back/user` the corresponding env files are located at `conf/dev.env`

* We have only `dev.env` and not `prod.env` also. Why not?

Should we sort that out?

**Comment by aldarund** [comment]
1 - not quite correct. .env needed to run project in dev mode. and it will be run without conf/dev.env without any errors.  conf/dev.env needed for deployment build via serverless.

**Comment by aldarund** [comment]
2 - agreem it could be unified

**Comment by aldarund** [comment]
3 - we have prod.env too. its for production and its not in repo

**Comment by GildedHonour** [comment]
@aldarund 

(1)
Only when they're both present, the app works.


If I remove front/conf directory, I'll get this in the console at runtime - a page won't load:

<img width="1439" alt="Captura de pantalla 2020-02-19 a la(s) 16 49 45" src="https://user-images.githubusercontent.com/2032888/74830118-58093c00-530a-11ea-8409-7bb2cb7bc9d0.png">


If I remove front/.env file:

<img width="1424" alt="Captura de pantalla 2020-02-19 a la(s) 16 51 17" src="https://user-images.githubusercontent.com/2032888/74830164-72431a00-530a-11ea-9751-6d0f7632c44a.png">

**Comment by GildedHonour** [comment]
(2) what do you mean? I meant, to store config data, shouldn't we agree to use  either a) the "conf" directory in root of each app b) or the ".env" file in the root of each project? In order to avoid confusion.

**Comment by aldarund** [comment]
i reworked front envs. Now they are only in /conf

./conf/local.env

**Comment by aldarund** [comment]
and moved for appsync to conf
