### ISSUE TITLE
Idea text region cannot scroll. Long ideas are truncated.

### ISSUE THREAD

**Issue by ccg** [ezl/dailyidea.com#16]
Using the latest Firefox on the latest version of macOS.

![Screen Shot 2019-08-02 at 11 41 42 AM](https://user-images.githubusercontent.com/59996/62382113-e9ee5a80-b51a-11e9-962a-455cf8d6e61e.png)

**Comment by patelravi** [comment]
This left-right design has major drawback. Hence I've put them on vertical order as shown in attached screenshot

![image](https://user-images.githubusercontent.com/7405840/63337347-793e9f00-c35e-11e9-967a-dd5d63f7450f.png)
