### ISSUE TITLE
Split Test on unauthenticated user share signup dialog

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#176]
Follow up to https://github.com/ezl/dailyidea.com/issues/169

2 competing theses:

1. traditional "sign up" request -- this is effectively the normal process of communicating to a user that they are "creating an account" -- and we can communicate how easy it is or the value prop in order to get more people through the funnel.

2. @ezl's idea that we can blur the lines a bit between "account holder" and "email list subscriber". The theory in question is that internet people nowadays have an aversion to creating yet another account on yet another site. Just the cognitive overhead of even considering it causes funnel drop off. However, if all we want is an email address so we can gradually demonstrate value, then instead of even asking them to create an account at all, we just tell them we can "keep sending them the most popular ideas from other people" if they give us their email address.  IMO this feels more like a email subscription with little impact and no "account" in their mind, but from our perspective, it's effectively an account.

These paths are really the same thing, just with different copy -- would be interesting to see if there's a measurable difference.

**Comment by inflameous48** [comment]
Just to reiterate on this one with an example:

1. Sign up to receive benefit A, benefit B, benefit C, all you have to do is enter your email.
2. Would you like to receive daily/updates of the best ideas, save and follow other user's ideas, save your own idea? Simply enter your email.
