### ISSUE TITLE
Use the user's name in appropriate places in the app

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#18]

**Comment by ezl** [comment]
signup screen DOES accept a "name" value for the user.

However, It's not clear what that does. I couldn't find anywhere where the username is used.

1. in the welcome email we send them (would be nice to say  "hi {firstname}"
2. when they click the verification link and they see a login screen or loading screen
3. anywhere else in the app (settings, for example, or on the name for the ideas)

**Comment by ezl** [comment]
Renamed this ticket from

`At signup, accept user name and forward it at login success.` to current one.

See specific places in previous comment as a starting point.

**Comment by ezl** [comment]
@aldarund I can't check this easily because I can't set the name on my account.
