### ISSUE TITLE
on idea creation from website, show individual id page after idea creation

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#180]
i tried creating an idea, and after submitting, it shows a 404.

it should show the actual idea page and a success message.

**Comment by aldarund** [comment]
Cant repro. Can you share some video maybe?  You can use https://birdeatsbug.com/ for this, really easy @ezl

**Comment by ezl** [comment]
tested:

false / 404 on firefox 73

no problems on firefox 74 or on chrome 80.0.3987.132

**Comment by ezl** [comment]
closing. seems like a fluke on just this browser.

**Comment by ezl** [comment]
reopening. @f-prime found it, assigning to him.

**Comment by f-prime** [comment]
I am not sure if this issue has been indirectly addressed but I can no longer seem to reproduce it. I create an idea and it redirects me to the idea properly.

**Comment by ezl** [comment]
ok -- reclosing. :) 

if it's an issue it will resurface.
