### ISSUE TITLE
The "sign up" button is present for a logged in user

### ISSUE THREAD

**Issue by GildedHonour** [ezl/dailyidea.com#193]
Should we remove it?

<img width="1418" alt="Captura de pantalla 2020-03-16 a la(s) 15 22 24" src="https://user-images.githubusercontent.com/2032888/76744264-e1762780-676b-11ea-8f1b-6e625db775eb.png">

**Comment by ezl** [comment]
no need -- leave it for now.

i appreciate that you made the ticket though -- and that you considered this. 

closing.
