### ISSUE TITLE
Redirect bare -> www

### ISSUE THREAD

**Issue by GildedHonour** [ezl/dailyidea.com#194]
There have to be 2 records: A and CNAME. 

The A exists for the both bare and "www". But it's incorrect, it instead has to contain only the "www" domain. 

The bare one has to point to the www one as CNAME.

The CNAME doesn't exist. 

```
dig dailyidea.com

;dailyidea.com.			IN	A

;; ANSWER SECTION:
dailyidea.com.		59	IN	A	13.227.185.39
dailyidea.com.		59	IN	A	13.227.185.78
dailyidea.com.		59	IN	A	13.227.185.97
dailyidea.com.		59	IN	A	13.227.185.32
```
and

```
dig www.dailyidea.com
;www.dailyidea.com.		IN	A

;; ANSWER SECTION:
www.dailyidea.com.	59	IN	A	13.227.185.39
www.dailyidea.com.	59	IN	A	13.227.185.97
www.dailyidea.com.	59	IN	A	13.227.185.32
www.dailyidea.com.	59	IN	A	13.227.185.78
```

It's set up via a the dashboard of the domain. I need access to it or will anyone create CNAME? @aldarund @ezl

**Comment by GildedHonour** [comment]
There may be additional stuff required to do a redirect too, at AWS/serverless level.

**Comment by aldarund** [comment]
Both www and non www aliased via aws s3 to same aws lambda. I can change later to CNAME but its dont affect redirect routine.
At serverless you can just change handler in front and add custom redirect logic there

**Comment by GildedHonour** [comment]
> Both www and non www aliased via aws s3 to same aws lambda. 

Yes. That's why they're deemed different websites by Google. Maybe by other search engines too.

Namely, Google sees "www.dailyidea.com" and "dailyidea.com" as different websites. Whereas it should them as a single website, the "www" being the main one.

Therefore, Google will punish one of them by lowering its position in search, because of being the exact duplicate of the other.

**Comment by GildedHonour** [comment]
CNAME doesn't do a redirect on its own - yes. Nor will it affect SEO ranking.

Then the steps will be:

1) remove the "dailyidea.com"  A record
2) leave "www.dailyidea.com" as is
3) do a 301 redirect from the bare domain to www via AWS lambda
4) optionaly - add CNAME record "bare domain -> www"

Yes? @aldarund

**Comment by aldarund** [comment]
1 and 4 connected. if we just remove 1 without 4 it wont do anything.
so for now we can just do 2 and 3

**Comment by GildedHonour** [comment]
@aldarund 

> Where do you see aliases?
> 
> dig dailyidea.com returns A records
> dig www.dailyidea.com returns the same A records + one A record for IPv6
> 
> no aliases.

**Comment by GildedHonour** [comment]
Where do you see that they are "aliases"?

El 19 de marzo de 2020 5:59:13 GMT+05:30, Dmitry Molotkov <notifications@github.com> escribió:
>Both www and non www aliased via aws s3 to same aws lambda. I can
>change later to CNAME but its dont affect redirect routine.
>At serverless you can just change handler in front and add custom
>redirect logic there
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ezl/dailyidea.com/issues/194#issuecomment-600924381

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
