### ISSUE TITLE
Homepage Top Section

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#205]
**Header Section**
![image](https://user-images.githubusercontent.com/50846999/77570894-21a87900-6ed5-11ea-8759-04496d569ce9.png)
- limit the text section to two styles of typography, big heading and small body text (16px)

**Signup Button**
![image](https://user-images.githubusercontent.com/50846999/77570938-3422b280-6ed5-11ea-9ac2-a8cd489905c3.png)
- remove the button shadow, flat design will look better and change the border radius of the button to 5-10 px instead of full rounded / also add up more padding top and bottom on the button + change the color of the `yellowish` platform color

**Remove Search bar**
Remove the search functionality from the homepage could be removed, it would be better if we encourage the user first to learn about the platform, then see the ideas section below, see all the ideas and then give them the search functionality there

**Comment by ezl** [comment]
cancel ticket. resolved by other open tickets:

1. fonts - we are reworking the entire page markup to use less individual custom stuff
2. signup button style -- disagree, i like it as it is.
3. search bar - currently in aldarund's queue
