### ISSUE TITLE
Sign up and Login page copy

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#209]
Add copy below the login fields that indicate what will happen next.

# signup

> We'll send you an email that contains a confirmation link. This will be the email address you'll use to interact with the site going forward.

# login

> We'll send you a magic login link, which will take you directly to your dashboard.

**Comment by ezl** [comment]
Notes to Daosh:
removed note about color gradient. this is resolved by another ticket to fix ALL site buttons.
rejected recommendation to change greyed out bulb - this is deliberate. grey before auth, lit up after auth.
rejected changing images. wait til later.
