### ISSUE TITLE
My ideas / Saved ideas / All ideas - empty state

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#216]
**Illustration**

![image](https://user-images.githubusercontent.com/50846999/77598065-841b6c80-6f09-11ea-84a1-abf39000d08c.png)

Shrink this light bulb image to be 1/2 the height and width of it's current size.

**Arrow**

![image](https://user-images.githubusercontent.com/50846999/77598335-34897080-6f0a-11ea-9355-d48bca65e9b8.png)

Remove this area altogether

**Add an idea button**

![image](https://user-images.githubusercontent.com/50846999/77598112-a7deb280-6f09-11ea-9173-97ef5f33f2f9.png)

remove this circular floating "add idea" button

** Add an idea button**

Change the empty state area to just use this copy:

> You don't have any ideas here yet.
> 
> When you do, they'll show up here.
>
> [button][icon plus-sign] Add an idea[/button]

**Comment by ezl** [comment]
done
