### ISSUE TITLE
User Dashboard: Profile

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#218]
![image](https://user-images.githubusercontent.com/50846999/77598758-4f101980-6f0b-11ea-9bae-90d3ea6eead2.png)

**Suggestion**
- make the profile show recent activity that can be opened instead of `my ideas` section as we already have `my ideas` in a separate page, and also as a link in the navbar

**Comment by ezl** [comment]
cancel. maybe in the future.
