### ISSUE TITLE
Individual Idea Page

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#219]
**Content box**
![image](https://user-images.githubusercontent.com/50846999/77598898-c180f980-6f0b-11ea-97a3-88c89bbfa295.png)
- push the content to the bottom slightly so the page can breathe, don't have it right next to the navbar

**Public/Private functionality**
![image](https://user-images.githubusercontent.com/50846999/77598985-fd1bc380-6f0b-11ea-9b87-c21053e33197.png)
- don't show to users that this idea is public, show this to the idea creator only so it can be switched to public/private
- transfer the public/private toggle in the three dots (options) about the idea

**Bookmark/Save Idea Graphic**
- change the save icon with a heart instead of `save bookmark` icon, a better indication of "favorite" functionality

**Search**
![image](https://user-images.githubusercontent.com/50846999/77599062-3c4a1480-6f0c-11ea-86d2-8fdc5749ab54.png)
- the search functionality looks like it is supposed to search for this page only, remove it from this page (?)

**Time of the post indicator**
![image](https://user-images.githubusercontent.com/50846999/77599090-54219880-6f0c-11ea-9261-d02401879c9e.png)
- move the time indicator next to `person's idea` label under the heading, it is more suitable in a group with similar information rather than being thrown on the side

**Margin between the text box and the comment box**
![image](https://user-images.githubusercontent.com/50846999/77599129-70253a00-6f0c-11ea-93d2-cd5dc4eaa886.png)
- add some margin to the text box so it can be from the comments section better and the page can breathe

**Suggestions**
- add a scroll bar and fixed height to the idea body section so whenever there's a large idea, users won't have to scroll to the bottom of the page and the comment section will be always visible

**Comment by ezl** [comment]
![v](https://user-images.githubusercontent.com/157627/79494191-349bfe00-7fe8-11ea-938b-ca6118bf2fae.png)
