### ISSUE TITLE
Add an Idea Page

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#220]
**Section Containers**
![image](https://user-images.githubusercontent.com/50846999/77599282-e033c000-6f0c-11ea-8c2f-0d80ac6f8a7d.png)
- make a template that will structure this section with containers instead of just a text without containers

**Hamburger menu on the right**
![image](https://user-images.githubusercontent.com/50846999/77599306-f0e43600-6f0c-11ea-9110-370a330402d9.png)
- this looks like a hamburger menu that shouldn't be here, add a field for formatting options on the bottom that will always be shown instead

**Illustration**
![image](https://user-images.githubusercontent.com/50846999/77599319-fccff800-6f0c-11ea-9cd1-b38ba162de3d.png)
- change the illustration, looks like being thrown there randomly (?)

**Submit Button**
![image](https://user-images.githubusercontent.com/50846999/77599338-0bb6aa80-6f0d-11ea-8c50-bb151fa8a3a9.png)
-change the color to solid, the darker yellow for more contrast with the button text inside

**Comment by ezl** [comment]
Closing this. Grammarly style copying supercedes this ticket.
Submit button will be resolved by global styles.
