### ISSUE TITLE
Mobile: Homepage Cards

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#228]
![image](https://user-images.githubusercontent.com/50846999/77600334-4837d580-6f10-11ea-98e5-9a90343da170.png)

- make the same style of cards as desktop, as recommended above, use a different fixed height for the cards on mobile

**Suggestion**
- display only 3 cards on the homescreen and make them fixed height as well, so users won't scroll that much

**Comment by ezl** [comment]
1. fixed height implemented.
2. only 3 cards being displayed.

completed so closing issue.
