### ISSUE TITLE
Mobile: Footer

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#229]
![image](https://user-images.githubusercontent.com/50846999/77600381-74ebed00-6f10-11ea-8237-b5c03cc51d77.png)

## Current status / problem:

This footer is terrible. Unnecessarily uses 2 different fonts and the spacing is very non-standard.

## Solution should look like this:

- At wide viewports, links on left and copyright on right.
- At narrow viewports, 4 links in one row and copyright below it. All centered.
- same font size

## Notes:

- Assume no existing CSS has to stay in place. if existing directives don't make sense, kill them and note it.
- Feel free to refactor and use built in vuetify helper classes instead

**Comment by ezl** [comment]
cancelling
