### ISSUE TITLE
Mobile: Log in/Sign Up Pages

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#230]
![image](https://user-images.githubusercontent.com/50846999/77600466-b67c9800-6f10-11ea-8b68-2f4e096202f3.png)

Task:
instead of leaving the hamburger that opens the full menu on the login and signup pages, just put an X in the upper right corner that goes back to the preceding page.

**Comment by ezl** [comment]
modification to ticket:

instead of leaving the hamburger that opens the full menu on the login and signup pages, just put an X in the upper right corner that goes back to the preceding page.

reason:

i like having login and signup pages have less paths out which distract users
