### ISSUE TITLE
Mobile: Settings Area

### ISSUE THREAD

**Issue by inflameous48** [ezl/dailyidea.com#232]
![image](https://user-images.githubusercontent.com/50846999/77601185-afef2000-6f12-11ea-8b46-106958ed9419.png)

![image](https://user-images.githubusercontent.com/50846999/77601167-a36ac780-6f12-11ea-96c9-03f64c915833.png)

- grey out email field so it doesn't look like an editable input field
- remove the lightbulb background above "Settings" header

**Comment by ezl** [comment]
Modification on this ticket:

1. DO grey it out  and make it so it doesn't look like an editable input field
2. Do not do the pen icon  to change email address -- supporting email change requires more work than worth it at this time.
