### ISSUE TITLE
Give users placeholder avatars

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#270]
https://avatars.dicebear.com/

1. Generate a placeholder avatar for all users that don't have one.

2. Give all new users an avatar on signup.

Use "botts"

**Comment by ezl** [comment]
@f-prime apologies, i wasn't clear.

On https://avatars.dicebear.com/ there are various different avatar sets. One of the sets is titled "bottts": https://monosnap.com/file/GZh2jYmX8bDhFoUeppMhpTfzhLF49q

You used the default avatar set ("male") and used "bottts" as the seed for the random avatar generator.

What I meant was to use the bottts set and then generate a random avatar for each user when they sign up.

**Comment by f-prime** [comment]
> @f-prime apologies, i wasn't clear.
> 
> On https://avatars.dicebear.com/ there are various different avatar sets. One of the sets is titled "bottts": https://monosnap.com/file/GZh2jYmX8bDhFoUeppMhpTfzhLF49q
> 
> You used the default avatar set ("male") and used "bottts" as the seed for the random avatar generator.
> 
> What I meant was to use the bottts set and then generate a random avatar for each user when they sign up.

Ah, this makes more sense.  I should have asked. I will make the fix.
