### ISSUE TITLE
create static pages for about, faq, terms, privacy

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#282]
For now, just create the pages so the routes exist (as simple as creating the files in the path, since nuxt.js handles routing automatically for us -- if you're not familiar with this, look at nuxt.js docs on routing).

importantly, try to make sure you're using a single layout type so we store minimal style/structure data in each individual page (DRY as possible)

4 pages:
- faq
- about
- terms
- privacy

**Comment by vedmant** [comment]
I see there is footer hardcoded into index page and not common layout, not sure if it makes sense to put footer into common layout so I just moved footer into separate component to be included where needed. Better solution will be to include footer to common layout, but if some pages don't require footer then it needs a prop option to disable it.
