### ISSUE TITLE
? does login button appear in header on sign out?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#293]
if you're currently logged in and sign out from the home page, does the login button reappear in place of the logged in header info?

what happens if you do this from an internal dashboard page?

**Comment by vedmant** [comment]
Looks like if I signed out dropdown menu disappears but 'Log in' doesn't appear on it's place. It only affects desktop version, mobile menu works ok. Should I fix this?

**Comment by ezl** [comment]
yes, please fix @vedmant

**Comment by vedmant** [comment]
It's merged now
