### ISSUE TITLE
polish the modals during unauthenticated save

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#300]
fix modals for unauthenticated save

# case 1: non user
info collection 1 (email): "Introduce yourself?" -> "What's your email" https://monosnap.com/file/PStUPuzmqxRUuGvf3ztrDbAmGst7eb
info collection 2 (name): "Almost there" -> "Anonymous user just doesn't feel so personal... :)" https://monosnap.com/file/fmLc89Qkah2A2yuqtdzvuIQLx82BuE
successful information received -- add an image of a party or success (clicking ok searches for the email in the user's gmail?)
successful verified - "hooray" -- you've saved your first idea. all your saved ideas will be available in your account from now on. Do you want to: go ack to the idea you saved (close), browse other ideas (all/popular), start entering your own great ideas (ideas/create)?

# case 2: existing user:

do we have the user's name? If so, use it in the modals.

after email collected -> "We sent you a confirmation email. Please check your inbox and click the verification link in the message so we can make sure we're saving this idea to the right account." -> improve this copy or insert line break after "we sent you confirmation email".

https://monosnap.com/file/aY8pdHOmxHNsE168Vx6yH2NoVjce4C <-- improve this

**Comment by vedmant** [comment]
@ezl 

> successful information received -- add an image of a party or success

Right now dialog is this: https://prnt.sc/swydud . What image I should use, where to get it? 

>  (clicking ok searches for the email in the user's gmail?)

I can redirect to gmail if email address is gmail.com


> case 2: existing user
> do we have the user's name? If so, use it in the modals.

We don't have user name before user is authenticated. I'll add user name to "Yay" dialog.

**Comment by ezl** [comment]
sent to you via slack, @vedmant - filename: undraw_arrived_f58d.svg (github does not allow me to attach an svg)

**Comment by vedmant** [comment]
[undraw_arrived_f58d.svg.zip](https://github.com/ezl/dailyidea.com/files/4804745/undraw_arrived_f58d.svg.zip)

**Comment by vedmant** [comment]
- [x] successful information received -- add an image of a party or success
- [x] Redirect to gmail if email address is gmail.com
- [x] Add user name to "Yay" dialog
