### ISSUE TITLE
send users notifications when they get comments on their ideas

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#311]
when a comment is left on an idea, notify the user via email.
when someone likes an idea, notify the user via email.
allow the user to opt out of these via their email preferences.

**Comment by Watson-B** [comment]
Some first passes at light and dark mode for email alerts

**Comments and Likes**
<img width="375" alt="all activity_dark" src="https://user-images.githubusercontent.com/65913664/89925206-effc2a00-dbb7-11ea-8502-87c8815d24f0.png">
<img width="375" alt="all activity_light" src="https://user-images.githubusercontent.com/65913664/89925208-f094c080-dbb7-11ea-8d85-6b03d0d22f07.png">

**Multi Comments**
<img width="375" alt="multi comments_dark" src="https://user-images.githubusercontent.com/65913664/89925303-11f5ac80-dbb8-11ea-8723-1c3049296720.png">
<img width="375" alt="multi comments_light" src="https://user-images.githubusercontent.com/65913664/89925304-11f5ac80-dbb8-11ea-8adf-77cb1c55460a.png">

**Multi Likes**
<img width="375" alt="multi likes_dark" src="https://user-images.githubusercontent.com/65913664/89925324-18842400-dbb8-11ea-8782-ce4fcba500a1.png">
<img width="375" alt="multi likes_light" src="https://user-images.githubusercontent.com/65913664/89925327-191cba80-dbb8-11ea-82ea-cb144bcfc351.png">

**Single Like**
<img width="375" alt="one like_dark" src="https://user-images.githubusercontent.com/65913664/89925354-246fe600-dbb8-11ea-82cb-3ad5dcf283f9.png">
<img width="375" alt="one like_light" src="https://user-images.githubusercontent.com/65913664/89925356-25087c80-dbb8-11ea-83e1-adc5b5d46d68.png">

**Email Unsubscribe Footer**
<img width="375" alt="break footer_dark" src="https://user-images.githubusercontent.com/65913664/89925367-29349a00-dbb8-11ea-9e4b-080f9f7cfd3f.png">
<img width="375" alt="break footer_light" src="https://user-images.githubusercontent.com/65913664/89925368-29349a00-dbb8-11ea-80d7-a600856d241e.png">

**Email Settings**
<img width="415" alt="email settings" src="https://user-images.githubusercontent.com/65913664/89925385-305ba800-dbb8-11ea-97bd-632f445acef7.png">

**Comment by Watson-B** [comment]
@ezl @alisonuxdesign tagging for feedback

**Comment by alisonuxdesign** [comment]
@Watson-B  i like this, I kind of want to add a bit of illustration tho. I'll play around and see if I can make it look okay without taking up too much space

**Comment by ezl** [comment]
snooze for 1/2/4 weeks -- Do you think it would be possible to get them inline on one row instead of 3 rows? snoozing is an important pattern, i think, but not so important that i would want it to take up so much vertical screen space.

**Comment by Watson-B** [comment]
<img width="375" alt="break footer_dark" src="https://user-images.githubusercontent.com/65913664/90064816-2d3be700-dca0-11ea-9330-d4eb22546d4c.png">
<img width="375" alt="break footer_light" src="https://user-images.githubusercontent.com/65913664/90064819-2d3be700-dca0-11ea-9661-7be54ef36167.png">
Yeah, we can make that work

**Comment by ezl** [comment]
I prefer that -- OK with you too @alison?

--Eric

**Comment by alisonuxdesign** [comment]
yeah @Watson-B and @ezl I like this horizontal layout better. Going to add illustrations and then move this forward into implementation.

**Comment by vedmant** [comment]
@ezl I have some concerns about multiple comments notifications. I see in design emails are like "you have 2 new comments" the question is 2 new comments since when, last login or last time user opened that specific idea, or something else?

Also about likes "10 people liked your idea" - is this total idea likes or also some number after some point in time?

**Comment by vedmant** [comment]
- [ ] Idea activity setting
- [ ] New likes notification
- [ ] New comments notification

**Comment by ezl** [comment]
@vedmant this is a very good point and a valid concern.

If I'm understanding correctly, your question is:

if a person receives 1 comment every hour on Thursday on a SINGLE, should that person get:
(A) 24 emails, each sent immediately after the comment was made?
(B) 1 email at midnight on Thursday saying 24 comments have been received?

In the above, (A) has the benefit of immediacy, which allows users to respond to each other, but has the penalty of potentially flooding their inbox. (B) is batched, which solves the inbox flooding, but might remove the ability for quick responses. Variants of (B) include batching and sending hourly, sending at a different time (not midnight), or every day at 10am and 3pm.

if the person receives 3 comments on idea `foo` and 5 comments on idea `bar`, should that person get:
(C) a single email saying "8 comments have been received on multiple ideas"
(D) 2 separate emails: one for each idea

The message subjects above are for a *single* idea. If it's a single idea, I feel like we might want to include the actual idea title in the subject.

What does FB do here on comment replies? What do other platforms do (IG, Twitter, Quora)?

@alisonuxdesign @Watson-B

**Comment by vedmant** [comment]
@ezl Please let me know which way to go here.

Also I'lll continue here after completing https://github.com/ezl/dailyidea.com/issues/522 as it will require migration for the ideaActivity setting.

**Comment by ezl** [comment]
cc @alisonuxdesign

**Comment by alisonuxdesign** [comment]
I'm sorry guys I totally dropped the ball on this, I designed the screens and then just didn't attach them. @vedmant github isn't letting me attach right now so I will slack designs to you and try again.

**Comment by alisonuxdesign** [comment]
okay so what i’m thinking and open to suggestion is:
if a person receives 1 comment every hour on Thursday on a SINGLE idea, should that person get: 1 email at midnight/another time of day on Thursday saying 24 comments have been received. I think we don’t want flood people’s emails and if we REALLY want this feature we are better off with making a native app with push notifications instead of spamming people. I think that will get super old fast if we are sending a ton of separate emails, pretty much rendering this feature useless/unused.


For the email itself:
I redesigned these emails to just a generic text that says “your ideas are getting action and then in the email say which ideas are getting comments: snow cones for dogs has 3 new comments, idea about a waterproof ukelele has 12 new comments or something of the sort. Any thoughts on this particular point?

**Comment by ezl** [comment]
Agreed @alisonuxdesign.

So @vedmant - the decision here is that once a day, we will notify the user of his/her updates.

from an implementation perspective, consider that in the future, we'll want to be able to have a notification center in the app/website where the user can see notifications since his/her last login.

so for this issue, i think the right implementation is to:

1. NOT send immediate emails
2. In fact, we don't even need the actions (like/save/comment) to *trigger* any sort of notification or event

Instead, a cron job (or celery or whatever repeating task):

1. search for all comments/likes/saves in the last N hours (N=24)
2. compile an email and send

This can later be adapted to search for all comment/like/save since `user.last_login` or something like that to show the correct number of notifications.

**Comment by vedmant** [comment]
@ezl I probably need new template that will incorporate all updated for user ideas. Like one email that will list all updated ideas, then each idea will have stats like number of likes (who liked), number of comments (limited comments list), number of saves. I think it makes more sense then sending separate emails for each idea / comments / likes / saves.

**Comment by ezl** [comment]
ok. cc @alisonuxdesign

**Comment by vedmant** [comment]
<img width="375" alt="multi comments_light" src="https://user-images.githubusercontent.com/5052406/91059960-09c75380-e633-11ea-8939-f58c6e53eac7.png">

**Comment by vedmant** [comment]
@alisonuxdesign When there are multiple ideas, where View Comments button will lead?

**Comment by alisonuxdesign** [comment]
hey @vedmant button will lead eventually notification page but for now, let's assign it to "my ideas" section. Also, I wasn't able to attach this to Github so I slacked it to you- look a few comments up in our thread. also right here: 
[Email DI.zip](https://github.com/ezl/dailyidea.com/files/5130534/Email.DI.zip)

**Comment by vedmant** [comment]
@alisonuxdesign In the latest template I don't see snooze buttons, but you have them in zip file, should I add them?

**Comment by alisonuxdesign** [comment]
yes, the full design here: 

<img width="375" alt="break footer_light" src="https://user-images.githubusercontent.com/63747360/91319055-2a012a80-e779-11ea-9da5-cdae5f89e3c1.png">
<img width="375" alt="multi comments_light" src="https://user-images.githubusercontent.com/63747360/91319059-2a99c100-e779-11ea-89b9-95e028236c85.png">
