### ISSUE TITLE
Improve dialog experience on mobile

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#314]
![image](https://user-images.githubusercontent.com/157627/81234847-33df0200-8fbf-11ea-8fd7-8e3b735315bf.png)

1. Scrolling - bootstrap does this better. Scroll the modal up and down, not the content within it.

2. Wider form, wider overall content (less margin on mobile)

**Comment by vedmant** [comment]
I'll need to fork branch for this dialog from #331 , I think it makes sense first to merge https://github.com/ezl/dailyidea.com/pull/341 but I added there a comment about if I should refactor all other dialogs in the app, if yes then I need to to that first also.

**Comment by vedmant** [comment]
Yes, I'll start only after modal are refactored as it makes sense to work on this one only then.
