### ISSUE TITLE
use random idea quotes in emails

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#315]
https://docs.google.com/spreadsheets/d/1tB4AQWBD3zACNq8RauMWDFLnHf5chKOQ-PU28IJYlEE/edit#gid=0

**Comment by f-prime** [comment]
Want to confirm two things about this issue.

1. The rows with the `x` in the include column are the quotes to choose from?
2. The quotes being referenced here would show up under `What's your daily idea?` which currently is just one quote by Johann Wolfgang von Goethe ?

**Comment by ezl** [comment]
Correct, @f-prime 
"X" in column A in the google sheet means it should be included in our repository of quotes.

Implementation-wise, I was thinking that we convert the quotes into a JSON object like:

```
[
  {
    'quote': "If I have a thousand ideas and only one turns out to be good, I am satisfied.",
    'by': "Alfred Bernhard Nobel",
    'source': "https://ineedmotivation.com/45-unforgettable-quotes-about-ideas/"
  },
  {
    'quote': "A pile of rocks ceases to be a rock pile the moment someone contemplates it with the idea of a cathedral in mind.",
    'by': "Antoine De St-Exupery",
    'source': "https://www.goodreads.com/quotes/121975-a-rock-pile-ceases-to-be-a-rock-pile-the"
  },
  { ... }
]

```

Then we can have a thin layer that either returns a numbered or random result from that JSON object (or python array of dicts)

I'm not sure if that's the "right" implementation.

Thoughts:

1. It'd be nice to have it totally separated so we can just query it and get a quote

```
class QuoteLibrary
quotes = [{}, {}, {}]
def random(self): return random.choice(self.quotes)
def get(self, n) return self.quotes[n] # don't die if n > len(quotes) though
```

2. On the other hand, since we're going to be sending tons of emails that include this quote, we don't really want it to be a separate SERVICE because we'll be querying it a shit ton.

Thoughts?

**Comment by f-prime** [comment]
Okay, that was pretty close to the implementation that I had in mind. I was thinking there would be a some file `generate_quote.py` or something that has code similar to what you wrote. Then `send_request_daily.py` or whatever needs it would import and use it. I am not sure if there are any gotchas with that though when it comes to SES.

**Comment by ezl** [comment]
👍
