### ISSUE TITLE
"unsubscribe from everything"

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#319]
have a separate endpoint which unsubscribes the user from all emails.

when that page is loaded, displays a page that says:

> 
> {{ firstname }}, you've been unsubscribed from all emails.
> 
> This has removed these emails: 
> - daily idea reminder
> - weekly digest of ideas from other people
> - your weekly stats (people who have liked or commented on your ideas)
> 
> If you'd like to reinclude any of these or update your email preferences, link(click here)
> 

that link just forces a log in, and on login, it directs the user straight to the settings page

**Comment by ezl** [comment]
@aldarund lets leave this for @vedmant to try.

@aldarund when you implement the emails, you can just make the link go nowhere, then we'll make it work later.

@vedmant there's currently a way in emails for us to "snooze" emails already (see commit a818bdf)

you can use this as a starting point for executing this ticket.

**Comment by vedmant** [comment]
@ezl OK, I need to learn more about Appsync, I didn't use it before, what makes it complex is that I can't run this locally to test changes I make.

**Comment by vedmant** [comment]
Subtasks

- [ ] Create unsubscribe endpoint that will add unsubscribedAt timestamp field
- [ ] Update request_daily_idea function to skip unsubscribed users
- [ ] Update newly created weekly digest function to skip unsubscribed users

**Comment by vedmant** [comment]
@ezl 

> daily idea reminder
weekly digest of ideas from other people
your weekly stats (people who have liked or commented on your ideas)

As I understand we have currently implemented only "daily idea reminder" and my pull request for "weekly digest"?

**Comment by ezl** [comment]
correct -- those are the only 2 emails that are implemented at this time.

--Eric
