### ISSUE TITLE
don't show formatting on idea preview styles

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#325]
keep: bullet and list

remove everything else: bold and bigger fonts, link styles, underlines.

**Comment by vedmant** [comment]
@ezl Do you mean cards on https://www.dailyidea.com/ideas/all ? This might be simpler to do on backend, for example with https://pypi.org/project/html-purifier/ (with PHP I always use https://github.com/ezyang/htmlpurifier for this), on frontend I can use some regex but it might be not that robust.

**Comment by ezl** [comment]
hmmm that's a valid point, @vedmant -- i'm moving this back to icebox for now to think about it. no action on this for now.
