### ISSUE TITLE
implement weekly stats email

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#328]
https://email-designs.s3-ap-southeast-2.amazonaws.com/weeklyStats.html

images are already in appropriately named folders in mail-processing images path. each email has its own folder now.

remove any images that were used for the previous email that you are replacing (grep project to make sure it's not used elsewhere first

See recent commits by @aldarund as an example of how how to work with emails:
https://github.com/ezl/dailyidea.com/commit/3a196c110950a657949fa58708257b7a9af31d0f

**Comment by vedmant** [comment]
@ezl Should redo this email with MJML to make things consistent?

**Comment by ezl** [comment]
yes. this one do it in mjml.

**Comment by vedmant** [comment]
@ezl Ok, work in progress, appsync part of this task takes a lot of time for me as I'm not experienced with Dynamodb.

**Comment by vedmant** [comment]
@ezl How email should look in case stats are 0 https://prnt.sc/td9p8p ?

**Comment by ezl** [comment]
looks like there's already a PR for this @vedmant -- do you still need feedback or did you figure something out?

**Comment by vedmant** [comment]
@ezl Yes, I create PR, task is complete, I created PR is case @aldarund requests some changes. I still have the question about 0 stats or partly 0 stats.

**Comment by ezl** [comment]
@vedmant sorry, can you clarify what the question is?

are you asking if we should use different copy for the case of 0 ideas? (probably we should) and if so are you asking for the copy to be created?

or are you asking something else?

**Comment by vedmant** [comment]
@ezl The question is about if email should render different text if there are 0 stats, or don't event send email if all 0s. Here is example https://prnt.sc/td9p8p

**Comment by ezl** [comment]
Understood.

My 2 cents:

Regarding the 3 bullet points below -- just use the same format/template, regardless of the numbers. so if it's 0/0/0 -- render it like the screenshot you sent with all zeros.

However, the COPY should vary a little bit:

- [ ] If there are zero submitted ideas, change the first sentence from "Most importantly, you submitted 0 ideas for the week! Congrats!" to "Bummer! You didn't submit any ideas this week. That's ok though! Try to get 1 idea next week -- or `<a>submit one now by clicking here</a>`
- [ ] Make sure that the special case of 1 is handled regarding "0 ideas" "1 **idea**" "2 ideas" and "0 people" "1 **person**" "2 people (i.e. in both the sentence above and the 3 bullet points below, all the words following the number should be plural, except in the case where the value is 1, then use singular.

**Comment by vedmant** [comment]
Ok, done, pr is ready.
