### ISSUE TITLE
Update "shared idea" email

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#329]
There's an idea that has a "so and so has shared an idea with you" message.

Update it to use this markup:

https://email-designs.s3-ap-southeast-2.amazonaws.com/sharedIdea.html

images are already in appropriately named folders in mail-processing images path. each email has its own folder now.

remove any images that were used for the previous email that you are replacing (grep project to make sure it's not used elsewhere first

See recent commits by @aldarund as an example of how how to work with emails:
https://github.com/ezl/dailyidea.com/commit/3a196c110950a657949fa58708257b7a9af31d0f

**Comment by vedmant** [comment]
What's appropriate way to test idea sharing and email, should I register with another email?

**Comment by ezl** [comment]
tbh i just use the `+` trick with gmail
https://gizmodo.com/how-to-use-the-infinite-number-of-email-addresses-gmail-1609458192

**Comment by vedmant** [comment]
I updated template.

There is a question about idea content, there was no code for truncating idea content, should I add it? If yes then what will be the logic for truncated content, what html tags should be allowed or all tags removed, if removed what about newlines (they will be also removed then)? Currently without truncate it just adds idea content as is https://prnt.sc/sirfsu
