### ISSUE TITLE
fix modals in "share" and "save" flow to use the new style

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#331]
make the modals in the "share" flow match the new modal style.

previously modals looked different across the entire site.

now they are ALMOST the same, but this is one of the few places where it looks a little different still.

To see the desired style, as an unauthenticated user, try to SHARE an idea (click the share button on any idea detail page), it should look like: https://monosnap.com/file/hG5HElHTkQGvYlgMB7XkFXlhTHt3RV

Now, as an UNAUTHENTICATED user try to either:

1. share an idea with someone
2. save an idea

in both of these cases, you should see modals with different styles from the desired one.

make these modals all use the same style.

bonus: there's a lot of repeated code through ALL the dialogs -- unify them (do this as a separate commit)

**Comment by vedmant** [comment]
@ezl Can I do some refactoring on some components (simpleDialogPopup.vue specifically)? I see that it's done a weird way through refs, that's not how Vue components are supposed to work.

**Comment by vedmant** [comment]
Modals to refactor:

- [ ] simpleDialogPopup
- [ ] onFirstIdeaSavedDialog
- [ ] onIdeaSavedByLogInLinkDialog
- [ ] onUnAuthActionAskEmailDialog
- [ ] onUnAuthActionAskNameDialog

**Comment by ezl** [comment]
yes, PLEASE refactor! :)

code in this app is NOT very DRY in many places, if you see ways to improve maintainability, please do.

make sure you do so in ways that are easy to review pull requests though, so it'll be easier for me or @aldarund to review and merge.

**Comment by aldarund** [comment]
refs is not very common, but for modals its way more common to use. for example its even mentioned in vue bootstrap docs as a way to do it.
How do u want to refactor it, can you show what u have in mind?

**Comment by vedmant** [comment]
@aldarund to appropriate Vue usage with props, events and slots, calling vue component function directly from other component is absolutely not appropriate way to do things in Vue. Vue bootstrap has a helper plugin to add global variable to all components and open modal with function and it's not doing it the way you coded it https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/modal/helpers/bv-modal.js 

After I refactor it will be much cleaner and sane.

**Comment by vedmant** [comment]
I'll add a plugin for simple confirm and message dialogs, that's weird that Vuetify doesn't have this out of the box.

**Comment by vedmant** [comment]
Almost done, there is one error on adding comment I need to debug, I'll finish it tomorrow. I'll need to test all cases also as I did a lot of changes.

**Comment by vedmant** [comment]
There are list of other dialogs, I think it makes sense also refactor them so all dialogs will extend base dialog?

Here is the list:

- [ ] commentWithoutLogin
- [ ] makeIdeaPrivateDialog
- [ ] makeIdeaPublicDialog
- [ ] registerEncourageDialog
- [ ] resendAuthEmail
- [ ] saveIdeaWithoutLogin
- [ ] shareIdeaByEmail

**Comment by ezl** [comment]
yes, refactor.

**Comment by vedmant** [comment]
Looks like there were two abandoned components dialogs/SaveIdeaWithoutLogin.vue and profilePage/SaveIdeaBookmark.vue . Maybe it's good idea to delete files that are not used anymore, cause this confused me as I tried to refactor abandoned SaveIdeaWithoutLogin dialog. So I deleted this two components.
