### ISSUE TITLE
make it possible for site administrators (me? support?) to remove/deactivate accounts and delete ideas

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#337]

**Comment by vedmant** [comment]
@ezl As I understand there is no admin dashboard for the site? I'd suggest to create one where admin can manage all the data.

**Comment by ezl** [comment]
ugh yes, this is necessary i guess. it's a lot of work to build an admin. lets keep this an active conversation topic, but not ready to execute quite yet.

**Comment by vedmant** [comment]
@ezl Usually it's not a big deal when I do Laravel apps, I also have good template for admin dashboards on And Design Vue, the only problem will be with backend as it's on Appsync.
