### ISSUE TITLE
setup sentry

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#338]
@ezl Mentioned that sentry is not setup on the project, we need to setup it for for prod and dev backend and for front end (dev / prod) as well. 

@aldarund It could be partially setup as I see 
SENTRY_DSN=https://b40af20e2e1245e08787c292384fab22@sentry.io/2456242
in configs, is it setup but not shared? If yes lets share then Sentry (dev / prod) projects so I also can see errors.

**Comment by ezl** [comment]
@vedmant my understanding is that Sentry was set up, but we used a sample account to set it up. Perhaps the SENTRY_DSN that is connected to is not available for us to use now.

As a result, I think the only thing required is to set up a new sentry account and enter those details, then it will work.

I was trying to save money by not getting a paid sentry account at the time.

I created a new sentry account that we can attach to it.

I'll DM you the credentials for this Sentry account then can you set it up?

**Comment by vedmant** [comment]
Ok, here are settings as they are not stored in the repo:


front/conf/dev.env:
SENTRY_DSN=https://11a39e4619874cf49a4090743b0ffb7c@o393029.ingest.sentry.io/5241541

back/appsync/conf/dev.env:
SENTRY_DSN=https://16c84b9f74b7435199416ec3a6aee1c9@o393029.ingest.sentry.io/5241531

back/mail-processing/conf/dev.env:
SENTRY_DSN=https://16c84b9f74b7435199416ec3a6aee1c9@o393029.ingest.sentry.io/5241531

back/users/conf/dev.env: (that may need manual sentry integration)
SENTRY_DSN=https://16c84b9f74b7435199416ec3a6aee1c9@o393029.ingest.sentry.io/5241531

I couldn't verify yet if sentry is working on front end, attempts I tried for some reason didn't sent anything to sentry.

I didn't test backend also.

Let me know if I should actually test this properly, I feel like I need to test, but it takes additional time and I don't want to waste it.

**Comment by ezl** [comment]
Please test it.

**Comment by vedmant** [comment]
- [ ] Test front end sentry integration
- [ ] Test appsync backend sentry integration
- [ ] Test mail-processing backend sentry integration
- [ ] Test users backend sentry integration

**Comment by vedmant** [comment]
Looks like on backend Sentry was never intergated, for serverless I need to wrap every handler with helper sentry functions https://github.com/arabold/serverless-sentry-plugin https://github.com/Netflix-Skunkworks/raven-python-lambda

On it already, but it takes more time.
In any case it lets me learn backend code,

**Comment by vedmant** [comment]
On users authentication backend I see an issue with global try catch code, I'll need to add sentry capture functions there manually, generally global try catch is a bad practice so it might be good idea to refactor code there.
