### ISSUE TITLE
implement new "signup" email

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#345]
https://email-designs.s3-ap-southeast-2.amazonaws.com/signup.html

images are already in appropriately named folders in mail-processing images path. each email has its own folder now.

remove any images that were used for the previous email that you are replacing (grep project to make sure it's not used elsewhere first

See recent commits by @aldarund as an example of how how to work with emails:
https://github.com/ezl/dailyidea.com/commit/3a196c110950a657949fa58708257b7a9af31d0f

**Comment by vedmant** [comment]
@ezl @aldarund  Could you explain more about sign up email? I see currently there are two types or email templates `magic_link_template` and `require_login_template`, as I can see`magic_link_template` is used for first time sign in and `require_login_template` for next times, also there are separate templates for `magic_link` and `require_login` when creating new comment or idea.  So the question is where exactly should I implement signup email, for now I can guess that I should replace `magic_link_templat`e, there are however two more templates `magic_link_template_with_comment` and `magic_link_template_with_idea_save` with a bit different design / text, should I just leave them as they are?

**Comment by ezl** [comment]
i also don't know the answers to these questions. ultimately we should be cleaning up the codebase to make it clearer which templates are being actually used or not.

to do this ticket,
1. try signing up on the production website. see what email is sent to you.
2. look at recent commits by @aldarund around https://github.com/ezl/dailyidea.com/commit/3a196c110950a657949fa58708257b7a9af31d0f to guess which templates are the appropriate ones for replacing.
3. make it so that upon signing up on the website, this is the confirmation email that the user sees: https://email-designs.s3-ap-southeast-2.amazonaws.com/signup.html. This should correspond to `back/mail-processing/new_mail_templates_tomboitaliano/signup.html`, which is just included in the repository as a reference, but not used directly anywhere.
4. another way to check to see what templates are actually being used is to try to understand how this email is being triggered and follow the references from that.
5. on completion, if a user signs up on the website, they should receive a confirmation email that looks like https://email-designs.s3-ap-southeast-2.amazonaws.com/signup.html

Ideally through this process you'll have learned what templates are/aren't used in the repository and we can create a secondary ticket around cleaning up by removing unused assets.

I know this isn't as clear and straightforward as someone just telling you -- so this will require a little more work -- but it's good for the project because it will help you become the 2nd person to really understand this (in addition to @aldarund) and you'll be a valuable resource for future changes.

**Comment by vedmant** [comment]
@ezl I see what actual templates are used in the code, main issue was that there are 3 different templates for signup (first login) they all are used for different cases. The question is if I should replace only base one for signup, or all the them, (creating new comment / creating new idea) for the latest I probably need different templates then that will include appropriate messages.

**Comment by ezl** [comment]
Ah sorry I misunderstood.

Correct, only the main signup template.

The other cases will end up using different templates.

**Comment by vedmant** [comment]
Ok, I deployed new email, creating pull request. Btw, there is really cool framework for responsive mail templates https://mjml.io/ it can help to build much simpler code and consolidate all email styles.

**Comment by vedmant** [comment]
[ ] Rebuild template with MJML
