### ISSUE TITLE
[emails] for quote, use (A) cursive/script (B) light grey color; rewrite in MJML

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#347]
Should use this (or another cursive) font:
https://email-designs.s3-ap-southeast-2.amazonaws.com/dailyIdea.html

Color should be light grey.

Not working in gmail.

**Comment by vedmant** [comment]
@ezl Generally custom fonts don't work on many clients, for example Gmail doesn't support custom fonts.

**Comment by vedmant** [comment]
@ezl I changed color and added italic style to font. Btw, could be a good idea to rewrite this template with MJLM?

**Comment by ezl** [comment]
update all emails that have the quote.

how long does it take to rewrite a template with MJML? if 1 hour, do it. if 4, just file it for future dev.

**Comment by vedmant** [comment]
@ezl 

> how long does it take to rewrite a template with MJML? if 1 hour, do it. if 4, just file it for future dev.

I think about an hour for email. It's quite fast to do with MJML.

Here is the list of emails:

1. magic_link_template_with_idea_save.html
1. require_login_template.html
1. require_login_template_with_idea_save.html
1. daily_idea.html

**Comment by ezl** [comment]
correct -- feel free to redo all of them.

**Comment by vedmant** [comment]
@ezl I'll need also to spend some time on testing emails to make sure they work properly:

- [ ] magic_link_template_with_comment
- [ ] magic_link_template_with_idea_save
- [ ] require_login_template
- [ ] require_login_template_with_comment
- [ ] require_login_template_with_idea_save
- [ ] signup_template

**Comment by ezl** [comment]
understood. thank you for testing everything.
