### ISSUE TITLE
make links in daily idea reminder authenticate the user

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#357]
There are 2 links in daily idea reminder force the require to authenticate:

`ideas/create` (submit an idea)
`ideas/settings` (update your email settings)

## Current UX

Currently, if the user is not already logged in to the site, they are redirected to the login page.

This is a suboptimal user interaction because the path:

1. originates in email, they want to enter an idea, so they click "submit idea" from their email client (mood: EXCITED)
2. when they are expecting to enter an idea on the next page, we throw up a road block - NOPE! authenticate first! (mood: deflated)
3. Then they have to click, wait for an emailed magic link, then click back through to enter their idea. At this point we've lost momentum and good vibes.

(In fairness, we do show an appropriate error message already on the login page)

# Preferred path

Ideally, these would take the user straight to this page, authenticated.

if they are NOT authenticated, we would authenticate them and take them to the page in the same click.

what options do we have so that we can make it so users can click this button and if they aren't authenticated they aren't forced to?

# Technical issues

@aldarund you mentioned a problem with this because the links age, but the cognito tokens may not.

We don't have to make it so the links in these emails will be valid forever.

For example, if the one received today or yesterday still authenticates the user, that might be enough. < N days old works, but > N days old doesn't. 

@aldarund - how is the link age controlled for cognito? can we set how long it lasts, like a JWT token? or is it fixed? If it's variable, what is the range?

For links that don't work, for example, if the token is too old, then we could design the UX so that it feels compassionate and not jarring to the end user. for example, using a separate endpoint that doesn't just say "you're not logged in". We can recognize that it's coming from the email "submit" button and give a different login redirect that says something like:

> Ah shucks, {{ firstname }}. Unfortunately, the button from the email you clicked is a bit old, so we can't use it to log you in to your account. I see you clicked the email we sent to you to your inbox at **name@domain.com**. I've already sent you a new link. Please click that one and I'll have you submitting your idea in no time!

https://github.com/ezl/dailyidea.com/commit/3a196c110950a657949fa58708257b7a9af31d0f#r39182357

**Comment by ezl** [comment]
related question: https://github.com/ezl/dailyidea.com/issues/360

**Comment by vedmant** [comment]
@ezl @aldarund I think the simplest would be to share the same SECRET_TOKEN between mail-processing and users, so mail-processing can generate the same JWT tokens. Not sure however where SECRET_TOKEN comes in users app, looks like should be in dev.env file, but it's not there, does it just use default string "secret-tk1x"?

**Comment by aldarund** [comment]
for dev it use secret-tk1x since it doesnt matter . for prod its different in prod env file

**Comment by aldarund** [comment]
yes, secret token should be shared

**Comment by vedmant** [comment]
It will require the same SECRET_TOKEN env in users and mail-processing backends
