### ISSUE TITLE
What do we want to do after "idea created"?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#358]
UX - after create idea, do we want to go to a dedicated "success" page instead of just a toaster message?

Or a bigger modal that can be X'ed out?

If we did, this could potentially let us also encourage interactions that are good for growth like: "Do you want to share this with any of your friends?"

cc @alisonuxdesign

**Comment by Watson-B** [comment]
<img width="415" alt="ideaPost_confirm_modal" src="https://user-images.githubusercontent.com/65913664/88711075-769b0c80-d0cc-11ea-9d29-804860b6c19a.png">
@ezl Is this what you were thinking?

**Comment by alisonuxdesign** [comment]
Yeah love this! lets implement

**Comment by alisonuxdesign** [comment]
Assets for this idea here: 
[Idea Created Assets.zip](https://github.com/ezl/dailyidea.com/files/5008105/Idea.Created.Assets.zip)

**Comment by ezl** [comment]
agreed. gorgeous. love it, @Watson-B 

adding to dev pipeline for execution.

**Comment by vedmant** [comment]
@ezl "Turn on post activity emails" - we don't have this feature, should I add this switch with no actual function?

**Comment by ezl** [comment]
@Watson-B @alisonuxdesign what should "turn on post activity emails" control?

**Comment by alisonuxdesign** [comment]
I think the idea was to send a triggered email when the user's idea was getting some action. is this hard to set up? I'll whip up an email design today for this purpose if approved. @vedmant @ezl

**Comment by ezl** [comment]
@alisonuxdesign no need for design.

I propose that we don't implement this functionality here.

This basically seems then to be a *per idea* toggle for updates (idea saved, idea commented, idea liked).

Instead, I propose we treat this as a global setting, which we'll store in the Settings section - users can subscribe to updates on these actions (saved, commented, liked) on a global basis for ALL their ideas, rather than on an individual basis.

I feel little will be lost (at least early on) if users can't control this at a "per idea" level, and it significantly reduces dev and UX effort.

@alisonuxdesign if you strongly disagree and feel we should implement per idea level toggles, feel free to dissent and we can discuss.

@vedmant if @alisonuxdesign is ok with the global version, then for now we can just remove the toggle from that screen.

**Comment by vedmant** [comment]
@vedmant Setting per idea will require quite big amount of coding, but of course makes more sense. That will be out of this issue scope. So for now I just remove that toggle?

**Comment by alisonuxdesign** [comment]
@vedmant Remove the toggle. I'll attach a new design, it will take me 5 seconds

**Comment by alisonuxdesign** [comment]
<img width="415" alt="post_deleteConfirm_portrait" src="https://user-images.githubusercontent.com/63747360/89929308-b1be3500-dbce-11ea-92b9-5a8acf8c745d.png">


@vedmant

**Comment by vedmant** [comment]
@alisonuxdesign Ok, done.

**Comment by ezl** [comment]
This screen was implemented and merged, but seems to have been removed.

Let's bring this back. Also @Watson-B is going to add a button to this screen.

**Comment by vedmant** [comment]
@ezl Yes, it was removed during refactoring. It's easy to miss things like this during refactoring since we don't have automatic tests. 

I put it back on idea page, so after creating idea it redirects to that idea page and then shows a dialog.

One thing however, when creating private idea, it redirects to user profile page, and will not show created idea dialog. Should I also add this dialog on user profile page?

**Comment by vedmant** [comment]
I merged a fix, let me know about profile page.

**Comment by ezl** [comment]
I agree with your assessment, @ikosovec. Closing this issue as recommended. Thanks!
