### ISSUE TITLE
pretty slugs for ideas?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#369]

**Comment by vedmant** [comment]
Makes sense, we can create unique slug from the title, if slug already exists it should append -1, -2 etc. This is how I usually do slugs. The only downside is if title changes slug will change also and previous URL will be 404. For this I did something like /{post_id}/{slug} and made redirect is slug doesn't math, however since id's in DynamoDB are very long, it might require to create either posts counter and some additional short unique ID.

**Comment by ezl** [comment]
is there a way to create shorter slug ids? i realize that hash is probably the dynamodb hash, but we don't need to be able to support ids that are that long. even a 6 char alphanumeric id would be long enough 36^6 (not even using upper and lower) would be more than 2.176 trillion.

**Comment by vedmant** [comment]
This is question for @aldarund , I don't have much experience with DynamoDb. My idea is to generate random 6 char id and check for existence (re-generate if duplicate).

**Comment by vedmant** [comment]
- [ ] Generate shortId and check for uniquness
- [ ] Create slug from title
- [ ] Update slug on idea update
- [ ] Pull idea by shortId and 301 redirect if slug doesn't match
- [ ] Fix places that require ideaId from the route param

**Comment by vedmant** [comment]
Hi @aldarund can you confirm / suggest different way of doing this task?

**Comment by aldarund** [comment]
back/appsync/functions/create_idea/create_idea.py:32
idea_id = str(uuid.uuid4())

thats basically creating of id. nothing related to dynamodb. So can be anything here

**Comment by vedmant** [comment]
@aldarund yeah, makes sense, but in this case I'll need to update all the idea references that already exists, like comments / likes / saves / so on... So I just added separate shortId key for now.

**Comment by aldarund** [comment]
yes, short id is a fine way just need to apply to existing ideas too and than should be fine

**Comment by vedmant** [comment]
@aldarund Yes, it's in the subtasks list, btw I didn't find the proper way to create one time run commands with appsync. Should it be just a lambda function without api endpoint?

**Comment by vedmant** [comment]
@aldarund Another question, what is the difference between `getMyIdea` and `getUsersIdea`, this prevents requesting idea just by shortId as it check if idea belongs to user by passed user id in the url param. I don't see any specific private data that `getMyIdea` returns. For now I'll probably replace both by just `getIdea`.
