### ISSUE TITLE
don't overwrite global preview image on individual idea pages

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#370]
the main site one is better than the individual idea page one

**Comment by vedmant** [comment]
@ezl Not sure I understand which images is this about? Is this about meta images like og:image ? 
In this case I see some issue, on front page it adds `property="og:image" content="https://undefined.s3.amazonaws.com/og-default-image.png"` which is not loading subdomain is undefined. On idea page I see `property="og:image" content="/_nuxt/assets/images/bulb_with_light_holder.png"`.

So if I understand it correctly I should fix https://undefined.s3.amazonaws.com/og-default-image.png link and also set it to individual idea page?

**Comment by ezl** [comment]
for idea page:
- if an image is uploaded in the actual idea, use that image.
- if no image is uploaded there, use og-default-image.png

for all other site pages: no change
