### ISSUE TITLE
Let users see how many times an idea has been viewed (future)

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#377]
Only for your own ideas.

UI side of https://github.com/ezl/dailyidea.com/issues/274

**Comment by Watson-B** [comment]
Here are mocks of what this might look like on 'My Ideas' and in the general 'All Ideas' deck. Would the user be able to see a list of who has viewed the idea? If so, I would change the color of both the icon and the text to purple.
![idea count (my ideas)](https://user-images.githubusercontent.com/65913664/113438879-57145c00-939e-11eb-9b82-4017bd4a4048.png)
![idea count (stack)](https://user-images.githubusercontent.com/65913664/113438881-57acf280-939e-11eb-8e01-62dfe50e7ff5.png)

**Comment by ikosovec** [comment]
@Watson-B @ezl can we move this to the dev kanban and move up the priority list?

**Comment by ezl** [comment]
yep -- @ikosovec please chat with @vedmant first about feasiblity. If this can be done without any backend changes, lets do it. I believe we are already storing this data.

**Comment by vedmant** [comment]
@ezl Yes, we already track views, but just a total count, also I see some errors there. So it will be a some backend work, but not a lot. Also I see it's not tracking views on explorer swipes, so I'll need to fix this.

**Comment by ikosovec** [comment]
I guess we can move it forward then if it's only a small bit of backend adjustments.

**Comment by vedmant** [comment]
@Watson-B Could you send me link in Figma for this images, I can't find them

**Comment by Watson-B** [comment]
@vedmant here[https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea-Primary?node-id=396%3A20](url). I am also tagging you in a comment on the screens

**Comment by ikosovec** [comment]
Can I get more info about how this feature works please?
Like, what is the criteria of the counter going up?

@Watson-B are all users supposed to see the counter? Or just the user who created the idea?

**Comment by vedmant** [comment]
Currently it just increments every time idea is viewed without any criteria. So if you swipe back and forth it will increment both ideas views. If we need some more complex criteria for this, it will make sense to add it after rewrite, as it's most likely will be a backend work (if to count unique views using ip or cookies).

**Comment by ikosovec** [comment]
I think this is good for now so I'm closing it. I will be opening a new ticket and putting it in Maybe to discuss whether we need any different criteria on the views in the future (#974 ). Thanks for the explanation. :)

**Comment by Watson-B** [comment]
@ikosovec Just the user who created the idea

**Comment by ikosovec** [comment]
@Watson-B then we need to adjust this as well. I'm opening a new ticket: #976 

I also agree that this is the best solution - to show the counter only to the poster of the idea.
