### ISSUE TITLE
Choose a better preview image for sharing an individual idea

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#393]
We can explicitly set the "Preview image" that is displayed when someone posts a link on facebook or how it renders in slack/sms.

To test this, send yourself (or anyone) a FB message or text message or slack message of:

1. https://www.dailyidea.com/ (the main site)
2. https://www.dailyidea.com/ideas/1014b60d-e0ef-4490-80b0-b9f26bf79acf/a17add01-9067-4c55-948e-67e4b438b014 (a single idea)

Let's choose a better default image for a single idea.

(If a user INCLUDES an image, we should use their image, e.g. https://www.dailyidea.com/ideas/a020888a-72c8-4773-a0a7-484f7ed9d7fa/a09cfdb9-d761-4eef-8eb8-9e1d57f29730)

**Comment by alisonuxdesign** [comment]
@ezl can we wait on this? @Watson-B and I had talked about making some personalized illustrations for the brand. he's a wizard at sort of thing and I think we want to get the structure of the site done before moving on to the intricate UI if your okay with that

**Comment by alisonuxdesign** [comment]
@ezl & @Watson-B I think this might be a really fun opportunity to have a custom illustration. I know we had chatted about it and decided against doing it for every single illustration on the site but this one might be a nice touch

**Comment by ezl** [comment]
i'm on board with custom illustration here

**Comment by Watson-B** [comment]
![Frame 2](https://user-images.githubusercontent.com/65913664/89222461-f2440000-d589-11ea-881a-4ca0eb45c505.png)
@alisonuxdesign and I did some brainstorming this morning. This is just a quick mock and would need some polish, but what about something like this @ezl ?

As I was exploring this idea this morning, I had an idea about reusing the bulb if we go this direction.
<img width="415" alt="logIn_enteredName_portrait" src="https://user-images.githubusercontent.com/65913664/89222595-28817f80-d58a-11ea-82e2-ff887bb22f1a.png">
<img width="415" alt="confirmationEmail_portrait" src="https://user-images.githubusercontent.com/65913664/89222599-2ae3d980-d58a-11ea-8a04-3e81d657459c.png">

Some other exploration had me thinking about another path we could take before users upload a profile photo
<img width="415" alt="preGroupingIdeas_portrait" src="https://user-images.githubusercontent.com/65913664/89222659-47801180-d58a-11ea-98f8-f15003a6f3cd.png">
<img width="415" alt="share_portrait_1" src="https://user-images.githubusercontent.com/65913664/89222668-4bac2f00-d58a-11ea-914b-ca3db427e3d2.png">
<img width="415" alt="comments_portrait" src="https://user-images.githubusercontent.com/65913664/89222672-4e0e8900-d58a-11ea-8259-34be0ade5052.png">

**Comment by Watson-B** [comment]
![solid](https://user-images.githubusercontent.com/65913664/89359175-049d6700-d67a-11ea-87bc-24a112af8a90.png)
![gradient](https://user-images.githubusercontent.com/65913664/89359178-0535fd80-d67a-11ea-9c2a-5b8d21426a7f.png)
![no_blush](https://user-images.githubusercontent.com/65913664/89359179-0535fd80-d67a-11ea-95c2-5177dbca6b18.png)
@alisonuxdesign this is all you needed, right?

**Comment by alisonuxdesign** [comment]
@Watson-B Yeah lets go with this last one! I'm going to go-ahead and delete our trail to make it easier to implement for Dev
