### ISSUE TITLE
one click to search inbox for magic link emails for users

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#396]
If the user has a gmail inbox, we can use a specific link so if the user clicks it, it searches their gmail inbox for our message.

Implement something like this:
https://monosnap.com/file/7XlGXP9xCpowpS1bxiuKDc6p6cjq7a

for cases where the user's email is "@gmail.com"

This is an example link where it searches for the specified string in the subject. Adapt it for our message.

`https://mail.google.com/mail/u/0/#search/in%3Aanywhere+subject%3A%22Please+confirm+your+email+address%22`

edit:
Now that you're implementing a different login flow for mobile devices vs desktop -- only show this on desktop devices

**Comment by vedmant** [comment]
I made edits, but waiting on https://github.com/ezl/dailyidea.com/pull/484 to use that to detect mobile.
