### ISSUE TITLE
is it possible to make it so that daily idea doesn’t open in the email client when you view from your phone?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#397]
right now if you click a one click login link from gmail on a browser, it opens in the email client's browser.

Email client browsers suck.

Is it possible to force it to the device default browser?

**Comment by vedmant** [comment]
@ezl I don't think there is a way to do this in email. There is a setting in gmail client where to open links.

**Comment by ezl** [comment]
ok thanks, @vedmant 
note for @alisonuxdesign - this may not be possible

**Comment by ezl** [comment]
@vedmant - I'm moving this ticket out of your pipeline and back into "ideas" since it's not clear if this can actually be executed.

I have noticed that there's an option to specifcy a specific APP though, for example, forcing something to open specifically in Chrome. But this may only work if we know for sure that the user has chrome installed on their device.
