### ISSUE TITLE
gracefully handle expired auth links

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#399]
we'll be sending users lots of auth links via the daily idea reminders

https://github.com/ezl/dailyidea.com/issues/357

However, we can't let those links stay valid forever, so we have to expire them. But even after they expire, they'll live in the user's email. We aren't explicitly handling HOW we want this to fail once the links expire, but we should do so in a way that is graceful and a good user experience.

**Comment by ezl** [comment]
moving this to "design required" because i think we need to actually document what happens in these cases before we can talk about a solution. this will be for @alisonuxdesign and eric to figure out.

**Comment by alisonuxdesign** [comment]
@ezl  thinking something like this: 

![Get new Code](https://user-images.githubusercontent.com/63747360/88597095-bb1e9d80-d023-11ea-8375-88c5ad581e28.png)

Let's have it expire 

1) after a few (thinking 2-4)  hours of being requested 
2) If another link or code is sent to the same email

**Comment by ezl** [comment]
(A) please include screens for both expired code and for expired link (mobile v desktop)
(B) no need to take action by user -- ASSUME they want the code, let them know we already sent it to them and they should just check their inbox: "oops your ___ expired, we sent you a new one to alison@site.com -- go check it."

cc @alisonuxdesign

**Comment by alisonuxdesign** [comment]
### **Mobile**

**For expired Code**
![Code expired_mobile](https://user-images.githubusercontent.com/63747360/89056391-2bc20480-d319-11ea-82d1-5a3f3a34e8bb.png)

**For expired Link**
![Link expired_mobile](https://user-images.githubusercontent.com/63747360/89056431-3bd9e400-d319-11ea-8a8a-c3e88a17cc7d.png)


### **Desktop**

**For expired Code**
![Code expired_desktop](https://user-images.githubusercontent.com/63747360/89056498-5318d180-d319-11ea-8e2c-747d3884cb4a.png)

**For expired Link**
![Link expired_desktop](https://user-images.githubusercontent.com/63747360/89056523-5e6bfd00-d319-11ea-8b03-f06884c80f7f.png)

**Comment by alisonuxdesign** [comment]
![Bird Illustration](https://user-images.githubusercontent.com/63747360/89058459-90cb2980-d31c-11ea-8862-e336d5b5ec95.png)

**Comment by ezl** [comment]
teehee. ❤️ the chosen image.

**Comment by vedmant** [comment]
@ezl This one depends on new swiper implemented first according to design. For now I can make it re-send emails and redirect to confirm or success page without changing design. I can add "expired" query variable to render different text.

**Comment by ezl** [comment]
if this has another dependency, just wait for that one to be merged first then. if you think you can make progress before that, go for it.

**Comment by vedmant** [comment]
@ezl Ok, I'll wait for front page otherwise it will be code duplicate and double work. There is a question then about left / right arrows on the last images, where they should navigate?

**Comment by ezl** [comment]
@alisonuxdesign where do the left/right arrows on the image with the empty bird cage navigate to?

**Comment by alisonuxdesign** [comment]
hey @vedmant it doesn't go anywhere. those arrows were a mistakenly added when I copied this screen over.

**Comment by ezl** [comment]
@vedmant front page swiper is implemented and merged now, so i believe this is now unblocked. if that's not correct please lmk.

**Comment by vedmant** [comment]
@alisonuxdesign Could you send me svg image of the bird and cage?

**Comment by alisonuxdesign** [comment]
[Bird Illustration.svg.zip](https://github.com/ezl/dailyidea.com/files/5210361/Bird.Illustration.svg.zip)
@vedmant
