### ISSUE TITLE
create a way to schedule/send "best ideas" digests

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#409]
This should be a page with a form that has:

* 6 input fields for idea urls
* 1 input field for an email address (required)

I can enter between 2 and 6 dailyidea urls. Do not accept 0 or 1 completed urls

On submit, confirm that they are valid dailyidea urls.

Send an email to the address in the email address input that contains:

for each idea:
 idea.title
 ideal.description
 idea.author

right now this can be totally unstyled.

currently developing the template for this, and we will design the template afterwards.

**Comment by vedmant** [comment]
@ezl How that page should be protected? As I understand we don't have user roles or separate admin users. This then will require first to add roles or admin users to the app.

**Comment by ezl** [comment]
2 options:

1. hacky temporary solution: don't protect the page, but require an arbitrary password input to be included, and if it's not correct, then do not process the send request. Super easy.

2. time to start thinking about build out a a dashboard / admin privileges for certain users.

Right now my main concern is just getting it quickly and I feel confident #1 is safe enough and easy to execute, even though a little hacky.

I don't care about the dashboard yet as I don't have other things I want to do with it, so I'm hesitant to invest in the effort to build a dashboard and permission for different class of users.

However, if you think this can be done quickly and effectively, I'd be open to considering it.

Overall, my hesitancy is also based on the fact that in the long term I don't believe that if we keep building Daily Idea we will choose to stay with Appsync, so I am timid about investing in building a lot around it.

My perspective is that at this point there are effectively 2 main possible directions:

1. This gets no meaningful traction -- if so, then I still want to polish it and add basic minimum feature sets, but then let it stay in appsync forever, but we'll reduce efforts toward it once it's in a good UX state and stable

2. It does get meaningful traction and we want to keep investing in it -- if so, I think we should consider rewriting to something where we can develop faster (probably django, but most importantly probably, local development and better debugging tools)

@aldarund can you also weigh in here? what are your thoughts?

tagging @f-prime and @alisonuxdesign just so y'all know where my head is at on this kind of thing.

**Comment by vedmant** [comment]
@ezl Ok, for now I'll add simple page with form protected by password. I'll add password to env variables.

**Comment by vedmant** [comment]
Ok, this is basically done, I'll create a PR request.

So there is a new page: http://localhost:3000/send-digest
with the form to select ideas and submit it for sending digest
the passcode is "saprobregu", it's hardcoded in dev.env

```
DIGEST_PASSCODE=saprobregu
```
