### ISSUE TITLE
Broken idea link on Saved Ideas page

### ISSUE THREAD

**Issue by f-prime** [ezl/dailyidea.com#431]
Getting redirected to `/i/undefined/undefined`

Original message in slack:
> I am experiencing an issue where I am getting redirected to /i/undefined/undefined on the Saved Ideas page. Seems to be related to the new slugs, but I want to make sure it's not something trivial. Otherwise I will make an issue.

**Comment by vedmant** [comment]
@f-prime @ezl Just tested on current branch, it works properly for me

**Comment by vedmant** [comment]
@f-prime If you still have it, can you describe steps to reproduce it
