### ISSUE TITLE
Create idea: upload image, delete from editor then Ctrl-Z causes error

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#452]

**Comment by vedmant** [comment]
@ezl There is a bit of a problem here with removing image and ctrl-z, when image is removed it's also removed from S3, then ctrl-z adds it back but actual image is deleted. I'm trying to cache File object to make it re-upload on Ctrl-Z, but there are a lot of issue with Trix as it's written on CoffeScript with all that Rails nonsense in place. It almost works but shows broken previous after Ctrl-Z and not showing uploading progress after Ctrl-Z, I'll try to fix this, but probably should not spend too much time, it's just a broken preview while uploading after Crtl-Z which is rare case.

**Comment by vedmant** [comment]
@ezl Generally trix editor might be not the best option, I usually use tiptap editor, it much more developer friendly and Vue based https://github.com/scrumpy/tiptap maybe we can consider using it, there is Vuetify tiptap package also https://github.com/iliyaZelenko/tiptap-vuetify it will allow to write all the components inside the rich editor in Vue.

**Comment by ezl** [comment]
closing, won't fix. in the future we will implement tip tap
