### ISSUE TITLE
Create idea: dragndrop issue, when image dropped on top of uploaded image, it opens image in the browser

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#454]

**Comment by vedmant** [comment]
@ezl This one is also internal issue with Trix, I'll need to search for workarounds to fix it, let me know if you can consider switching to tiptap, in this case there is no need to work on this.

**Comment by ezl** [comment]
closing -- won't fix. we won't fix this. in the future we will implement tiptap.
