### ISSUE TITLE
Implement intermediate "card" swiping UX

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#457]
This is intended as a bridge between our current UX and the new one.

The objective is to make our current swipe pattern more obvious and apparent, but with minimal dev reworking.

This will act as a bridge for us so we have a "pretty good" pattern on the live site while we start to work on the new version.

edited now that
https://github.com/ezl/dailyidea.com/issues/458 and https://github.com/ezl/dailyidea.com/issues/461
are in progress.

the individual card "view" basically contains the front/back swipe pattern and the "card" idea is already live.

i think now what we should do is:
1. immediately always drop people into the `ideaDetail` view (skip the `ideaList`)
2. maybe: allow people to kick OUT to the `ideaList` view. (note this is more like instagram -- immediately in a "single item at a time" view, but you can, with effort, arrive at a grid view that shows more at a time)
3. maybe: put an overlay on the first card that reminds users that they can do a left right swipe (@alisonuxdesign already designed this screen)
4. maybe: create 2 different ideaDetail "modes" (even though the ideaDetail page already contains too much IMO w/ view/edit modes, but that's a problem for when we refactor and build the new UX) these 2 "modes" are "cardview" and "fullscreenview". "cardview" is a fixed height and overflow-y:hidden. tapping the screen toggles to "fullscreenview" which is the current main view and allows up down scroll.

**Comment by alisonuxdesign** [comment]
Here is an image of the first tutorial the user will see as an overlay. 
![tutorials](https://user-images.githubusercontent.com/63747360/86620104-fecc3d00-bf78-11ea-8dab-2840815cb8fa.png)

Here is an alternative example of a toast that the user will see for the first (lets say 3) slides to know they can swipe. 
![tutorials toast](https://user-images.githubusercontent.com/63747360/86620109-01c72d80-bf79-11ea-9116-4c61c38ac86c.png)

Here is the uploaded PNG of the icon: 
![Swipe icon](https://user-images.githubusercontent.com/63747360/86620254-405ce800-bf79-11ea-8019-e08422f80553.png)

**Comment by f-prime** [comment]
1 - Should users be dropped in to an idea immediately after login? When the come to the website? When specifically? 

3 - Of the overlays that Alison has put above, which one do you suggest we use for the intermediate card version? The toast, the initial swipeable instruction card, or both? 

4 - Where would they set the mode and when it is set is it universal or just for the card being viewed?

**Comment by ezl** [comment]
@alisonuxdesign lets revisit this. 

i had created the ticket first as a bit of a placeholder, and some of this has already been implemented.

let's clarify the next steps we want to take on this.

i personally think it would be good to get the image that @alisonuxdesign attached in there somewhere, but i'm not sure where / when it gets displayed.

**Comment by alisonuxdesign** [comment]
@ezl lets touch base on this today!

**Comment by ezl** [comment]
@alisonuxdesign @f-prime -- closing this ticket in exchange for 2 separate tickets:

https://github.com/ezl/dailyidea.com/issues/479
https://github.com/ezl/dailyidea.com/issues/481
