### ISSUE TITLE
swipe interaction enhancements

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#458]
1. on card swipes, if the next/previous action is NOT triggered when the card is released, animate the card snapping back to center.

2. on card swipes, if the next/previous action IS triggered, animate the card sliding all the way off the screen.
micro improvements on swipe pattern for cards and for onboarding flows - actually show the swipe transition, visible card

edit:

Now that I've actually looked at this, I have some new thoughts on this.

Macro: I still think animation would be nice. I think for the user, it's a bit jarring that both the "swipe not activated" and "swipe activated" outcomes of "fingerUp" look identical (i.e. the card snaps to the center, and either there is new content or there is not new content).

Thoughts on method:
The rotation uses CSS transforms.
Can we just animate the transforms? I tried messing with this a little bit, but there are some problems.

I think ideally what you want to do is:
1. no animation while finger down
2. on fingerup, if swipe-right: setRotation(90), setX(+screen.width). opposite for swipe-left. else setRotation(0), setX(screenCenter). this is MOSTLY the behavior we have, except that it swipes the card off on minDistanceForSwipeAchieved. The UI will LOOK the same as current if we just implement this though, because no transitions.
3. on fingerUp, `transition-property: transform` + `transitionDuration:200ms` or something. this will make the card animate to its endpoint.

the problem with this though is then after a swipeleft or swiperight moves the card off the screen, it'll ANIMATE back.

what i realized yesterday while working with this that is problematic about what we are doing is:

1. tinder/bumble use swipe left and swipe right as NEXT. so it's ALWAYS pulling the "next" card off a stack, but it's just adding a different value to each one (like/dislike). this makes it so they ALWAYS know what the next card that will show up is going to be.
2. WE are using it for POSITION in a stack of cards. that means if you start swiping, we actually don't know if the card udner the stack is the one BEFORE or the one AFTER in the card stack. we won't know which card to display on swipe "off" until the swipe action is completed -- therefore we CAN'T have a card displayed underneath.

this is problematic for the UX. in essence, we're using a swipe pattern by tinder/bumble in the wrong way because they only have UNIDIRECTIONAL card stack traversal, but ours is bidrectional.

a more "appropriate" swipe pattern is actually like a kindle book, or a gallery swipe, where left/right preserve "forward"/"back" in a stack, so as the primary card slides a little left or right, we can actually start dragging the next/previous one on to the screen.

A way i toyed with for "hacking" this is:

1. put a placeholder card with greyed out text underneath the current card. this stays static.
2. when a swipe off is achieved, slide the `Swiper` off screen.
3. set opacity to zero
4. snap it to center
5. animate opacity back to 1

this makes it look like a "next" card is being displayed (of course, it's just snapping the original card back to center).

i struggled a little with timing the css transitions.

**Comment by f-prime** [comment]
If I understand the new proposed swiping pattern it's that after a swipe left or right the new idea will show up in the middle and fade in to view. If so it seems to suffer from the same problem of not knowing if the new card is the previous or the next idea. It makes the transition smoother but the new idea card would seem to pop up out of nowhere. I think we need a visual indication that the card is either coming from the left (previous) or the right (next).

This is what I had in mind.

1. detect swipe left/right 
2. move card off screen on opposite side of screen
3. Animate moving card back to the center from the opposite direction with the new content

**Comment by ezl** [comment]
yep, i love this. your version is better. lets do it.
