### ISSUE TITLE
getIdeas API not returning number of comments, Pagination integration is pending

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#46]
All get apis should return following fields according to design:

1. Idea title
2. Idea content
3. createdDate
4. Likes Count
5. Comments

Many of the APIs are not returning the the fields required.

**Comment by aldarund** [comment]
All ideas api return same idea field. If something is missing from one of it just add it to client query.
If something is not working after it - write exactly what api and what field

**Comment by patelravi** [comment]
Okay, I've made the changes, its working now.
