### ISSUE TITLE
fix magic link "submit your idea" button in daily reminder email

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#465]
https://monosnap.com/file/7nTV9RlMZjuFYcoAxoyoEZcBfN81qW

is leading to this:

https://monosnap.com/file/dgive5VjrxL2hhQjImFgLIZBlMxGeN

**Comment by vedmant** [comment]
@ezl It works on beta. Probably when it was deployed to production the "SECRET_TOKEN" env variable was not added to mail-processing. It should be the same as in users app. I'll check if I have access to prod setup, maybe I'll add it myself.

**Comment by vedmant** [comment]
@ezl Looks like it have to be added to prod.env file? @aldarund could you check this as you deploy production app.

**Comment by vedmant** [comment]
As a quick fix I set SECRET_TOKEN for the dailyidea-mail-processing-prod-requestIdeasMail function here https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/dailyidea-mail-processing-prod-requestIdeasMail?tab=configuration
