### ISSUE TITLE
create alternate login method: via code

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#467]
For the purposes of this ticket, this new login method ONLY applies to 1 case:

when users explicitly login by clicking the "login" button and enter their email address.

we won't worry about this (yet) for signup or other paths that authenticate the user.

We will be implementing a "prove your identity with a short, expiring code" similar to telegram, twitter, bitmoji

When we send the user an auth link (we will, for this ticket STILL send the original link), ALSO send them a short code. (for now, do a 4 digit numeric code)

this should expire after a fixed time (N minutes, let N be 15 for now).

This 4 digit code gets included in the login email.

On login attempt, on the same screen where we say "check your email", we ALSO now add a form field that says "enter the 4 digit code in your email".

- [x] Task #1 Send a 4 digit expiring code
- [x] Update "email sent" confirmation page to include a form that accepts the code
- [x] on correct code (code is correct and has not expired) authenticate user
- [x] on incorrect code due to expired -- say "sorry this code has expired. We sent you another one to the same email address." Automatically generate the next code and send it to the user. then show the code form again.
- [x] on incorrect code due to invalid -- say "sorry this code is invalid. please try logging in again." (show button to log in.
- [x] update email to include a 4 digit code. Just add below the confirmation button. "Log in by entering the following numeric code. This code is valid for 15 minutes from the time it is was sent."

**Comment by vedmant** [comment]
@ezl Ok, as the simplest solution I'll just add two fields to users table `loginCode` and `loginCodeDate` and create another function to check authentication by code.

**Comment by vedmant** [comment]
- [ ] Create separate email template for mobile login
