### ISSUE TITLE
lightbox for single card view

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#479]
transition to lightbox view for single card.

**current behavior:**

ideaDetail view displays a single card that can scroll up and down (default OS behavior) AND touch motions register x-axis drags to swipe left/right.

**new behavior: ideaDetail view has 2 modes**

1. default mode (swiping mode) displays a single card that (A) is fixed height (take up available screen space) and can NOT scroll up/down (y-overflow:hidden, css opacity gradient at bottom). (B) in this mode, x-axis drag does swipe left/right, but y axis does not.

2. alternate mode (reading mode) displays lightbox or full screen that (A) is NOT fixed height, can scroll up and down, like the current detail view, and shows full card height. (B) in this mode, x-axis drag does nothing -- we aren't treating this as a draggable, so it's just a full screen/lightbox view where touch interactions execute OS default behavior.

tapping the screen in either mode toggles to the other mode.

(this is similar to some dating apps with swipe patterns)

**Comment by alisonuxdesign** [comment]
hey @ezl  quick question: I am assuming this is for Mobile only. Is that a correct assumption?

**Comment by ezl** [comment]
correct, @alisonuxdesign

**Comment by alisonuxdesign** [comment]
### 1. Default Mode/ Card looks like this: 

![longIdea_noScroll_portrait](https://user-images.githubusercontent.com/63747360/87595410-bc5adc80-c6ab-11ea-9ad3-ee526bc88d61.png)

```
position: absolute;
width: 343px;
height: 460px;
left: 16px;
top: 168px;
```

![shortIdea_img_landscape](https://user-images.githubusercontent.com/63747360/87595421-bf55cd00-c6ab-11ea-9f09-ca2fd9a5fefd.png)

```
position: absolute;
width: 642px;
height: 227px;
left: 85px;
top: 64px;
```

### 2. Alternative Mode/ Lightbox looks like this: 

![lightboxPost_portrait](https://user-images.githubusercontent.com/63747360/87595697-2ecbbc80-c6ac-11ea-94d4-42c1d6db7b3b.png)

```
position: absolute;
width: 343px;
left: 16px;
top: 108px;
```

![lightboxPost_landscape](https://user-images.githubusercontent.com/63747360/87595704-33907080-c6ac-11ea-93a7-9858dfe0a3c3.png)

```
position: absolute;
width: 642px;
left: 85px;
top: 16px;
```


Let me know if you would like additional assets like icons and in what format (SVG, PNG?)

**Comment by f-prime** [comment]
@alisonuxdesign Could you share the heart, comment, save, and share icons? As an SVG would be fine, or just point me to where you got them from. Also, more important than the width and position of the designs are the colors and fonts used. I have referred to #482 to get this info but I think it's be better to include that info in these issues instead of px width and positions.

**Comment by alisonuxdesign** [comment]
@f-prime SVG sent through Slack the following information you are looking for is: 

```
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: rgba(91, 65, 187, 0.6);
```

**Comment by alisonuxdesign** [comment]
@f-prime here is the desktop card design 

![Desktop card add to git](https://user-images.githubusercontent.com/63747360/87995505-ebf35580-caac-11ea-906a-66fd7c6ccab3.png)

```
Desktop Card
Box/card: 
/* Background card */
position: absolute;
left: 6.57%;
right: 5.81%;
top: 0%;
bottom: 0%;
background: #FFFFFF;
box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.1);
border-radius: 10px;x;

Bottom Fade

background: linear-gradient(360deg, #FFFFFF 0%, rgba(251, 251, 253, 0) 170.69%);


Text 

Title:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 32px;
line-height: 38px;
color: #151125;

Comment Title (secondary title)
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 20px;
line-height: 24px;
color: rgba(0, 0, 0, 0.6);


User Name/ “Post”:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #5B41BB;

Time stamp
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: rgba(21, 17, 37, 0.6);

Body Text
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #151125;

Join the Conversation: 
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: rgba(21, 17, 37, 0.6)
```;
