### ISSUE TITLE
show swipe explainer card on first time browsing

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#481]
key objective: try to ensure that everyone who views an ideaDetail card realizes that they can swipe to view more ideas.

task: the first time a user sees an ideaDetail card, first show them the swipe explainer card.

potential implementation - set a cookie for "hasSeenExplainer" on the client. No need to store on the backend. if it doesn't exist when a user goes to view an ideaDetail, then show the explainer. otherwise don't.

downside - if a known user changes devices or resets cookies, they'll see the explainer again (I'm willing to accept this for now).

thought -- we can have a parallel desktop explainer as well ("press left/right on your keyboard to see other ideas") -- having a parallel implementation for non-swipe devices is nice (and easier-ish to make sense of the logic).

collaboration -- @vedmant has another ticket where he has to consider the question of how to assess whether the user is on a mobile device or not, and we discussed whether we should use user-agent or device viewport size. I recommended viewport size -- though now in retrospect, i think we may already have logic in the swipeable stuff that we can use for this. overall since we're doing this in several places, let's just try to keep it DRY. placeholder ticket for making sure that logic is reusable: https://github.com/ezl/dailyidea.com/issues/480

**Comment by alisonuxdesign** [comment]
Wanted to go ahead and put these images here to provide some visual direction. 

This card will always appear the first time a user goes to the current "all ideas" section.
-If the user goes straight to all ideas from onboarding this will appear OR if they go to create an idea and then goes to explore all ideas this will still be the first card they see when seeing all ideas.
- It will also appear if a logged out user is exploring ideas. It will be the second card they see (directly after the card they clicked on in the landing page). In this instance, a toast will appear letting them know they can swipe. 

Welcome cards:

![welcome Desktop](https://user-images.githubusercontent.com/63747360/87580985-7f83eb00-c695-11ea-92fd-00e733cafb8d.png)

![Welcome Card](https://user-images.githubusercontent.com/63747360/87580614-01bfdf80-c695-11ea-8281-6518da9d7dec.png)

Following that first welcome card, we would like to introduce a banner on mobile and toast on desktop that lets the users know that they can swipe (just to reiterate the swiping function). This will fade away after the user has swiped through 2 actual ideas (not including the intro card). 

Banner/Toast: 

<img width="375" alt="swipe_toast" src="https://user-images.githubusercontent.com/63747360/87582194-4e0c1f00-c697-11ea-8cb5-f89478e850c4.png">

![Desktop toast](https://user-images.githubusercontent.com/63747360/87583925-ed321600-c699-11ea-9344-a5a85528f681.png)

@ezl Let me know if this is the correct place for this. And if not where to move them!

**Comment by f-prime** [comment]
@alisonuxdesign Can you share the assets for the explainer cards here? Either that, or link to where I can find them. Thanks!

**Comment by ezl** [comment]
meta: between designers, devs, pms, we should establish a practice for where all assets are stored and what should be attached to each card.

even if all assets are available in a centrally stored place, i do feel it's a good idea to make sure it's also available on the card.  not the superset of all images, JUST the images that are required for implementation of the ticket -- so it reduces interpretation or cognitive load for choosing by the developer implementing the ticket.

**Comment by alisonuxdesign** [comment]
Here is Specs for the Card. SVG through slack @f-prime 

### Portrait: 

![Welcome Card](https://user-images.githubusercontent.com/63747360/87580614-01bfdf80-c695-11ea-8281-6518da9d7dec.png)

```
Large Card Portrait:
Box: 
width: 343px;
height: 460px;
background: #FFFFFF;
box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.1);
border-radius: 10px;
padding: 30px 16px 16px 16px;

Text 

Title:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 24px;
line-height: 29px;
color: #151125;

User Name:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: #5B41BB;

Time stamp
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: rgba(21, 17, 37, 0.6);

Body Text
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #000000;

Gradient fade at bottom:
width: 311px;
height: 32px;
left: 772px;
top: 8523px;
background: linear-gradient(0deg, #FFFFFF 0%, rgba(255, 255, 255, 0) 134.37%);
```
### Landscape:

![Group 277](https://user-images.githubusercontent.com/63747360/87956675-8da68280-ca6c-11ea-95d6-f716de1df945.png)
![Group 392](https://user-images.githubusercontent.com/63747360/87956681-8e3f1900-ca6c-11ea-8f3e-ef4858a66f7e.png)
```

Large Card Landscape:
Box/card: 
width: 642px;
height: 227px;
background: #FFFFFF;
box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.1);
border-radius: 10px;
padding: 30px 16px 16px 16px;

Text 

Title:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #151125;

User Name:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: #5B41BB;

Time stamp
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: rgba(21, 17, 37, 0.6);

Body Text
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #000000;

Gradient fade at bottom:
width: 642px;
height: 23px;
background: linear-gradient(360deg, #FFFFFF 0%, rgba(251, 251, 253, 0) 96.01%);
```

### Desktop: 

![Desktop Card](https://user-images.githubusercontent.com/63747360/87957866-107c0d00-ca6e-11ea-8604-76c010c603df.png)

```
Desktop Card
Box/card: 
/* Background card */
position: absolute;
left: 6.57%;
right: 5.81%;
top: 0%;
bottom: 0%;
background: #FFFFFF;
box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.1);
border-radius: 10px;x;

Text 

Title:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 32px;
line-height: 38px;
color: #151125;

User Name/ “Post”:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #5B41BB;

Time stamp
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: rgba(21, 17, 37, 0.6);

Body Text
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #151125;

Join the Conversation: 
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: rgba(21, 17, 37, 0.6);

```

**Comment by ezl** [comment]
#481 is a welcome explainer for the first time a user starts browsing ideas. the first time a user, authenticated or not goes to the browsing experience (dailyidea.com/ideas/all), this explainer card is displayed on the top of the stack.

**Comment by vedmant** [comment]
@ezl @alisonuxdesign What about comments section of the card, this will require some hardcoded idea, that first will not appear somewhere else, and secondly should have hardcoded id on every server (I can do this with migration). But generally, allowing comments in explainer card makes this task much more complex. It will be much simper if that card doesn't have comments.

**Comment by ezl** [comment]
I'm ok with doing this card with no comments. @alisonuxdesign let us know if you think the comments are necessary for the explainer card

**Comment by ezl** [comment]
@alisonuxdesign - i chatted with @vedmant and said he can proceed without the comments for now, since he's blocked and unable to work. if we need to add comments, we can do that on a later ticket.

**Comment by vedmant** [comment]
@ezl @alisonuxdesign I tried to copy and paste in figma to get svg image:
<img width="739" alt="Screenshot at Sep 18 11-54-02" src="https://user-images.githubusercontent.com/5052406/93578161-a87e7000-f9a5-11ea-858c-8d192c787f98.png">
but looks like it's not allowing to copy, I only have my previous clipboard.

Can you please export for me this SVG

**Comment by vedmant** [comment]
@ezl @alisonuxdesign Also since I'm not creating idea for this, then there will not be author and buttons bar. Only title and content. This will not look like in the design at all, basically something like this:
<img width="1423" alt="Screenshot at Sep 18 12-01-37" src="https://user-images.githubusercontent.com/5052406/93579083-b97bb100-f9a6-11ea-83b9-237c5f719231.png">

**Comment by ezl** [comment]
@vedmant Can we put arbitrary HTML there? So in theory, could we add elements, images, or sections to that card, if we wanted?

**Comment by vedmant** [comment]
@ezl Not sure what do you mean, it's just hardcoded HTML code. Do you mean you want to add some html to database so it will be rendered here? In this case I'll need to go with different solution I explained before, that will be quite some more work on backend.

**Comment by ezl** [comment]
@vedmant I don't understand the constraints.

I think it's fine to not have:
* author
* comments
* action buttons like Like / Share

However, I think we'd like to have more control over what this card visually looks like than just header and p tags.

Are you saying that in order for this card to have an image added to it, we would have to do something with the database? If so, why?

**Comment by vedmant** [comment]
@ezl No, it can have any HTML, images, etc... I mean is that it's hardcoded in JS, and is not in database.

**Comment by ezl** [comment]
Ah cool. That's what I was hoping.

In that case, for now, you can submit a PR with it exactly as the screenshot you showed.

At a future time, we'll create a separate ticket for changing the appearance of this card, which will be done with HTML in JS on the client.

**Comment by ezl** [comment]
this ticket was closed and something was merged for this, but it doesn't seem to be working on the main site.

**Comment by ezl** [comment]
Reclosing. I see this WAS implemented and it is deployed. I misunderstood how to see it.
