### ISSUE TITLE
implement button UI styles per new style guide

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#482]
@alisonuxdesign can you extract just the button styles and put them in this ticket separately?

for all the CSS, can you paste it in here as text (you can use the <> code button above) -- this will make it easier for whoever is implementing to focus on just the specific part -- otherwise this is quite big and also harder to review.

pasting the text is easier for the implementer as well because then he/she can copy/paste it instead of looking at the image of text and transcribing.

**Comment by alisonuxdesign** [comment]
@ezl yeah adding it to my list to do today.

**Comment by alisonuxdesign** [comment]
### Default Button: 

![default button (1)](https://user-images.githubusercontent.com/63747360/87587778-c840a180-c69f-11ea-9383-3ba12b8dd646.png)

Css:
```
Default Button
background-color: rgba(91, 65, 187, 1);
width: 131px;
height: 36px;
border-radius: 6px;
padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```

### On Hover: 

![On Hover button](https://user-images.githubusercontent.com/63747360/87588067-47ce7080-c6a0-11ea-9cd7-8820c41403f0.png)

CSS: 
```
Hover Button
background-color: rgba(91, 65, 187, 1);
width: 131px;
height: 46px;
border-radius: 6px;

padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```

### Clicked: 

![Clicked](https://user-images.githubusercontent.com/63747360/87588289-9e3baf00-c6a0-11ea-851e-35ddf574dff3.png)

 ```
Clicked Button
background-color: rgba(66, 39, 169, 1);
width: 131px;
height: 46px;
border-radius: 6px;

padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```

### Disabled: 

![disabled button](https://user-images.githubusercontent.com/63747360/87588426-e1961d80-c6a0-11ea-89cc-07c62ac83cbc.png)

```
Disabled Button
background-color: rgba(91, 65, 187, .6);

width: 131px;

height: 36px;

border-radius: 6px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```
### Fixed-Width             

![fixedWidth_button](https://user-images.githubusercontent.com/63747360/87588799-7d278e00-c6a1-11ea-99f6-7ba2ca1d517b.png)


```
 Fixed-Width Button
background-color: rgba(91, 65, 187, 1);
width: 311px;
height: 36px;
border-radius: 6px;

padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```

**Comment by ezl** [comment]
@danleyb2 are you up for this?

**Comment by danleyb2** [comment]
@ezl Yes i am

**Comment by danleyb2** [comment]
@ezl @alisonuxdesign  Have implemented the CSS above and this is how it looks

![2020-08-06_07-36](https://user-images.githubusercontent.com/9919961/89491325-af676f80-d7b7-11ea-9928-7b68e03e745d.png)

A few issue

1. We are missing the font
2. Are the css to imlement only limited to the onces provided above for now or should i add more?
this is because the button in the disabled state still hovers, the width might be too small for large amounts of text

**Comment by danleyb2** [comment]
@alisonuxdesign what is the difference between **default** and **hover** ?, 
the colors in the css are similar but the images look different
