### ISSUE TITLE
Fix typo in email settings

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#486]
https://monosnap.com/file/Qi2t837nGrLIzfFDfhdSUAY4Vpu8I1

**Comment by ezl** [comment]
@danleyb2 as you take assigned tickets, can you please move them in https://github.com/ezl/dailyidea.com/projects/1 to "in progress" and "PR review" when appropriate?

Then when it is merged, whoever merges it will move it to "merged"

**Comment by danleyb2** [comment]
@ezl  have moved the card to "PR Review" 
@aldarund please move to merged.
