### ISSUE TITLE
implement new swipe pattern landing pages

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#487]
@alisonuxdesign can you add the screens for the new landing page that start with the swipe pattern immediately for the user?

please make sure to include both mobile and desktop screens please

**Comment by alisonuxdesign** [comment]
### MOBILE: 
![landing_valueProp_2_portrait](https://user-images.githubusercontent.com/63747360/88096692-4f848e00-cb54-11ea-9f8c-15ff04e6cc29.png)
![landing_valueProp_3_portrait](https://user-images.githubusercontent.com/63747360/88096693-501d2480-cb54-11ea-9a18-d704ffd7511e.png)
![long_or do you need to scroll to see_](https://user-images.githubusercontent.com/63747360/88096695-501d2480-cb54-11ea-9fc1-a3d1fa3371c2.png)

![landing_swiping_portrait](https://user-images.githubusercontent.com/63747360/88096674-4b587080-cb54-11ea-8e2c-9fdc79e63006.png)
![landing_valueProp_1_landscape](https://user-images.githubusercontent.com/63747360/88096679-4c899d80-cb54-11ea-8720-b2fe380ba03f.png)
![landing_valueProp_1_portrait](https://user-images.githubusercontent.com/63747360/88096680-4d223400-cb54-11ea-8dae-f55323fc42f8.png)
![landingURL](https://user-images.githubusercontent.com/63747360/88096684-4e536100-cb54-11ea-9b5d-080de63d78b5.png)
![swiping_landscape](https://user-images.githubusercontent.com/63747360/88096688-4eebf780-cb54-11ea-9c95-6f6c71a1646d.png)

### DESKTOP
![unauthorized_explore_desktop](https://user-images.githubusercontent.com/63747360/88096750-688d3f00-cb54-11ea-8ca2-ad6025ce3610.png)
![unauthorized_myIdeas_Post_desktop](https://user-images.githubusercontent.com/63747360/88096753-69be6c00-cb54-11ea-80a2-726d8c4075d1.png)
![landingPg3_desktop](https://user-images.githubusercontent.com/63747360/88096756-6a570280-cb54-11ea-9bd8-ce090ebfd9b6.png)
![landingPg2_desktop](https://user-images.githubusercontent.com/63747360/88096759-6aef9900-cb54-11ea-9734-5895a9bb4370.png)
![landingPg1_desktop](https://user-images.githubusercontent.com/63747360/88096760-6aef9900-cb54-11ea-914c-e557a0c7b5cf.png)

Attaching Assets as SVG's in a separate comment

**Comment by alisonuxdesign** [comment]
### Mobile: 
![landing_valueProp_1_portrait](https://user-images.githubusercontent.com/63747360/88097411-56f86700-cb55-11ea-984f-43be5eb6fe04.png)
![landing_valueProp_1_landscape](https://user-images.githubusercontent.com/63747360/88097414-58299400-cb55-11ea-9913-020a32dd105d.png)
![landingURL](https://user-images.githubusercontent.com/63747360/88097416-58c22a80-cb55-11ea-9837-a15171c8fd80.png)
![landing_valueProp_2_portrait](https://user-images.githubusercontent.com/63747360/88097420-595ac100-cb55-11ea-9ca5-3fc72235c2e7.png)
![landing_valueProp_3_portrait](https://user-images.githubusercontent.com/63747360/88097422-595ac100-cb55-11ea-9aa0-9d82b656aea4.png)
![long_or do you need to scroll to see_](https://user-images.githubusercontent.com/63747360/88097424-59f35780-cb55-11ea-854e-326f2bc95e88.png)

**Comment by alisonuxdesign** [comment]
### DESKTOP

![unauthorized_myIdeas_Post_desktop](https://user-images.githubusercontent.com/63747360/88097742-dede7100-cb55-11ea-8431-d5b766719582.png)
![unauthorized_explore_desktop](https://user-images.githubusercontent.com/63747360/88097745-df770780-cb55-11ea-8a92-9a5057fbf359.png)
![landingPg3_desktop](https://user-images.githubusercontent.com/63747360/88097749-e0a83480-cb55-11ea-8d14-94d802f2a7e4.png)
![landingPg2_desktop](https://user-images.githubusercontent.com/63747360/88097750-e140cb00-cb55-11ea-9f82-6890a7650c4c.png)
![landingPg1_desktop](https://user-images.githubusercontent.com/63747360/88097751-e140cb00-cb55-11ea-95c8-9a23a144a6ac.png)

**Comment by alisonuxdesign** [comment]
![landingPg1_desktop](https://user-images.githubusercontent.com/63747360/88097866-16e5b400-cb56-11ea-9484-32245d686dc2.png)
![landingPg2_desktop](https://user-images.githubusercontent.com/63747360/88097867-1816e100-cb56-11ea-8396-dd496f93f9e4.png)
![landingPg3_desktop](https://user-images.githubusercontent.com/63747360/88097870-18af7780-cb56-11ea-8749-12b055345cb9.png)
![unauthorized_explore_desktop](https://user-images.githubusercontent.com/63747360/88097872-19480e00-cb56-11ea-8243-a9cd9e14e880.png)
![unauthorized_myIdeas_Post_desktop](https://user-images.githubusercontent.com/63747360/88097874-19e0a480-cb56-11ea-9fb6-2092049ef774.png)

**Comment by alisonuxdesign** [comment]
@vedmant here are the assets let me know if you are missing anything. Also going to copy the button specifications for you in so you have the specs in the next comment
[New Swipe Pattern Landing Pages assets.zip](https://github.com/ezl/dailyidea.com/files/4955789/New.Swipe.Pattern.Landing.Pages.assets.zip)

**Comment by alisonuxdesign** [comment]
### Button Guide: 

### Default Button: 

![default button (1)](https://user-images.githubusercontent.com/63747360/87587778-c840a180-c69f-11ea-9383-3ba12b8dd646.png)

```
Default Button
background-color: rgba(91, 65, 187, 1);
width: 131px;
height: 36px;
border-radius: 6px;
padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```

### On Hover: 

![On hover](https://user-images.githubusercontent.com/63747360/87588968-c4158380-c6a1-11ea-8fce-a1c6f866f1ce.png)


```
Hover Button
background-color: rgba(91, 65, 187, 1);
width: 131px;
height: 46px;
border-radius: 6px;

padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```

### Clicked: 

![Clicked](https://user-images.githubusercontent.com/63747360/87588289-9e3baf00-c6a0-11ea-851e-35ddf574dff3.png)

 ```
Clicked Button
background-color: rgba(66, 39, 169, 1);
width: 131px;
height: 46px;
border-radius: 6px;

padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```

### Disabled: 

![disabled button](https://user-images.githubusercontent.com/63747360/87588426-e1961d80-c6a0-11ea-89cc-07c62ac83cbc.png)

```
Disabled Button
background-color: rgba(91, 65, 187, .6);

width: 131px;

height: 36px;

border-radius: 6px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```
### Fixed-Width             

![fixedWidth_button](https://user-images.githubusercontent.com/63747360/87588799-7d278e00-c6a1-11ea-99f6-7ba2ca1d517b.png)


```
 Fixed-Width Button
background-color: rgba(91, 65, 187, 1);
width: 311px;
height: 36px;
border-radius: 6px;

padding: 11px 24px;
Text
color: rgba(251, 251, 253, 1);
size: 16px;
font-family: Avenir LT Std;
```
![login](https://user-images.githubusercontent.com/63747360/88099477-72b13c80-cb58-11ea-9602-cc5a3b051799.png)


```
Selection highlight: 
width: variable
height: 8px;
background-color: rgba(91, 65, 187, 0.15);
oppacity: 15%
```
      
tagging @Watson-B so he can stay in the loop

**Comment by vedmant** [comment]
@ezl To actually make it work properly I'd suggest doing it the way images carousels do this with preloading data for next / previous slides and pre-rendering them, then swipe gesture will feel more slick. Maybe using third party slider for this, I like this one https://github.surmon.me/vue-awesome-swiper/ it should save time and it has tons of features. I can try it first and check if it does what's needed.

**Comment by f-prime** [comment]
@vedmant I looked into vue-awesome-swiper when implementing swipe. It seemed to have too many features for what exactly we needed here. I generally have an aversion to third party dependencies especially for specific features like this that need fine tuning. When something like this has so many features it adds a lot of bloat for very little gain. Unless we're going to have many different kinds of swiping patterns? I don't know, but it seems unlikely. If not, I think it makes more sense to use our own implementation especially since it is not very complicated then we can get it exactly how we want it. 

(Swiper.vue)[https://github.com/ezl/dailyidea.com/blob/dev/front/components/ideaDetail/Swiper.vue] already implements the kind of swiping/sliding needed for this ticket. All that would be needed is to be done is to create the cards then wrap them in Swiper and it will take care of the rest. 

I know that generally "reinventing the wheel" is considered bad, but if we only need a few simple features from a massive swiping library then I'd rather avoid the external dependency. It'll prevent bloat and let us tune the swiping to be _exactly_ how we want it. 

>  I can dynamically load slides while swiping

This something that I had to do for the idea swiping (https://github.com/ezl/dailyidea.com/blob/dev/front/pages/i/_shortId/_slug.vue#L272-L297) maybe it could be factored out so that it's reusable or just used as a reference.

**Comment by vedmant** [comment]
@f-prime OK, I'll go with custom solution. About preloading next prev slides I was thinking to do this not right after swipe but before, so next slide appears immediately without API request first. Also for front page we actually will have whole list of slides already loaded and will need to swipe between all them faster, and it makes sense to pre-prender at least next / prev slides before animation or more. I can create a callback for loading following slides in this case, also it will need to support removing / adding slides dynamically to slider and make it stay on the correct slide.

**Comment by vedmant** [comment]
@ezl Ok, as a first stage I'll work on new top bar and footer. Then on main slider. I'll add a subtasks list here and will update it if needed:

- [ ] New layout component
- [ ] New top bar
- [ ] New footer
- [ ] Front page slider

**Comment by vedmant** [comment]
@ezl There are some things not clear about new front page. About order of slides. I see there is one slide with Signup / Login button, with left and right arrows but without dots on the bottom, then next slide is an idea (should it go there on right arrow?), then there are next three slides with 3 dots on the bottom “How does it work”, “Browse popular ideas” and “Every day log an idea”. What’s not clear on what order this slides change. Or front page is only that 3 slides I mentioned, and Signup / Login slide is the slide on login page? But in this case where left right arrows lead?

**Comment by danleyb2** [comment]
hi @vedmant will be working on this together.  
You layout of the tasks looks okay with me.
As you already working on the **new top bar and footer** is it okay if i start on the **Front page slider** ?

**Comment by vedmant** [comment]
@danleyb2 hi, looks like navbar is already done by @f-prime in https://github.com/ezl/dailyidea.com/issues/497 @ezl could you please manage who should work on which task here?

**Comment by ezl** [comment]
#487 is a replacement for the landing page. any time a user, authenticated or not, no matter how many times they have been to the landing page (www.dailyidea.com/) -- they should see this card interface. it's basically: "the landing page is a 3 card carousel, where if you swipe right on the 3rd carousel item, it takes you to the first item of "browsing" (which, for now is www.dailyidea.com/ideas/all)
