### ISSUE TITLE
API Change - User Idea detail api also requires auther info(name, email and id )

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#49]

**Comment by aldarund** [comment]
You need to query userInfo for that

**Comment by patelravi** [comment]
@aldarund I' just checked userInfo query, it does not return logged in user's name and email id.
Sample of response it returns is given below, we need user's email & name to show on idea detail and profile page.
`
{ 
   "userId":"d331e081-a639-4f14-9a57-2e1380cdcd5e",
   "followersCount":0,
   "followeesCount":0,
   "ideasCreated":19
}
`

**Comment by aldarund** [comment]
I dont think exposing email is a good idea

**Comment by patelravi** [comment]
Can we Share name if provided?

**Comment by ezl** [comment]
closing for now. will re-evaluate app and if this seems relevant, will create a better ticket.
