### ISSUE TITLE
My Ideas Page

### ISSUE THREAD

**Issue by alisonuxdesign** [ezl/dailyidea.com#495]
This Ticket is related to ticket #497  (implementing new Navigation). To implement the new Navigation we will simultaneously need to implement the new My ideas structure. 

### My ideas is broken up into three sections: My Ideas, Saved Ideas, and Settings/edit profile. My ideas and Saved Ideas utilizes a miniature stacked card structure that opens into lightboxes. 

**My Ideas**

![myIdeas_portrait](https://user-images.githubusercontent.com/63747360/88416605-b8127b80-cd9d-11ea-8693-3c3b7006e579.png)
![myIdeas_landscape](https://user-images.githubusercontent.com/63747360/88416608-b9dc3f00-cd9d-11ea-8c83-a8af1ca16a8e.png)
![lightboxPost_portrait](https://user-images.githubusercontent.com/63747360/88416610-b9dc3f00-cd9d-11ea-96f6-8bd47abe46bc.png)

**Saved Ideas**
Later we will section up the Saved ideas so the user can add idea boards to organize their ideas but for now we will just have it look exactly like the "my ideas" section but for saved. 

![preGroupingIdeas_portrait](https://user-images.githubusercontent.com/63747360/88416835-20615d00-cd9e-11ea-8742-6a3ea3c3c673.png)

**Settings**

![settings_portrait](https://user-images.githubusercontent.com/63747360/88417302-f3fa1080-cd9e-11ea-8803-17ed3ed66100.png)
![settingsScrolled_landscape](https://user-images.githubusercontent.com/63747360/88417303-f52b3d80-cd9e-11ea-9a9c-352f3db3d4d9.png)
![settingsScrolled_portrait](https://user-images.githubusercontent.com/63747360/88417305-f5c3d400-cd9e-11ea-9826-8534f7ada931.png)
![settings_landscape](https://user-images.githubusercontent.com/63747360/88417352-07a57700-cd9f-11ea-878d-8658b04f3a81.png)

**Edit Proflie**
![editProfile_portrait](https://user-images.githubusercontent.com/63747360/88417395-1724c000-cd9f-11ea-85e3-f6e3e6c12709.png)
![editProfile_landscape](https://user-images.githubusercontent.com/63747360/88417400-1a1fb080-cd9f-11ea-835b-8e2c4838a0cb.png)
![editName_landscape](https://user-images.githubusercontent.com/63747360/88417422-2146be80-cd9f-11ea-98ae-694b07d9dc62.png)
![editName_portrait](https://user-images.githubusercontent.com/63747360/88417411-1d1aa100-cd9f-11ea-94ae-98215c59011c.png)
![editBio_portrait](https://user-images.githubusercontent.com/63747360/88417428-2441af00-cd9f-11ea-946b-64e19f37495b.png)
![editBio_landscape](https://user-images.githubusercontent.com/63747360/88417432-26a40900-cd9f-11ea-8932-62bd479fc06a.png)
![diTNC__portrait](https://user-images.githubusercontent.com/63747360/88417443-29066300-cd9f-11ea-937d-09d5d65f43ef.png)
![diPrivacy_portrait](https://user-images.githubusercontent.com/63747360/88417450-2b68bd00-cd9f-11ea-8694-6d574a9568fa.png)

**Comment by alisonuxdesign** [comment]
### Assets

Collapsed Mini-card: 

![Mini-card](https://user-images.githubusercontent.com/63747360/88418487-d8900500-cda0-11ea-9202-7cdb0601c1ab.png)

```
background-color:  rgba(251, 251, 253, 1);
width: 343px;
height: 193px;
border-radius: 10px;
box-shadow: 0px 4px 20px rgba(0, 0, 0, .1);
padding: 16px;

Title
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #151125;

User Name:
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: #5B41BB;

Time stamp
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: rgba(21, 17, 37, 0.6);

View Idea button (bottom)
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: #5B41BB;


```
Settings Card: 
![Settings Card](https://user-images.githubusercontent.com/63747360/88418565-fb221e00-cda0-11ea-8f87-cc5369ceaee6.png)

```
width: 343px;
height: 357px;
background: #FFFFFF;
box-shadow: 0px 4px 20px rgba(0, 0, 0, 0.1);
border-radius: 10px;

Titles (edit profile, idea reminder...)
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 135.3%;


Secondary Titles (email settings,logout)
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 16px;
line-height: 19px;
color: rgba(0, 0, 0, 0.6);


Sub text
font-family: Avenir LT Std;
font-style: normal;
font-weight: normal;
font-size: 12px;
line-height: 14px;
color: #878787;
```


### Icons here: 
[Settings Icon.zip](https://github.com/ezl/dailyidea.com/files/4973472/Settings.Icon.zip)

**Comment by alisonuxdesign** [comment]
My Profile - Portrait
myProfile_portrait

profile nav Portrait
Box: 
/* Style for "Rectangle" */
width: 375px;
height: 52px;
background-color: #ffffff;

Selection highlight: 
width: variable
height: 8px;
background-color: rgba(91, 65, 187, 0.15);

Selection Underline: 
width: variable
height: 2px;
background-color: #ffc61e;

Selected text:
color: #5b41bb;
font-family: "Avenir LT Std";
font-size: 16px;
font-weight: 400;
margin-top: 17px;
margin-bottom: 16px;

Non-selected text:
color: #151125;
font-family: "Avenir LT Std";
font-size: 16px;
font-weight: 400;
margin-top: 17px;
margin-bottom: 16px;

my ideas:
margin-left: 48px;
margin-right: 32px;

saved ideas:
margin-right: 32px;
My Profile - Landscape
myProfile_landscape

profile nav Landscape:
Box: 
/* Style for "Rectangle" */
width: 812px;
height: 52px;
background-color: #ffffff;

Selection highlight: 
width: variable
height: 8px;
background-color: rgba(91, 65, 187, 0.15);

Selection Underline: 
width: variable
height: 2px;
background-color: #ffc61e;

Selected text:
color: #5b41bb;
font-family: "Avenir LT Std";
font-size: 16px;
font-weight: 400;
margin-top: 17px;
margin-bottom: 16px;

Non-selected text:
color: #151125;
font-family: "Avenir LT Std";
font-size: 16px;
font-weight: 400;
margin-top: 17px;
margin-bottom: 16px;

my ideas:
margin-left: 144px;

settings:
margin-right: 144px;
My Profile - Desktop
myProfile_desktop

```
Top Nav with button
W: 1440px
H: 52px
Background-color: #FFFFFF;

Selection highlight: 
width: variable
height: 8px;
background-color: rgba(91, 65, 187, 0.15);

Selection Underline: 
width: variable
height: 2px;
background-color: #ffc61e;

Selected text:
color: #5b41bb;
font-family: "Avenir LT Std";
font-size: 16px;
font-weight: 400;
margin-top: 17px;
margin-bottom: 16px;

Non-selected text:
color: #151125;
font-family: "Avenir LT Std";
font-size: 16px;
font-weight: 400;
margin-top: 17px;
margin-bottom: 16px;

my ideas:
margin-left: 386px;

settings:
margin-right: 386px;

**Comment by alisonuxdesign** [comment]
### **Desktop**


**_My Ideas main section_**
Please note that this is the only section that has a lightbox for Desktop In the form of an expanded mini-card. 

![myIdeas_desktop](https://user-images.githubusercontent.com/63747360/88569586-de335800-cff7-11ea-8063-b23f116c4adc.png)
![myIdeas_edit_desktop](https://user-images.githubusercontent.com/63747360/88569591-df648500-cff7-11ea-9b79-7bf6a9690c66.png)
![myIdeas_expanded_desktop](https://user-images.githubusercontent.com/63747360/88569715-133faa80-cff8-11ea-8a6d-f7d17c20ca19.png)

![myIdeas_empty_desktop](https://user-images.githubusercontent.com/63747360/88569597-dffd1b80-cff7-11ea-818b-5e103110c214.png)

**_My saved Ideas_**
![Saved Ideas](https://user-images.githubusercontent.com/63747360/88569789-2e121f00-cff8-11ea-9157-9ccc0fee45a8.png)
![savedIdeas_empty_desktop](https://user-images.githubusercontent.com/63747360/88569792-2f434c00-cff8-11ea-927c-566a9af7aca1.png)


**_Settings_**
![settings_desktop](https://user-images.githubusercontent.com/63747360/88569852-4124ef00-cff8-11ea-9847-b650eabebae9.png)
![editAccount_desktop](https://user-images.githubusercontent.com/63747360/88569881-47b36680-cff8-11ea-8a17-99f0040841c5.png)
![about_desktop](https://user-images.githubusercontent.com/63747360/88569889-4b46ed80-cff8-11ea-80e9-0bba2823d165.png)
![FAQ_desktop](https://user-images.githubusercontent.com/63747360/88569897-513cce80-cff8-11ea-845d-2495351aa19a.png)
![editAccount_desktop](https://user-images.githubusercontent.com/63747360/88569903-56018280-cff8-11ea-92b3-fc9bfe190a33.png)

**Comment by f-prime** [comment]
@alisonuxdesign Where can I find the "start saving inspiration" image?
