### ISSUE TITLE
Skeleton Card Browse Swipe interaction

### ISSUE THREAD

**Issue by alisonuxdesign** [ezl/dailyidea.com#498]
We are implementing a skeleton card to live underneath any given card so that when the user swipes one direction or another, they are given a visual queue that another card is behind it. 

![skeleton_matte](https://user-images.githubusercontent.com/63747360/88608553-3ccff480-d03f-11ea-823c-7f428e0cb4db.gif)

![Skelton Card Portrait](https://user-images.githubusercontent.com/63747360/88608158-502e9000-d03e-11ea-8b90-d37a712ba349.png)
![shortIdea_img_landscape](https://user-images.githubusercontent.com/63747360/88608165-53298080-d03e-11ea-98ff-b48227476031.png)

Assets: 

[Skeleton Cards.zip](https://github.com/ezl/dailyidea.com/files/4985450/Skeleton.Cards.zip)

**Comment by vedmant** [comment]
@ezl We don't have cards like that currently. Swiping is different from the image above, also list of ideas are loaded on the page, so there is no need to show skeleton, they can be rendered instantly. Not sure what do to for this task.

**Comment by ezl** [comment]
The task is just to put a static card placeholder underneath where the currently displayed card is. it is only visible when the primary card is moved from it's base position.

@alisonuxdesign -- please
(A) correct me if I'm wrong
(B) confirm that we still want to do this

**Comment by vedmant** [comment]
@ezl The main problem is that we don't have card underneath, we have different swipe pattern: 

![Aug-31-2020 09-59-29](https://user-images.githubusercontent.com/5052406/91691664-b1cba800-eb70-11ea-9502-2b25ae977a43.gif)

Furthermore, list of next and previous ideas is pre-cached, so there is no need to wait for something, next card can be rendered instantly.

**Comment by vedmant** [comment]
@ezl Oh, I see, sorry, I was thinking that skeleton is for next idea card, but this is just a background without any fuction.

**Comment by vedmant** [comment]
@ezl Ok, done, to safe time I didn't do skeleton pixel perfect, but similar in layout. Let me know if pixel perfect is important here, I can make it.

**Comment by ezl** [comment]
correct. my understanding is taht the skeleton does not have any function.

pixel perfect is not important. will review once this PR gets merged and is live.
