### ISSUE TITLE
Preview Image for sharing an idea

### ISSUE THREAD

**Issue by alisonuxdesign** [ezl/dailyidea.com#505]
We can explicitly set the "Preview image" that is displayed when someone posts a link on facebook or how it renders in slack/sms.

1. IIf a user INCLUDES an image, we should use their image, e.g. https://www.dailyidea.com/i/8ve2gd/finnish-spa
2. If there is no attached image we should share this graphic:

![no_blush](https://user-images.githubusercontent.com/63747360/89439838-fdbd3580-d707-11ea-93a4-adfebc80a86e.png)

Asset: [no_blush.png.zip](https://github.com/ezl/dailyidea.com/files/5029829/no_blush.png.zip)

**Comment by ezl** [comment]
@alisonuxdesign @Watson-B sorry -- just realized -- this image is too big.

the preview image sizes should follow certain recommendations for opengraph standards to make sure they render well across different platforms (facebook, twitter, etc preview things differently, as do fb messenger, android SMS, and iMessage).

there are a few different POVs on this (you can google about it if you like).

My recommendation is to keep it to the same size as the existing preview image -- but if you can find research that suggests a better size for Opengraph preview images, we can use that as well.

The current one is 1200x630

**Comment by alisonuxdesign** [comment]
@ezl good to know. I will resize and resend. Do you need it in PNG form or SVG? I have both attached in the asset zip folder I believe but can resize the PNG specifically with new dimensions

**Comment by alisonuxdesign** [comment]
Here is the new resized PNG: 
[no_blush.png.zip](https://github.com/ezl/dailyidea.com/files/5057560/no_blush.png.zip)

**Comment by ezl** [comment]
any format is fine. moving this back to "ready for implementation"

**Comment by vedmant** [comment]
@ezl There is already default og image: https://dailyidea-serverless-static-dev.s3.amazonaws.com/og-default-image.png so I just replace it with attached one? If idea includes image it puts that image to og tag.

**Comment by ezl** [comment]
hmmmm I realize now this issue isnt as thought out as necessary. Back to the drawing board for ~alison and I.

No action at this time.

**Comment by alisonuxdesign** [comment]
@ezl how do you feel about this: 

![no_blush](https://user-images.githubusercontent.com/63747360/93722162-f8019f00-fb51-11ea-9625-16ab76871844.png)

**Comment by ezl** [comment]
❤️
