### ISSUE TITLE
Unauthorized User states 

### ISSUE THREAD

**Issue by alisonuxdesign** [ezl/dailyidea.com#506]
This ticket is to address What the site looks like to authorized users and what kind of experience they having during these crucial first touchpoints. 

1. Users will only be able to access Explore during their pre-logged in session when trying to navigate to Post or My Ideas the yare taken to this page: 

![My Ideas 21](https://user-images.githubusercontent.com/63747360/89446137-6230c280-d711-11ea-8d61-e0a2f5c9446d.png)
![My Ideas 23](https://user-images.githubusercontent.com/63747360/89446140-62c95900-d711-11ea-89b1-7b04b248acaf.png)
![unauthorized_myIdeas_Post_desktop](https://user-images.githubusercontent.com/63747360/89446144-64931c80-d711-11ea-810f-d0baebad7a8a.png)

**### 2. Lets get users to convert** ### (This is a replacement of ticket #435)

A. In the case of an unauthorized user trying to comment/save/share: If the user is the middle of the interaction, we verify their email and drop them back into the action they wanted to complete and show a toast message that their action was completed. As soon as they click into any other navigation tab (other than Explore) they are brought into the onboarding flow. 

### **Mobile**

**Save:** 
![bookmarkUnauthorized_portrait_2](https://user-images.githubusercontent.com/63747360/89443577-b33eb780-d70d-11ea-8bf1-10d585293948.png)
<img width="852" alt="bookmarkUnauthorized_landscape_2" src="https://user-images.githubusercontent.com/63747360/89443581-b5a11180-d70d-11ea-9229-b23387441889.png">
![bookmarkUnauthorized_portrait_2](https://user-images.githubusercontent.com/63747360/89443869-247e6a80-d70e-11ea-8eed-930c7f6bf0ae.png)

**Comment**
![comments_unauthorizedModal_portrait](https://user-images.githubusercontent.com/63747360/89443599-bafe5c00-d70d-11ea-9234-126296dbfa24.png)
![Comment posted](https://user-images.githubusercontent.com/63747360/89444089-6c9d8d00-d70e-11ea-8b30-2d3438fe586a.png)

Share:
![share_portrait_3_unauthorizedConfirm](https://user-images.githubusercontent.com/63747360/89444545-1715b000-d70f-11ea-9473-286f46f92fa5.png)
![share_portrait_3_authorizedConfirm](https://user-images.githubusercontent.com/63747360/89444557-1aa93700-d70f-11ea-982c-37252d5eade3.png)

### Desktop
**Save**
![unauthorizedBookmark_desktop](https://user-images.githubusercontent.com/63747360/89444709-5e9c3c00-d70f-11ea-8081-d767238ce7f6.png)
![bookmark_desktop](https://user-images.githubusercontent.com/63747360/89444863-9c996000-d70f-11ea-9ff7-4a487ea2cdb5.png)

**Comment**

![unauthorizedComment_desktop](https://user-images.githubusercontent.com/63747360/89445032-d9fded80-d70f-11ea-891e-453891467d90.png)

**Share**
![share_options_desktop](https://user-images.githubusercontent.com/63747360/89444741-6956d100-d70f-11ea-891c-a90eeaac904a.png)
![share_email_desktop](https://user-images.githubusercontent.com/63747360/89444761-707ddf00-d70f-11ea-8234-9f99191536d3.png)
![unauthorizedShare_desktop](https://user-images.githubusercontent.com/63747360/89444777-75db2980-d70f-11ea-8d16-c6da12516e72.png)
![share_confirm_desktop](https://user-images.githubusercontent.com/63747360/89444803-7ffd2800-d70f-11ea-87ba-888483f20d1e.png)

B. In the specific case of share, we should allow users to share their content and then exit out of the modal and continue to browse if they want to continue to be an unauthorized user. The user should not have to be authorized to share content. 

C. In the case of like: we verify their email and then drop them immediately into the onboarding flow as this is such a lesser action that I don’t think this should be too disruptive. 

![Like_portrait_3_unauthorizedConfirm](https://user-images.githubusercontent.com/63747360/89443644-ca7da500-d70d-11ea-870c-90c664a5d252.png)

![unauthorizedreact_desktop](https://user-images.githubusercontent.com/63747360/89445312-352fe000-d710-11ea-99cb-0813e810cdb8.png)

**Comment by alisonuxdesign** [comment]
Assets here:
[Assets Unauthorized User states.zip](https://github.com/ezl/dailyidea.com/files/5030277/Assets.Unauthorized.User.states.zip)

**Comment by vedmant** [comment]
@ezl @alisonuxdesign Wanted to make sure, is this task only about "Oops, looks like you don't have an account yet!" or it will include this dialogs for commenting, saving ideas, etc... Thing is that we already have this functions, but dialogs look a bit different, so it's not clear for me if I should update dialogs to make them look like in images above.

**Comment by ezl** [comment]
@alisonuxdesign i chatted with @vedmant on this and he has a lot of questions about this particular ticket implementation.

i propose that you redo or close and open a new ticket for this in the story format you were exploring.

**Comment by vedmant** [comment]
@alisonuxdesign @ezl Another thing, since we have cards interface now, I see that desktop example is in card but mobile example is not in the card, so probably both mobile and desktop have to be cards like other pages https://prnt.sc/ulmcid

**Comment by ezl** [comment]
@vedmant use your best judgment and just proceed with what you think makes the most sense here.
