### ISSUE TITLE
Create a way to handle env variables between environments

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#509]
To avoid missing needed env variables when deployed to production. Needs discussion

**Comment by vedmant** [comment]
@aldarund I think quite a simple solution will be to add a build plugin to Nuxt to read all env keys from example.env and then check if all that keys exists. That will ensure that current environment has all keys that are present in example.env.

**Comment by ezl** [comment]
mmmm -- i'm wary of overengineering a solution.

is this not as easily solved with "make sure to always update the README if we change env variables?"

**Comment by vedmant** [comment]
@ezl The problem with readme is that it's all manual, means that someone who will deploy new changes to production will need to manually re-check if any new variable was added (also someone who adds variable needs to make sure to add it to readme). I don't think it readme can solve anything, it will be very easy to miss env variables check especially cause we don't change them often.

**Comment by vedmant** [comment]
@ezl Please let me know if I should proceed with env validator module, this should be quite simple one, but will ensure that all env variables that are in example.env present during building, so if something is missing build will fail.

**Comment by ezl** [comment]
i don't like it. i still prefer documentation.

waiting for @aldarund to respond to be the tie breaker.

**Comment by vedmant** [comment]
@ezl Currently since we use Wercker most of the variables added globally for all environments, also there is no point to spend time on this if we going to rewrite backend.

**Comment by ikosovec** [comment]
Moving back to Icebox.
