### ISSUE TITLE
implement one-idea-at a time on explore

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#516]
Let's go ahead and implement a "One idea at a time" browsing experience. The current experience is that "all ideas" (aka explore) is abbreviated ideas cards that are stacked on top of one another and once the user clicks into an idea they can swipe between them. We want to make it so there is no "stacked view" on explore just one idea at a time. This is so that users are able to focus on one idea at a time.  

See before: 

![Screen Shot 2020-08-21 at 2 16 20 PM](https://user-images.githubusercontent.com/63747360/90930959-e98c6000-e3b8-11ea-9a73-0080faa3f8ff.png)

See After: 
![ideaView_desktop](https://user-images.githubusercontent.com/63747360/90931114-2d7f6500-e3b9-11ea-9b86-fed1c7c5899a.png)

**Comment by ezl** [comment]
@alisonuxdesign I recommend you chat with @f-prime regarding this for implementation
