### ISSUE TITLE
Make idea search work

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#52]

**Comment by ezl** [comment]
I think this is going to wait until after Django rewrite

**Comment by Watson-B** [comment]
Thoughts - No search in site, search would be cool, searching by keyword would be great. Need search results page. Should results be a bunch, single? Does it enter swipe interface when they click on a result, pop into full idea.

**Comment by vedmant** [comment]
@ezl I see you moved this to Up Next, I then Implement search without interface, just a simple page. For the proper text search I'll need to use something like Cloud Search, it will index DynamoDd data https://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-dynamodb-data.html . I'll spend some time to see how to connect this things.

**Comment by vedmant** [comment]
@ezl I can't find proper example where everything is connected together, I think it's better if someone with good Appsync / Serverless knowledge will do this. For now I can just make simple DynamoDb scan if title or content contains exact query.

**Comment by ezl** [comment]
@vedmant let me think about this as well. I will discuss with @shchoi22.

Personally, I do NOT want us to invest ANY more time into building this dynamodb/appsync stuff unless absolutely necessary. Right now I've started focusing on user acquisition.

However, I DO feel that search is important.

So one possible path is to create a separate service for search (possibly elastic search), which can be used also after we rewrite the backend.

(Assuming we do start acquiring users, the backend will be written in django/django rest framework)

**Comment by vedmant** [comment]
@ezl Sure, however integration with Elasticsearch on Django and AWS are totally different things, the most work is for configuring database indexing, so even if we do this in AWS, in will need total rewrite when moved to Django.

**Comment by ezl** [comment]
understood. for now lets do nothing on idea search then.

i've asked @shchoi22 to help me consider approaches for the rewrite so I may execute that sooner than originally intended.
