### ISSUE TITLE
Design an empty state for "ideas" page

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#526]
When a user has no ideas, show something.

Example of an empty one:
https://www.dailyidea.com/ideas/nick-8feb

**Comment by alisonuxdesign** [comment]
Implement Empty state for my ideas page: 

![myIdeas_empty state](https://user-images.githubusercontent.com/63747360/93723155-6b5adf00-fb59-11ea-8bfe-a858f9591968.png)

- Plus sign takes user to the posting page. This is image is only displayed when the user has no ideas. 

Asset here:
[empty state my ideas.png.zip](https://github.com/ezl/dailyidea.com/files/5252774/empty.state.my.ideas.png.zip)

**Comment by vedmant** [comment]
@alisonuxdesign Is this only for mobile? What about desktop version, we already have c card for desktop and mobile: https://prnt.sc/ulmrwa should I replace only mobile version then?

**Comment by ezl** [comment]
@vedmant no -- please implement for both.

For now, just proceed and use your best judgment for what you think an appropriate design would look like, based on the mobile empty state card.

**Comment by vedmant** [comment]
@alisonuxdesign Could you attach bigger image or svg image? This one is small and will look blurry.

**Comment by ezl** [comment]
@vedmant here's an svg.

[undraw_season_change_f99v.svg.zip](https://github.com/ezl/dailyidea.com/files/5279921/undraw_season_change_f99v.svg.zip)

If you need to generate it again from source or prefer png, it can be found on undraw (https://undraw.co/search), with title "season change". You'll need to change the color to #5B41BB
