### ISSUE TITLE
New API: Send email to registeration with add comment

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#54]
To support the feature mentioned in [issue #6](https://github.com/ezl/dailyidea.com/issues/6), api needs to be implemented with following logic.

- Api will accept ideaId, comment content and email Id (user provided from ui)
- API will send an email as described in issue#6.

**Comment by ezl** [comment]
closing this ticket - unclear to me what it really means. I *think* it means to notify a user whenever a comment is left on his/her idea, but i'm not super sure. Creating a separate ticket for that.
