### ISSUE TITLE
[idea detail] fix comments / kebab placement on desktop

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#544]
https://monosnap.com/file/7UOKDmoahpESr92JweWgab9w8REJ6S

Seems wrong. If this is intended, then disregard.

**Comment by f-prime** [comment]
This is a bug that is fixed in https://github.com/ezl/dailyidea.com/pull/537

**Comment by ezl** [comment]
ok thanks @f-prime - closing issue.
