### ISSUE TITLE
New UI- Error state logging in

### ISSUE THREAD

**Issue by alisonuxdesign** [ezl/dailyidea.com#560]
Use case: when a user uses an expired auth link or provides an email address that does match a code they are currently taken to a screen that looks like this: 

<img width="1049" alt="Screen_Shot_2020-09-15_at_10 25 03_AM" src="https://user-images.githubusercontent.com/63747360/93829563-24d5b500-fc2b-11ea-82b5-bcd59484aa41.png">

Can we Remake this screen to look like this? 
![Code expired_desktop](https://user-images.githubusercontent.com/63747360/93829875-e987b600-fc2b-11ea-9ac0-18288ffc8b9c.png)

asset: 
<img width="325" alt="Bird Illustration" src="https://user-images.githubusercontent.com/63747360/93829881-ee4c6a00-fc2b-11ea-9619-8909bdfda844.png">

https://www.figma.com/file/vwPwlzhQC2FrCIfdcxshm5/Daily-Idea-Mobile-Desktop?node-id=707%3A0

**Comment by vedmant** [comment]
@ezl @alisonuxdesign Probably this ticket is outdated, this is how expired page looks currently: https://prnt.sc/upj3a0

**Comment by ezl** [comment]
interesting. @alisonuxdesign and I took that screenshot only a week ago. It's possible that the ticket had already been executed but not merged though, since a lot has been merged and deployed in the last week.

@vedmant Closing this ticket as your screen shot shows it's complete.
