### ISSUE TITLE
Unauthenticated Comment on an idea

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#6]
Add the functionality so a user can comment on an idea.

In the same way blogs and other platforms do this, let the user TRY to start leaving a comment before forcing them to authenticate, then when they press the button that causes the comment to be left, make them authenticate.

however, lets be a little more clever with our UX in order to improve the experience and the completion rate.

## Case 2: if the user is NOT authenticated, the flow should be something like:

1. type in the comment
2. press the submit button
3. modal or some sort of message pops up saying: "Oops, verify your email or sign in to post your comment!" -- include an email form field and a button which triggers the email send.
3.5 go to "sent an email, check your inbox!" page.
4. we send a message to the email address they submitted. The email content says "post your comment" and contains the idea title and the comment text that was used by the user in the steps above.
5. When the "post your comment" button is clicked from the email, it takes the user back to the idea detail page they were already on, and the comment should be posted. This is possible because we know what detail page the user was on, and what the comment content was. 
6. We should display a different modal success message BASED ON whether the user previously existed or not. (A) if the user did exist before, we just say "Welcome back, Username! Thanks for your comment!" OK button to close modal. (B) if the user did NOT exist before, we create an account for that user, then show a modal that says "Thanks for your comment!"
<img width="269" alt="thanks" src="https://user-images.githubusercontent.com/157627/62009539-060e8800-b126-11e9-8648-0107eed07628.png">

**Comment by aldarund** [comment]
Case 1 implemented

**Comment by ezl** [comment]
potentially should break up into 2 tickets - 1 for authenticated case (easy), 1 for unauthenticated case (more UX work). I think this is later.

leaving intact for now.
