### ISSUE TITLE
[landing page] Fix font sizes at all screen widths

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#600]
https://monosnap.com/file/iGmOiOPFUB5AvalbY1T96y1n9iQ3g6

Especially the 2nd widest setting has badly sized fonts. Between the largest (ok), 2nd largest (fonts are WAY too big), and 3rd (also ok), these aren't scaling well.

If there are default font sizings in whatever framework we are using, we should use that. If not, try to put in global defaults so we don't have to manually define these on every page.

**Comment by vedmant** [comment]
@ezl That home page is generally done weird, it uses separate components for landscape and portrait. I'd better refactor and remove that code duplicate. What do you think?

**Comment by danleyb2** [comment]
@vedmant Have taken care of the duplicated code by creating a single component for Landscape and Portrait
@ezl The second picture is how it looks now

![20201027_191338](https://user-images.githubusercontent.com/9919961/97330058-d0a49d00-1888-11eb-93e8-98aef540542d.png)

![20201027_191651](https://user-images.githubusercontent.com/9919961/97330256-11041b00-1889-11eb-89a9-b55ff464ffc2.png)
