### ISSUE TITLE
[landing page] fix button colors to match design

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#602]
Buttons in landing page implementation are currently black:
https://monosnap.com/file/Y6ZNC8gLYIG6NIl8gfRMRdOuaVEFKo

Correct to match the design by @alisonuxdesign, where they are purple:
https://monosnap.com/file/Y6ZNC8gLYIG6NIl8gfRMRdOuaVEFKo

Original figma link:
https://www.figma.com/file/vwPwlzhQC2FrCIfdcxshm5/Daily-Idea-Mobile-%2B-Desktop?node-id=279%3A8156

**Comment by ikosovec** [comment]
This looks fine now.
