### ISSUE TITLE
[landing page] "swipe right" vs swipe either way?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#606]
1. Currently, landing page copy says "swipe right" in the Tinder sense, but it's ACTUALLY swipe left. (but "*page* right" in the Kindle sense)
2. Can we implement swiping BOTH ways? meaning let's do a mirror reflection of the cards so that the user doesn't get stuck if they swipe the wrong way?

What I mean is:

Currently, the implementation is such that if you swipe one direction (LEFT,  move forward), then it takes you through this sequence:
```
0 (default start) every day log an idea
1 -> "2/3: Browse Popular"
2 -> "3/3: How it works"
3 -> First idea
```
This is good.

However, if you swipe the other way (RIGHT, move backwards) on mobile, it just keeps loading the same page.

One possible solution to this is to drop the user into the CENTER of a series of cards, so swiping either way produces the same sequence:

```
-3 -> First idea
-2 -> "3/3: How it works"
-1 -> "2/3: Browse Popular"
0 (default start) every day log an idea
1 -> "2/3: Browse Popular"
2 -> "3/3: How it works"
3 -> First idea
```

**Comment by alisonuxdesign** [comment]
I like this solution! Dropping the user into a sequence of cards... this however would only work on the "top" category and not "new".
