### ISSUE TITLE
[landing page] fix swipe sequence

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#608]
1. in designs, the card you land on is 1/3, then the first card you swipe TO is 2/3. In the implementation, after the first swipe, you arrive at 1/3. This messes up the sequence. As a check, notice that "browse" is 2/3 and "how does it work is 3/3 in figma: https://monosnap.com/file/ptzv47sMy9mduHsdT6UyNusE52Vhu5

2. after swiping past the last explainer card ("how does it work"), the user gets dropped to an unauthorized page. instead, the user should be shown an idea.

**Comment by vedmant** [comment]
@ezl I generally don't like how this is implemented, I'd refactor font page completely.
