### ISSUE TITLE
[action modals] Update style

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#610]
The "share" dialog uses this style:
https://monosnap.com/file/ct75y8sh4Buhv32Ea2vmaQUnj3a6Tl

But the "comment" "like" and "save" modals use this style:
https://monosnap.com/file/RTfJQ217jEZOGhTKCTRhvAT022RIPd

Did we revert some code here? I thought we had moved to all dialogs that look more like the "share" one, but this comment/like/save seem old?

Possibly related, @vedmant I recall you did some work here:
https://github.com/ezl/dailyidea.com/issues/331

**Comment by vedmant** [comment]
@ezl Latest edits were done by @f-prime where he added a bar between buttons, removed image from comment dialog https://github.com/ezl/dailyidea.com/commit/2fef6d6852953306b1a71223916ffdf565258ea9 . So this looks like  "comment" "like" and "save" dialogs have recently updated styles, and only "share" was not updated (cause it uses custom footer).

The question is should I update "share" dialog to match all other, or revert changed on "comment" "like" and "save" dialogs?

**Comment by ezl** [comment]
@vedmant can you take screenshots of all those dialogs as they are now and put them in here -- I'll respond here

**Comment by vedmant** [comment]
@ezl 
<img width="648" alt="Screenshot at Oct 20 19-58-47" src="https://user-images.githubusercontent.com/5052406/96619561-fe309a00-130e-11eb-808f-1e257bd170b4.png">
<img width="624" alt="Screenshot at Oct 20 19-59-11" src="https://user-images.githubusercontent.com/5052406/96619569-012b8a80-130f-11eb-8b83-5190f9d236b5.png">
<img width="633" alt="Screenshot at Oct 20 19-59-28" src="https://user-images.githubusercontent.com/5052406/96619576-038de480-130f-11eb-8488-912151ac8049.png">
<img width="659" alt="Screenshot at Oct 20 19-59-57" src="https://user-images.githubusercontent.com/5052406/96619582-05f03e80-130f-11eb-9700-542504f556d8.png">
<img width="670" alt="Screenshot at Oct 20 20-00-20" src="https://user-images.githubusercontent.com/5052406/96619587-08529880-130f-11eb-95a7-c54e01ed0f80.png">
<img width="649" alt="Screenshot at Oct 20 20-00-35" src="https://user-images.githubusercontent.com/5052406/96619607-0dafe300-130f-11eb-95a9-89c235a257b5.png">
<img width="668" alt="Screenshot at Oct 20 20-01-01" src="https://user-images.githubusercontent.com/5052406/96619624-11436a00-130f-11eb-8354-9bc064f16351.png">

**Comment by ezl** [comment]
Oof. Ok:

1. Input styles should all match the one on "Share" (small purple icon prepended)
2. Buttons should match the new ones (like, comment, save)
3. Welcome back -- these buttons look weird -- it's missing the left side one. If there's only one, just center it in the middle.
4. All modals should have an image -- just pick any placeholder image and enter it for all of them. Or even better, pick one you think is best from https://undraw.co/

**Comment by alisonuxdesign** [comment]
Hey all here are the designs here: https://www.figma.com/file/vwPwlzhQC2FrCIfdcxshm5/Daily-Idea-Mobile-Desktop?node-id=841%3A2079

Assets are here: 
[Modals assets.zip](https://github.com/ezl/dailyidea.com/files/5440395/Modals.assets.zip)
