### ISSUE TITLE
[login flow] don't take user to an empty page

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#612]
currently, when a user logs in, the user is dropped onto an empty page.

to test:
1. try to log in
2. click link in email
3. you'll get taken to https://www.dailyidea.com/ideas/all, which looks like this: https://monosnap.com/file/uPztzaKBAiioS7U6S8jqtZHYmATDSX

Edit:
This may be a duplicate of:
https://github.com/ezl/dailyidea.com/pull/597 / https://github.com/ezl/dailyidea.com/pull/597

**Comment by f-prime** [comment]
Addressed in this pr

**Comment by ezl** [comment]
thanks @f-prime 

I created the ticket, but saw the PR afterwards. Just didn't close it in case it wasn't the same. Closing now. :)
