### ISSUE TITLE
There's some sort of bug with mobile safari always thinking it's the first time a user has been to the site

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#616]
on ios 13.07 on iphone 7, every time I go to explore, it ALWAYS thinks it's my first time there -- it always shows the explainer card created here:

https://github.com/ezl/dailyidea.com/issues/481

**Comment by vedmant** [comment]
@ezl I think this was the bug introduced by this commit: https://github.com/ezl/dailyidea.com/commit/bd74e0f4b1cbfa1138650ea9a31663c94b71b8cc#r43364442 I fixed it already

**Comment by vedmant** [comment]
Tried it on iOs simulator and safari, can't reproduce it, I think it was already fixed

**Comment by ezl** [comment]
@vedmant closing. I checked and could not replicate this anymore so I assume it has been resolved.
