### ISSUE TITLE
[idea detail view] fix images

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#617]
This was previously worked on in:
https://github.com/ezl/dailyidea.com/issues/563

It was improved, but not completely fixed.

One thing that WAS fixed in #563 is that the image is resized in the lightbox view.

Tasks for this ticket to continue:
1. In the non-lightbox/preview of the card, also resize images to fit (currently only the lightbox view is resized, not the non-lightbox view)
2. do NOT allow clicking the image to lead to loading the URI of the image asset on aws. (clicking the image in the lightbox and non-lightbox view should do nothing different than if it was blank space)

Good sample link to try:
https://www.dailyidea.com/i/3dgdlr/better-airbnb-chrome-extension?category=top

Video demo of error:
https://monosnap.com/file/mb0ah3j5TagtTn0vDCpKp6lbh3Ehmv

Assigning to @vedmant since @vedmant did the original implementation of #563

**Comment by vedmant** [comment]
@ezl Fixed images size, previously I made only .jpg images non clickable, added also .png and .gif. Not sure if we support any other images?
