### ISSUE TITLE
enhancement: reverse card animation and "end of stack" alert if user goes beyond available cards

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#618]
After discussion with @f-prime, instead of supporting negative indexing (unintuitive) or bidirectional scroll (unnecessary complexity), the solution for "end of card stack" is now 2 parts.

1. If the user tries to go beyond the first or last card either swiping (on mobile) or paging (on desktop), REVERSE the card animation when showing the same card.

*PROBLEM*: Currently, for example, if the user is on the FIRST card, the only valid action is to LEFT swipe to get to the 2nd card. However, if they RIGHT swipe, we swipe the card off to the right, then show the SAME card showing up from the left. This makes it appears as if there is an infinite stream of the SAME card being displayed over and over. This is bad. As an example, you can try this on the first card of the landing page. just continue to swipe right over and over and it looks like the same card is coming up next.

*SOLUTION* - If the user chooses a direction in which there are no cards remaining, we still swipe the card OFF in the same direction, but instead of redisplaying the same card by sliding it ON from the opposite direction (i.e. looking like a new card with same content), the same card slides on from the same direction it was swiped off. For example, on the landing page, if one swipes right (there is nothing left on the left side, since it's the first card), then the card still swipes OFF to the right (this is the current behavior. But instead of sliding the same card back on from the left, the card slides BACK from the right (same side it was swiped off). This makes it look like the card is RETURNING, rather than a NEW card is coming on.

2. When this slide reversal action happens, ALSO show an alert saying: "Oops, you're already at the beginning -- Please swipe the other way! :)" (if it's the first card). If it's the last card: "Oops, you've reached the end! Please swipe the other way!"

For the style of this alert, use the style of the alert that Alison added in the comment thread below.

End ticket.
---
(The below is just being left for reference, but no longer necessary for completing the ticket)
if a user scrolls back before idea 1, currently, we just keep re-displaying the first idea. Let's improve this UX.

In this example, I swipe forward a few times then back to demonstrate that the ideas change. Then I swipe backwards 10+ times to show that the same idea is displayed repeatedly.

https://monosnap.com/file/6NRyXb1xCz0KgRQB8daorl4XCsFbuE

Alternatives:
1. Support negative indexing - if they go before the first idea, load ideas from the back of the stack
2. create a "stop" card that says: "go the other way" or something to indicate to the user they can't keep going.

Personally, I vote for #1

Related: #606

**Comment by alisonuxdesign** [comment]
This ticket relates directly to ticket #606..... I believe if we implement a "middle of the deck" starting place this will significantly mitigate this problem. 

 In the instance the user swipes backward and gets to the "first" card and then beyond then we should flip them to the back of the deck- this would also be the case for when they are in the "new" top navigation section.  in the new section by default, we need to always show them the first card in the new deck and by swiping backward (to the left) they get to the oldest card. It might be worthwhile to throw up a toast message saying "You’re seeing old ideas, swipe right to see the newest ideas." 

![toast swipe right to see new ideas](https://user-images.githubusercontent.com/63747360/96280257-fb434b80-0f94-11eb-8b04-6209d81145e5.png)

**Comment by vedmant** [comment]
@ezl There are some confusing messages, as I understand I do following:

1. When reaching end of stack animate the same card appearance from opposite direction, like it goes back from where it was swiped.
2. Add toast messages: "Oops, you're already at the beginning -- Please swipe the other way! :)" (if it's the first card). If it's the last card: "Oops, you've reached the end! Please swipe the other way!".

As I understand I disregard other suggestions in the ticket?

**Comment by vedmant** [comment]
@ezl I've completed that two points, let me know if I should do something else here

**Comment by ezl** [comment]
nothing further. just those 2 things. once you've merged this, please let me know and I'll check it on beta.
