### ISSUE TITLE
[card order] is sequence preserved on "back" actions?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#619]
I'm not sure what's going on here.

It seems that if I:
1. scroll through ideas
2. click on the username of an idea to go to the user's profile page.
3. click back

Then the displayed card on back is the idea that I originally left  in step 2 above. However, ALL the cards under it are as if the card sequence started from the beginning of the deck.

This creates unintuitive user interaction because then upon returning to the card I just left, if I go "forward" again, then I start seeing cards I've already seen.

Notice that in this video, the sequence is:
1. for file sharing...
2. let's cook...
3. scared straight program...
4. for file sharing...
5. tech support...

However, as I start clicking the username on the "for file sharing" card, whenever I hit back,
(A) it correct displays the card I navigated away from (for file sharing)
(B) BUT if I continue swiping, it seems to drop me into a previous sequence, then RE-DISPLAYS the "for file sharing" card to me.

Edit: Forgot to attach video link: https://monosnap.com/file/Jo0MRxf1zDZeJ83ir3W4A4Z2MjJlyM

**Comment by vedmant** [comment]
@ezl I'll take over this one then

**Comment by ezl** [comment]
yep, thanks @vedmant

**Comment by vedmant** [comment]
@ezl This basically done, I did a lot of refactoring, and made it use Vuex properly using all the reactive model, now it looks much better, easy to debug as all the data in Vuex now and also less code. However Explore link will not work as I removed that code, I'll fix it in this issue: #697

**Comment by ikosovec** [comment]
This looks like it's working fine now, except that it's throwing an error which is not 100% correct.
Steps to reproduce:
1. Open dailyidea.com, go to explore
2. Scroll 3 cards
3. Open a profile
4. Go back in browser
5. Go "back" on the explore part:
I will get an error like this, although I can go to the previous card:
![image](https://user-images.githubusercontent.com/16639403/99532292-59a08700-29a4-11eb-90aa-c4f277ddd6c7.png)
The error shouldn't be there, as I'm on the 3rd card and I can scroll back.

**Comment by ikosovec** [comment]
Fixed. Love it!

**Comment by ezl** [comment]
well, by the time i got to it, it looks like it was fixed! awesome work team!
