### ISSUE TITLE
Unify login and signup pages, remove duplicate code

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#62]

**Comment by patelravi** [comment]
They both are developed individually. Some of the markups and styles were reused.

**Comment by aldarund** [comment]
Greate copy paste in action https://c2n.me/44B9GWn.png https://c2n.me/44B9G5S.png
Renamed ticket

**Comment by ezl** [comment]
... exactly...

**Comment by ezl** [comment]
this is just tech debt. it's not great, but i don't care a ton about it now. leave for future.

**Comment by GildedHonour** [comment]
The pictures are no longer available. Where is the duplicated code @aldarund ?

**Comment by aldarund** [comment]
Thats not valid anymore ticket, it was quite some time ago
