### ISSUE TITLE
Errors when swiping right from index page on mobile

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#629]
https://streamable.com/ngjs3b

**Comment by vedmant** [comment]
This was happening when idea was not yet loaded and swipe explainer was swiped too fast.

**Comment by vedmant** [comment]
@ezl I also disabled explainer on SSR, otherwise it doesn't render content and search bot cant read it

**Comment by ezl** [comment]
> I also disabled explainer on SSR

@vedmant I see -- does that mean it's only disabled for search bots? or is that disabled for actual users as well?

**Comment by vedmant** [comment]
@ezl Yes, on generated on SSR html it will show actual idea, for browser when JS is run, it will show explainer card first.
