### ISSUE TITLE
Implement Darkmode designs for emails

### ISSUE THREAD

**Issue by alisonuxdesign** [ezl/dailyidea.com#633]
Please Implement dark mode designs for the rest of emails! We tested this in ticket #557 and it turned out great. So its time to do it for the rest of the emails. 

- There is a great many assets that belong to this ticket so I am going ahead and linking the figma file [here](https://www.figma.com/file/vwPwlzhQC2FrCIfdcxshm5/Daily-Idea-Mobile-Desktop?node-id=783%3A10391)

-  you need to export asset please use this guide to do so: https://www.notion.so/How-to-Access-Figma-For-Dev-0e4cf85a9034464fb5605fa17f938597

Please see the picture below for the first of the emails to be rendered, all other emails follow the exact same order. 

![Frame 5](https://user-images.githubusercontent.com/63747360/96295231-c510c680-0faa-11eb-8115-e94ee28a96af.png)

A. This instance is what the user would see in a light mode aka "Regular" email client.

B. In this instance you can see that we have "dark-mode" proofed our emails. This is the exact same email with the exact same elements as the light mode email but with al colors inverted.

C. In this email you can see that we are dictating what Dark mode renders. We have different colors in the image.

**Comment by vedmant** [comment]
@alisonuxdesign 

> you need to export asset please use this guide to do so: https://www.notion.so/How-to-Access-Figma-For-Dev-0e4cf85a9034464fb5605fa17f938597

Tried this guide, but Ctrl+C doesn't copy anything, when I try to paste it just inserts previous clipboard content.

**Comment by vedmant** [comment]
### Full list of emails:

- [x] back/users/mail-mjml/require_login_template.mjml
- [ ] back/users/mail-mjml/require_login_template_with_idea_save.mjml
- [ ] back/users/mail-mjml/require_login_template_with_comment.mjml
- [ ] back/users/mail-mjml/require_login_template_mobile.mjml
- [ ] back/users/mail-mjml/magic_link_template_with_idea_save.mjml
- [ ] back/users/mail-mjml/magic_link_template_with_comment.mjml

- [ ] back/mail-processing/mail-mjml/idea_notifications/idea_notifications.mjml
- [ ] back/mail-processing/mail-mjml/request_daily_idea/daily_idea.mjml
- [ ] back/mail-processing/mail-mjml/weekly_stats/weekly_stats.mjml

- [ ] back/mail-processing/mail_templates/request_daily_idea/daily_idea.html
- [ ] back/mail-processing/mail_templates/idea_received_confirmation/idea_received_confirmation.html

- [ ] back/appsync/functions/share_idea/share_idea.html

---

@ezl There are few emails that will require first to be converted to MJML, so I'll start from them:

### Convert to MJML:

- [ ] back/mail-processing/mail_templates/request_daily_idea/daily_idea.html
- [ ] back/mail-processing/mail_templates/idea_received_confirmation/idea_received_confirmation.html

- [ ] back/appsync/functions/share_idea/share_idea.html

**Comment by ezl** [comment]
sounds good @vedmant

**Comment by vedmant** [comment]
@alisonuxdesign Here is email we have when user saves idea: https://prnt.sc/v534lw and https://prnt.sc/v537yh couldn't find it in Figma.

**Comment by vedmant** [comment]
@alisonuxdesign Also about logo, I see we have two different logos, one for option A and B, and different one for option C, I was thinking why not to use the same logo for all 3 options, for A it will look the same as it just has white background, for B it will look like on C. And I can use the same image for all 3 then.

**Comment by vedmant** [comment]
@alisonuxdesign Could you also attach images here, I was unable to copy paste on Figma, it doesn't copy.

**Comment by vedmant** [comment]
@alisonuxdesign I also see different backgrounds on different emails in dark mode: https://prnt.sc/v541o7 I think it makes sense to have one background color for all emails?

**Comment by alisonuxdesign** [comment]
> @alisonuxdesign I also see different backgrounds on different emails in dark mode: https://prnt.sc/v541o7 I think it makes sense to have one background color for all emails?

Hey @vedmant ! Yes, it makes sense to have the same exact background, however, google or whatever email provider should actually supply that for us when they switch it over to dark mode. This is just an example of what it might look like. 

> @alisonuxdesign Could you also attach images here, I was unable to copy-paste on Figma, it doesn't copy.
I exported and zipped them here: 
[Dark mode assets.zip](https://github.com/ezl/dailyidea.com/files/5431869/Dark.mode.assets.zip)

> @alisonuxdesign Also about logo, I see we have two different logos, one for option A and B, and different one for option C, I was thinking why not to use the same logo for all 3 options, for A it will look the same as it just has white background, for B it will look like on C. And I can use the same image for all 3 then.

You are right. We want to use the same logo for all three emails. find it here: 
![daily idea logo](https://user-images.githubusercontent.com/63747360/97056222-afb91080-1545-11eb-80a7-7d39d6800d04.png)

**Comment by vedmant** [comment]
@alisonuxdesign 

> Hey @vedmant ! Yes, it makes sense to have the same exact background, however, google or whatever email provider should actually supply that for us when they switch it over to dark mode. This is just an example of what it might look like.

I mean for option C where we actually set exact color for dark emails, so I use then #170F26

**Comment by vedmant** [comment]
@alisonuxdesign I can't find this two images in "Dark mode assets.zip": https://prnt.sc/v6x9s2

**Comment by alisonuxdesign** [comment]
hey @vedmant - background #170F26 should work great. 

As for the missing assets they are here! sorry about that. : 
[Dark mode assests pt 2.zip](https://github.com/ezl/dailyidea.com/files/5439982/Dark.mode.assests.pt.2.zip)

Lastly, the daily idea email is here: https://www.figma.com/file/vwPwlzhQC2FrCIfdcxshm5/Daily-Idea-Mobile-Desktop?node-id=783%3A1514

**Comment by vedmant** [comment]
@alisonuxdesign Could you attach bigger image or SVG image for "Dark mode assests pt 2/whoohooooo/wooohoooo dark mode.png" it's too small, it's ok for mobile but it will look blurry on desktop. Generally it's better if you send all images in SVG, so I can make save in needed png size.

**Comment by vedmant** [comment]
More TODO:

- [ ] Replace back/mail-processing/static/email/images/received-email-idea/woohoooo-dark.png with bigger size

**Comment by alisonuxdesign** [comment]
hey @vedmant here are the updated images:
-Dark mode whoohooo email is svg 
-re-exported svgs without white background  

[Dark mode assests pt 2.zip](https://github.com/ezl/dailyidea.com/files/5454405/Dark.mode.assests.pt.2.zip)

and your right I missed that first comment. I don't have it designed. getting it over it you shortly

**Comment by vedmant** [comment]
@ezl @alisonuxdesign Ok, almost done, waiting on this two emails designs: https://prnt.sc/v534lw and https://prnt.sc/v537yh

**Comment by alisonuxdesign** [comment]
Saved idea design: https://www.figma.com/file/vwPwlzhQC2FrCIfdcxshm5/Daily-Idea-Mobile-Desktop?node-id=873%3A438
assets: 
[untitled folder.zip](https://github.com/ezl/dailyidea.com/files/5461519/untitled.folder.zip)
