### ISSUE TITLE
Check overwritten code after PR conflicts merge

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#634]
Following https://github.com/ezl/dailyidea.com/pull/631 conflicts merge, some latest edits could have been overwritten

**Comment by f-prime** [comment]
The important edits were not overwritten. The changes that were overwritten pertained to issues with the card sizes on mobile. I will create a new issue for this and address them there instead.

**Comment by vedmant** [comment]
@f-prime You can proceed in this ticket also.
