### ISSUE TITLE
500 errors on production pages, 404 idea created by email link

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#661]
Hi, all direct links to ideas are missing, Here is the error that I am getting(e.i., links https://www.dailyidea.com/i/61hvhg/business-idea-for-restaurants, https://www.dailyidea.com/i/eclu5f/patching):

![image (8)](https://user-images.githubusercontent.com/5052406/97318107-30447d80-1874-11eb-8565-0ac5ed346f7d.png)

I also tried to share the idea with my own email and links to view the post is broken.

![image (6)](https://user-images.githubusercontent.com/5052406/97318142-3a667c00-1874-11eb-9b41-bc81a1e347cf.png)
![image (7)](https://user-images.githubusercontent.com/5052406/97318149-3cc8d600-1874-11eb-8fa5-797a57082b8e.png)
![image (8)](https://user-images.githubusercontent.com/5052406/97318161-3e929980-1874-11eb-9274-a9dcb2560369.png)

**Comment by ikosovec** [comment]
This is still happening. I just shared an idea via email and got a 404: https://beta.dailyidea.com/ideas/adef1c4a-c5ca-4177-9fc4-9d0a9961a622/87f8eb76-18cd-4f29-9ca0-8098390f6135

**Comment by vedmant** [comment]
@ikosovec Should be fixed now, last time it was different template fixed, notification about idea crating from email.

**Comment by ikosovec** [comment]
Tried sharing a random Idea to my email, got the email but the content is being sent to the beta prefix again: https://beta.dailyidea.com/i/03rt1i/digitally-archived-tv-so-i-can-rewatch-tv-like-it-was-in-the-90s-2000s

**Comment by vedmant** [comment]
@ikosovec I didn't test it on production, yeas I see it points to beta site, but URL is fixed, probably when you tested it was not published to production. Fixing domain url now.

**Comment by vedmant** [comment]
@ikosovec Should be fixed, one env variable was missing in Wercker.

**Comment by ikosovec** [comment]
Works like a charm. Thanks.
