### ISSUE TITLE
[profile page, desktop view] add whitespace between idea cards

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#671]
# problem

on settings/profile page, on *desktop* only, these cards are touching. they should have some whitespace between them.

<img width="493" alt="Daily Idea 2020-10-31 12-18-57" src="https://user-images.githubusercontent.com/157627/97785489-5c614680-1b73-11eb-992d-f8fadc93da64.png">

Note that in the mobile view, there IS appropriate whitespace between them.

Do not change the mobile view, but add whitespace to the desktop view.

**Comment by vedmant** [comment]
This one also was fixed by #687
