### ISSUE TITLE
Update welcome card with design and image

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#672]
Currently, the welcome card looks like this, including text that just says "image here".

![IMG_6810](https://user-images.githubusercontent.com/157627/97785568-c974dc00-1b73-11eb-9a3a-dbcd711fdff1.PNG)

**Comment by ezl** [comment]
@vedmant this needs an image -- @watson is going to add animated images and update the copy for mobile and desktop

**Comment by vedmant** [comment]
@ezl This is a bit confusing for me now.

- On the desktop this looks like an idea card with comments, but as we discussed before it's harder to do actual idea as a welcome card, so we use a hardcoded layout without comments or idea elements, so design needs to be updated to make it not an idea card but just info card with no comments or action buttons.

- On mobile I see this looks like a separate slider with multiple slides (more like on the front page), which is different functionality from what we have now and from the desktop version.

So this is quite confusing and needs more explanation and additional ticket(s).

**Comment by ezl** [comment]
@vedmant to complete this ticket:

1. Make "Welcome To Daily Idea" text appear bold
2. Insert an actual image in place of the "Image here" text using animated images from https://github.com/ezl/dailyidea.com/issues/723
-> on wide viewports, use the image of the keyboard arrow pad with animations for both directions
-> on narrow viewports, use image of swiping with animations for both directions

You can ignore all the parts in the design for like/comment/save, author, posted time

@Watson-B can you update the figma file so the welcome card is NOT like an idea? It should just be an explainer card with at title and the image (i.e. no actions bar, no author, no posted time)

**Comment by Watson-B** [comment]
Is this what you're picturing @ezl 
<img width="1440" alt="desktop" src="https://user-images.githubusercontent.com/65913664/99855405-abc7e080-2b3b-11eb-8c89-e956122bd03e.png">
<img width="415" alt="mobile" src="https://user-images.githubusercontent.com/65913664/99855409-ac607700-2b3b-11eb-8ece-29d5415a0399.png">

**Comment by vedmant** [comment]
@Watson-B Can you attach this images in SVG (if not animated) or required size in pixels x2 if gif.

**Comment by Watson-B** [comment]
Here are the gifs @ 2x pixels
![landingCard_keyboard](https://user-images.githubusercontent.com/65913664/100005838-6d6e3380-2d7e-11eb-8bb5-34e27512be28.gif)
![landingCard_swipe](https://user-images.githubusercontent.com/65913664/100005842-6e06ca00-2d7e-11eb-813d-dfd32405c4ba.gif)

**Comment by ikosovec** [comment]
I think this is fine now. What do you think @ezl ?
Can we close this ticket?

**Comment by ezl** [comment]
agreed, @ikosovec - this is complete. I am closing this ticket.
