### ISSUE TITLE
Still not getting card heights right

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#673]
Where: (A) landing page (B) idea cards 

(Unclear to me if these are the same code or different code)

<img width="521" alt="card and background error" src="https://user-images.githubusercontent.com/157627/97785728-d0501e80-1b74-11eb-9f76-9896fcac5acb.png">

Examples:
https://beta.dailyidea.com/i/lj6q93/test-idea?category=top

<img width="224" alt="card height" src="https://user-images.githubusercontent.com/157627/97785725-ccbc9780-1b74-11eb-9855-c9cc7611d7d3.png">

**Comment by vedmant** [comment]
@ezl This all if very weirdly done, I need to redo components inside card to make it work properly.
