### ISSUE TITLE
[settings] add whitespace around follow button

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#675]
In 2 cases (maybe unrelated).

1. On wide viewports, when the follow button is in the content, it has no space between the button and the name.

<img width="273" alt="whitespace" src="https://user-images.githubusercontent.com/157627/97786167-c54abd80-1b77-11eb-8b72-d195b3d1717e.png">

2. On very narrow viewports, when the follow button is in the topnav, there is no whitespace above/below the button. (this is only on the narrowest viewports (probably xs), but at slightly wider viewports (probably sm), it seems to be fine.

<img width="169" alt="Image from iOS png 2020-10-31 12-51-52" src="https://user-images.githubusercontent.com/157627/97786184-ec08f400-1b77-11eb-9a76-603a356971c3.png">

**Comment by vedmant** [comment]
I added left margin to desktop buttons, but on mobile view I see margins already: https://prnt.sc/vhuqkx so nothing to change

**Comment by ikosovec** [comment]
This looks fine on mobile from my perspective, but it broke the desktop design.
I'll open a separate ticket for this.
