### ISSUE TITLE
After mobile login success, direct to ideas page

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#677]
Currently, after successfully authenticating on the mobile login flow (with the 4 numbers), the user is directed to https://www.dailyidea.com/ideas/all, which is a blank page.

Instead, after login success, direct the user to the ideas page (same as what happens after successful email click through authentication on a desktop device).

If possible, make it so both of these methods use the same code to determine what happens after successful authentication.

**Comment by ikosovec** [comment]
Tested on Galaxy Note10+, Google Chrome.
This is fixed.
