### ISSUE TITLE
#11 individual idea page: Should we escape content before saving? (whether from email or from web app)

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#68]

**Comment by aldarund** [comment]
It was created from mail? html?

**Comment by ezl** [comment]
Yes, this was created from email. 

I renamed the ticket to address this as a question of whether we need to escape content

**Comment by aldarund** [comment]
from web fully implemented e.g. html sanitization

**Comment by ezl** [comment]
got it. what are your thoughts regarding email sanitation?

(A) do we need to do it?
(B) is it possible to do things like remove signatures?
