### ISSUE TITLE
[profile page, desktop] only display "Read More" when content overflows

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#681]
Currently, in some cases on desktop, the "Read more..." text is displayed on ALL cards, in preview AND in full card display mode, even when full text is already visible.

This should only be displayed in cases when the full card text is not visible. (i.e. there is y-overflow)

**Comment by vedmant** [comment]
@ezl Actually I fixed this together with https://github.com/ezl/dailyidea.com/pull/688

**Comment by ezl** [comment]
perfect. closing since you've already fixed it.
