### ISSUE TITLE
[landing page] Copy: Change swipe direction message

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#682]
1. On MOBILE this copy should say "Swipe left to see the next idea". Also reverse the arrow on the image. (currently it says swipe *right* - this is incorrect)

2. On DESKTOP, change the messaging and icon. Messaging should say "Use arrow keys to see the next idea". (for now, use the same icon, but will change this for desktop later)

**Comment by vedmant** [comment]
@ezl @alisonuxdesign I updated text but, I'll need reversed icon and also new icon for desktop to complete this task.

**Comment by ezl** [comment]
@vedmant - Attached:

1. reversed icon, `swipeLeft.svg` (for mobile)
2. keyboard icon, `pressRightArrow.svg` (for desktop)

Zipped because github doesn't support uploading svgs apparently.

[Archive.zip](https://github.com/ezl/dailyidea.com/files/5478242/Archive.zip)

**Comment by vedmant** [comment]
@ezl There is also another image when on slide 2+, it shows swipe both directions, but probably we need something else for desktop https://prnt.sc/vceu9c

**Comment by ezl** [comment]
@vedmant - Added image for desktop
[pressBothArrows.svg.zip](https://github.com/ezl/dailyidea.com/files/5482097/pressBothArrows.svg.zip)
