### ISSUE TITLE
bug:fix layout on desktop - don't use multiple columns

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#689]
seems to be a weird 4 column layout bug compressing large texts on desktop view

Example:
https://www.dailyidea.com/i/3dgdlr/better-airbnb-chrome-extension

Screenshot:
https://monosnap.com/file/6xbWllbhbHxE7RhUs7JlZQIkXjPggc

**Comment by vedmant** [comment]
Duplicate on #690
