### ISSUE TITLE
bug: only use one column on desktop single idea view

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#690]
seems to be a weird 4 column layout bug compressing large texts on desktop view

Example:
https://www.dailyidea.com/i/3dgdlr/better-airbnb-chrome-extension

Screenshot:
https://monosnap.com/file/6xbWllbhbHxE7RhUs7JlZQIkXjPggc

(edit: appears to also happen on mobile)

**Comment by vedmant** [comment]
@ezl looks like duplicate of #689 ?

**Comment by ezl** [comment]
oops, yes, was duplicate. when i created the ticket, github gave an error, so i didn't realize it had been created. 😇
