### ISSUE TITLE
bug: Fix individual idea loading

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#692]
Individual ideas not loading when accessed directly.

Example:
https://www.dailyidea.com/i/noo1mo/a-dating-app-without-pictures?category=top

They work if you start at "explore" then paginate to it, but not if loaded directly.

@vedmant says it's "something connected with server render"

**Comment by vedmant** [comment]
@ezl  The error is: `DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`
very cryptic. I'll try to disable some components to see which one causes this, but it takes time cause I need to rebuild every time, it only errors on build version. @aldarund maybe you can know what causes this kind of error?

**Comment by vedmant** [comment]
Really weird thing, it works if I comment out `<idea-comments>`:

    <v-col v-if="!preview && expanded" cols="12" md="4" class="fill-height">
      
    </v-col>

It fails if I keep it even fully empty component, with no props:

    <v-col v-if="!preview && expanded" cols="12" md="4" class="fill-height">
      <idea-comments></idea-comments>
    </v-col>

IdeaComments.vue

```
<template>
  <div class="comments-part d-flex flex-column fill-height"></div>
</template>

<script>
export default {}
</script>
```

**Comment by vedmant** [comment]
Ok, it works if I remove `v-if="!preview && expanded"`, but we need this condition, this looks like some bug in Vue or Nuxt, I'll try to upgrade.

**Comment by vedmant** [comment]
Ok, upgrading `@nuxtjs/vuetify` fixed, this, also upgraded nuxt
