### ISSUE TITLE
#13.  properly handle errors without tons of copy paste.

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#70]

**Comment by patelravi** [comment]
Just checked this on beta, the issue occurs when we save the idea without providing the description.

I will make the changes, but one question here @ezl , do we need to keep the idea description mandatory here?

**Comment by ezl** [comment]
1. make description not mandatory, only title (i just said this in slack too, but reiterating now)
2. overall, this is a sign too of lazy work. failing with generic errors when a clear error that the user could have used to fix the behavior

**Comment by ezl** [comment]
super old ticket, result of legacy code from ravi still. closing this ticket now and we can deal with tech debt incrementally.
