### ISSUE TITLE
bug:make long content cards accessible on desktop

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#700]
on desktop view, ideas with long content can't be viewed. the content overflows, but:
(A) clicking the card doesn't give a way to see the rest (like it does in mobile)
(B) the content doesn't scroll
(C) "read more" isn't visible

did we decide on a solution for this?

**Comment by vedmant** [comment]
@ezl Weird, for me content is scrollable and it shows Read more text http://www.giphy.com/gifs/i8dPghykr3LQ8y1uJc

**Comment by ezl** [comment]
@vedmant interesting.

I found that in chrome, it works for me as expected:
1. scrolling works
2. "read more..." is displayed when end of content isn't visible

however in firefox:
1. no scrolling
2. no "read more..."

video:
https://monosnap.com/file/z6mreKAF1NKjwmMQ2SW8RsIzZScqZw

**Comment by vedmant** [comment]
@ezl Looks like Firefox handles flex-box differently, fixed with overflow hidden.
