### ISSUE TITLE
bug:make email responses to create idea work (check why some users had unsubscribedAt Null: true)

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#704]
I responded to an email to create an idea, but it did not get posted.

```
to: | Daily Idea <ideas@mail.xxxxxx.com>
-- | --
date: | Nov 12, 2020, 7:52 AM
subject: | Re: [Daily Idea] Idea for Thu Nov 12 2020
mailed-by: | gmail.com
```

As of 8:09am still didn't get posted on the site.

Idea content contains this string: `Stretching/Flexibility Classes` (that's the first line)

Sent from my primary email address (ericzliu) to `ideas@mail.-domain-.com`.

**Comment by vedmant** [comment]
@ezl I just tried to respond to weekly digest email from "ideas@mail.dailyidea.com" and it created idea successfully, can you add here exact steps, what email you responses on so I can reproduce the bug.

**Comment by ezl** [comment]
@vedmant Interesting! I just tried again and no idea was created again.

What I did:
1. Find the most recent email in my gmail for a DAILY idea (yours was for weekly digest, but I think both are SUPPOSED to work)
2. respond to the email in gmail

https://monosnap.com/file/nJNXkS2cqj4KxR5Ix9jzB3el2SEmcQ

Nothing happens. No confirmation email, no update on site.

**Comment by vedmant** [comment]
@ezl Did exactly the same and get confirmation email https://prnt.sc/vk3ymz

**Comment by vedmant** [comment]
@ezl In scope of this ticket I can check why unsubscribedAt was Null: true in dynamodb for some users.

**Comment by ezl** [comment]
Confirmed, this works for me now.

Is there any action that needs to be taken on this to make it not happen again? If so, please ticket. If not, feel free to close this ticket.

**Comment by vedmant** [comment]
@ezl Ok, I'll create another ticket
