### ISSUE TITLE
bug: number of ideas on profile not matching

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#705]
<img width="281" alt="Daily Idea 2020-11-12 08-12-42" src="https://user-images.githubusercontent.com/157627/98950680-eb992300-24be-11eb-9f99-9b21b2674f9b.png">

Number of ideas on my profile isn't matching ^

I believe the correct number is 137, but under "my ideas" it says 24.

**Comment by vedmant** [comment]
@ezl Looks like both numbers are not really correct, I'll need to re-check backend

**Comment by vedmant** [comment]
Yeah I doesn't increment total ideas count field properly, for example it not doing it on creating idea by email. For now I fixed frontend to use user's `ideasCreated` field to show number of ideas. 

I think it should be follow up ticket to fix `ideasCreated` numbers for users (increment in idea by email), it will require to create some helper command that will run for each user and re-calculate correct totals.

**Comment by ikosovec** [comment]
This looks fixed to me now.
