### ISSUE TITLE
bug: move new/top navigation in line with page

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#707]
<img width="296" alt="margin" src="https://user-images.githubusercontent.com/157627/98960279-da094880-24c9-11eb-987b-2fdd6682951b.png">

move new/top nav inline with right margin of other content

**Comment by vedmant** [comment]
@ezl 

> inline with right margin of other content

Not sure I understood it right, I aligned it with left side of the card

**Comment by ezl** [comment]
ah got it. I described it incorrectly, but you did what i wanted. thank you! :)
