### ISSUE TITLE
design error message for reaching end of card stack

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#710]
that was implemented in https://github.com/ezl/dailyidea.com/pull/699

**Comment by Watson-B** [comment]
@ikosovec Card design for the end of a deck. Clicking the "Back to the top" button will take the user back to the first card in the stack.
<img width="1480" alt="end of stack" src="https://user-images.githubusercontent.com/65913664/112238349-b5547880-8c01-11eb-9442-4b2047bfa39f.png">

Illustration PNG
<img width="320" alt="illustration" src="https://user-images.githubusercontent.com/65913664/112238369-bd141d00-8c01-11eb-8b82-cb533ce4a721.png">

**Comment by ikosovec** [comment]
@Watson-B is this approved for development?

**Comment by ezl** [comment]
Approved!

**Comment by vedmant** [comment]
@ezl Reaching the end is so unlikely, we have 1200 ideas on prod right now, swiping them all will take like 2 hours. I can implement this page, it will take about an hour but I think actual users will never see it.

**Comment by ezl** [comment]
In the long run, there will be different sequences of cards: all, searches, for one user, etc -- so it'll make sense then. but agreed that for now it might not be visible, so let's put it on hold until we have those ideas implemented.

**Comment by vedmant** [comment]
@ezl Ok, we also have a notification when reaching end of stack (with card going back from where it swiped, the same as with first card in stack)

**Comment by ezl** [comment]
hmmm -- good point regarding the FIRST card in a stack. Given this, I need to discuss with @Watson-B.

This card as designed by @Watson-B functions as a *replacement* for the "last card" notification at the end, but it's not clear to me what we should do at the beginning. As such, this card needs further discussion before considering implementation. Will discuss with @Watson-B before we proceed.

**Comment by ezl** [comment]
@vedmant you're right -- this ticket is incomplete as it is written. @Watson-B and I have discussed and we're going back to the drawing board.

@Watson-B + @ezl - note to our future selves: There are 2 points to consider here:
(A) this won't be seen anyways until https://github.com/ezl/dailyidea.com/issues/954 is executed so there are multiple card sets (shorter ones) where users WILL actually reach the end
(B) we ALREADY have toast messages and a card swipe reversal that happens when a user reaches the begining/end of the card stack, but this ticket currently only addresses/modifies what to do on the END.

in order to be a complete ticket, we need to address both ends AND what to do with the old toast messaging and swipe patterns.

@Watson-B has proposed a "fun" idea to have a lightbulb air traffic controller character pop up and direct the user the other way.

**Comment by ezl** [comment]
related to #910 and #911

we probably need to close this one out and create a new one with the air traffic controller stuff.

**Comment by Watson-B** [comment]
Posting the solution to the beginning of stack bumper in #1030. Closing this for clarity's sake.
