### ISSUE TITLE
#16. single idea page, not authenticated: showing wrong name ("Ravi's idea"): https://beta.dailyidea.com/ideas/d28ed5ff-17b3-4888-b42f-6eb1fe011eda/fab366f5-e34d-435a-9cfb-03f8ba83214b

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#72]

**Comment by patelravi** [comment]
Api is not returning the auther's informtion, on slack, it was decided to use userInfo api for that, but userInfo api also is not returning email & name.

**Comment by aldarund** [comment]
duplicate #71

**Comment by ezl** [comment]
for authenticated user, not seeing "Ravi's Idea"
for *un*authenticated user, still seeing "Ravi's idea"
