### ISSUE TITLE
expired link page fonts are way too big

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#721]
<img width="507" alt="expired link page" src="https://user-images.githubusercontent.com/157627/99417120-cc333900-28b6-11eb-8c9b-49d3d5e4f8c7.png">

Correct size:
https://www.figma.com/file/FkptxrJSaBpU3mslMFnWm4/Daily-Idea-Mobile-Desktop-Copy?node-id=514%3A468

**Comment by vedmant** [comment]
@ezl Fixed size, but what about the font family? I see in figma that Avenir LT Std is used, but it's not integrated in the app, I see font files, but there is no styles for this fonts, it's like someone added fonts files but didn't integrate them.

**Comment by vedmant** [comment]
Also fixed cards width, created another component <card-layout> for this kind of pages that have one card in the middle.

**Comment by ikosovec** [comment]
@vedmant can you please help me with testing - how long do I have to wait for a link to expire?

**Comment by vedmant** [comment]
@ikosovec It's about a week, here is expired link: https://beta.dailyidea.com/auth/verify?code=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlZG1hbnRAZ21haWwuY29tIiwiaWF0IjoxNjAxNDc0NDA3LCJleHAiOjE2MDE0NzgwMDd9.QBRV2vpa2Wdah45KhydxNYYr3D3OI_z6-s0-QhPDQY0&email=vedmant%40gmail.com

**Comment by ikosovec** [comment]
This looks good to me now. Thanks @vedmant
