### ISSUE TITLE
Submit idea link from daily idea reminder email is already expired just 4 hours after sending

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#722]
I clicked this button in the email just 4 hours after it was sent, and was directed to a page that said it was expired:

<img width="314" alt="Daily Idea  Idea for Tue Nov 17 2020 - ericzliu@gmail com - Gmail 2020-11-17 09-25-56" src="https://user-images.githubusercontent.com/157627/99417329-0997c680-28b7-11eb-9e3b-766c7d8349c2.png">

**Comment by vedmant** [comment]
@ezl Weird I just tested 2 days ago email and it works ok, can you attach that link, I'll try to decode it

**Comment by ezl** [comment]
Fixed. was related to issue of invalid value for "unsubscribed at" field
