### ISSUE TITLE
animate left/right keypress and swipe icons

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#723]
Use these:
![keyboard_arrow_both](https://user-images.githubusercontent.com/157627/99464042-6d8cb000-28f4-11eb-97d2-93e00215ac36.gif)
![keyboard_arrow_left](https://user-images.githubusercontent.com/157627/99464046-6f567380-28f4-11eb-9155-3044efd82b7f.gif)
![keyboard_arrow_right](https://user-images.githubusercontent.com/157627/99464049-6fef0a00-28f4-11eb-9043-8d7e591d341b.gif)
![swipe_interaction_left_1](https://user-images.githubusercontent.com/157627/99464051-7087a080-28f4-11eb-8982-a65ca4fcc203.gif)
![swipe_interaction_right_1](https://user-images.githubusercontent.com/157627/99464053-71203700-28f4-11eb-9a15-2817e5cd6790.gif)
![swipe_interaction_both](https://user-images.githubusercontent.com/157627/99464055-71b8cd80-28f4-11eb-9a4c-46a71eadc519.gif)

**Comment by vedmant** [comment]
@ezl Hawing some problems with resizing and cropping this images, it's not that easy with animated gifs.
I need this sizes for images also they have to be cropped without any extra white space:

- Three keyboard buttons should be 120px width x 78px height not including animations, this is only buttons size.
- Swipe card should be 50px width x 70px height not including arrows, this is only card size (so images with arrows will be bigger, main point is that card size should stay the same).
- No extra white space around.

**Comment by ikosovec** [comment]
I'm moving this to the design project. @Watson-B is this something you can help us with, please?

**Comment by Watson-B** [comment]
@ikosovec Yeah I can re-export these. Working on it now

**Comment by Watson-B** [comment]
![keyboard_arrow_both_1](https://user-images.githubusercontent.com/65913664/99854172-2e9b6c00-2b39-11eb-94bd-52f5cf3f9a41.gif)
![keyboard_arrow_left_1](https://user-images.githubusercontent.com/65913664/99854176-2f340280-2b39-11eb-8891-eb8df0927416.gif)
![keyboard_arrow_right_1](https://user-images.githubusercontent.com/65913664/99854177-2f340280-2b39-11eb-893d-5b4c451d9c3d.gif)
![swipe_interaction_both_1](https://user-images.githubusercontent.com/65913664/99854178-2fcc9900-2b39-11eb-9291-f8c841614085.gif)
![swipe_interaction_left_2](https://user-images.githubusercontent.com/65913664/99854179-2fcc9900-2b39-11eb-8da9-f66bc6c8e4b7.gif)
![swipe_interaction_right_2](https://user-images.githubusercontent.com/65913664/99854181-30652f80-2b39-11eb-86e0-b0b15c614632.gif)

**Comment by Watson-B** [comment]
@vedmant So these should be the right size, let me know if there are other changes you need

**Comment by ikosovec** [comment]
This looks good on beta from my perspective.
