### ISSUE TITLE
As a non-registered user - the comment appears but the counter doesn't go up

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#724]
Here are the steps to reproduce this:

1. Anonymous window
2. Open dailyidea.com
3. Go to "Explore"
4. Find an idea I like
5. Write a comment
6. The comment appears visually on the idea card, but the counter doesn't go up
![image](https://user-images.githubusercontent.com/16639403/99527409-10006e00-299d-11eb-870d-05b6a3eb8820.png)

Afterwards I also get a modal asking me to confirm my email.
As a user, I might ask myself several questions:

- Was my comment posted?
- Under what name was it posted?
- If I refresh the page, the comment is gone. Is it in queue, will it get posted when I confirm my email?

I suggest we make a slight UI change, as this whole experience seems a little bit clunky. What do you think @ezl ?

**Comment by ezl** [comment]
valid bug. moving to up next.

**Comment by vedmant** [comment]
@ikosovec It doesn't actually add comment until you login, this is temporary comment, if you refresh the page comment will disappear. Comment will be added when you follow the link from email.

**Comment by ikosovec** [comment]
I think that's just a weird experience. It might be confusing.

I agree that it's not a bug @vedmant , this should be maybe reconsidered by design.
@ezl what do you think?

**Comment by ezl** [comment]
I see. I think there are probably a few different issues at play.

(A) the experience itself - I want the site to keep the current idea of NOT officially posting until the email address is confirmed.
(B) I believe we can improve the user experience through UI and language.

I propose that in this case, for a "pending" comment (i.e. it hasn't been officially posted because the user hasn't confirmed their email/comment), we:
1. add small text to the bottom of it like `(pending)` or "Will be posted once your email address is confirmed" or something.
2. use a different style to demonstrate that it is different. Perhaps a different background color or a lighter text.

@Watson-B can you create a "pending" comment style that is distinct from a posted comment?

**Comment by ezl** [comment]
@ikosovec after this, we may still have future questions around the flow that the user goes through, but we can treat that as a separate issue

**Comment by Watson-B** [comment]
@ezl Here are a couple of takes on pending comments, one with a tinted vers of the interaction color as the bg, and one that's downplayed a bit. Thoughts?
<img width="1440" alt="pendingComment_gray" src="https://user-images.githubusercontent.com/65913664/99857557-53471200-2b40-11eb-9756-45916eab61b0.png">@
<img width="415" alt="pendingComment_gray_mobile" src="https://user-images.githubusercontent.com/65913664/99857558-53dfa880-2b40-11eb-9ea2-26ca2ac11790.png">

<img width="1440" alt="pendingComment_color" src="https://user-images.githubusercontent.com/65913664/99857553-52ae7b80-2b40-11eb-8cdb-2eec1e7a4ced.png">
<img width="415" alt="pendingComment_color_mobile" src="https://user-images.githubusercontent.com/65913664/99857555-52ae7b80-2b40-11eb-97b8-e0975e5965a0.png">

**Comment by ikosovec** [comment]
I personally like the 2nd version better. What do you think @ezl?

**Comment by ezl** [comment]
agree with @ikosovec. prefer 2nd style. can we try the 2nd style and make the actual text a lighter grey also?

**Comment by Watson-B** [comment]
@ezl Samples with lighter grey
<img width="415" alt="pendingComment_gray_mobile" src="https://user-images.githubusercontent.com/65913664/100003154-79f08d00-2d7a-11eb-8289-aec024c29489.png">
<img width="1440" alt="pendingComment_color_lighterGray" src="https://user-images.githubusercontent.com/65913664/100003155-7a892380-2d7a-11eb-968c-01568cae77e7.png">

**Comment by ezl** [comment]
@ikosovec do you think this helps resolve some of the confusion via design?

**Comment by ikosovec** [comment]
@ezl @Watson-B yes, I think this is a good solution. It clearly communicates what's going on with the UX on this screen and doesn't leave any room for questions. 
"Your comment is pending" is a clear message we're sending here and the user should easily understand that this comment is not posted. 
Why is it not posted?
Becase you need to register - and this is answered in the copy.

I suggest we move forward with this.

**Comment by ikosovec** [comment]
This looks good from my perspective now.
