### ISSUE TITLE
"Others" profile page layout is off

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#725]
Figma link: https://www.figma.com/file/FkptxrJSaBpU3mslMFnWm4/Daily-Idea-Mobile-Desktop-Copy?node-id=668%3A250

Current state on https://www.dailyidea.com/profile/r-lightbulb:
![image](https://user-images.githubusercontent.com/16639403/99528764-109a0400-299f-11eb-81b8-a8b360838f30.png)

Might be related to #675

**Comment by ikosovec** [comment]
Hmm, I just opened another profile (/eric) and the layout is fine:
![image](https://user-images.githubusercontent.com/16639403/99530489-a6cf2980-29a1-11eb-8dc6-af545f856db7.png)

Maybe something on the /r-lightbulb profile is triggering the layout to go wild.

**Comment by ikosovec** [comment]
Looks good now. Thanks,

**Comment by ezl** [comment]
fixed and merged before i could get to it. perfect example of why @ikosovec has been asked to join this project.

great work @vedmant and @ikosovec
