### ISSUE TITLE
When creating an idea, the submit button is over the text styling buttons

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#726]
I'm on https://www.dailyidea.com/ideas/create

This is how it looks:
![image](https://user-images.githubusercontent.com/16639403/99529528-3ffd4080-29a0-11eb-8402-5bda503e7d04.png)

Using Google Chrome, 1920x1080
I can scroll down and it will move, but initially it's blocking the styling buttons.

**Comment by ezl** [comment]
Agreed. placement needs to be fixed. thanks for ticketing, @ikosovec

**Comment by vedmant** [comment]
@ezl @ikosovec This page is generally badly done:

<img width="792" alt="Screenshot at Nov 20 11-13-36" src="https://user-images.githubusercontent.com/5052406/99782155-744c3a80-2b21-11eb-801d-4f3e5d10787f.png">

In design it's completely different:

<img width="398" alt="Screenshot at Nov 20 11-14-11" src="https://user-images.githubusercontent.com/5052406/99782234-875f0a80-2b21-11eb-8a82-4c9454cd9b47.png">

Should we just make a proper layout according to new design instead of fixing this?

**Comment by ikosovec** [comment]
> Should we just make a proper layout according to new design instead of fixing this?
Yes, in the design it makes so much more sense - so I'd say go for it.

The current layout isn't good enough in my opinion.

**Comment by ezl** [comment]
(A) the current page in the codebase is bad (agreed w/ @vedmant )
(B) the design is also not great (agreed w/ @ikosovec)

What I would LIKE to emulate is a full screen page for entering ideas, copying grammarly.

@ikosovec can you please create an account and try creating a document on grammarly.com and see that interface.
@Watson-B can you please also try that, then model a version of our "create idea" page that looks like that (IMO, it's actually just simpler, and the dev implementation will be the tricky part)

**Comment by Watson-B** [comment]
I mocked a "Create a Post" that mimics grammarly's functionality. is this what you were picturing?
<img width="1440" alt="post_desktop" src="https://user-images.githubusercontent.com/65913664/100015436-cfce3080-2d8c-11eb-9d6f-b54aef2d3839.png">

**Comment by ezl** [comment]
@Watson-B I really like the "full screen" (not just a card) UX for creating an idea.

grammarly has that as well, which I think is great. I feel that a few sites have done this "no distractions" UX for content creation (writing blog posts, writing stories) idea really well. The "full blank page" IMO is really great for this idea of a blank canvas.

From a visual perspective, I think our full screen page is pretty close. I think the areas we mess up are that the actual typable area isn't that good and it scrolls. Instead, I wish our page scrolled more like grammarly's.

I DO like your formatting and "POST" button layout though -- i would like to keep that.

Where would those go on the mobile viewport?

**Comment by Watson-B** [comment]
Made updates to the way things scroll and changed the layout to a full screen layout. Based the width on optimal line width for legibility. 
**Default**
<img width="1480" alt="default" src="https://user-images.githubusercontent.com/65913664/100682198-691bba80-332a-11eb-8d11-5040efe77d39.png">

**Hovered**
<img width="1480" alt="hover tooltips" src="https://user-images.githubusercontent.com/65913664/100682201-6a4ce780-332a-11eb-8275-361d27a35344.png">


**Typed**
<img width="1480" alt="typed" src="https://user-images.githubusercontent.com/65913664/100682212-6d47d800-332a-11eb-9a44-6e369d23c7fe.png">


**Scrolled** The title sizes down and a gradient is introduced to fade the body text out.
<img width="1480" alt="scrolled" src="https://user-images.githubusercontent.com/65913664/100682220-7042c880-332a-11eb-98ec-4bc20ea808a3.png">


Is this closer to what you're thinking? @ezl

**Comment by ezl** [comment]
yes, this is beautiful. @ikosovec lets roll with this. tagging @vedmant -- this is an improvement on our current page.

I suspect you may think this page also needs refactoring -- my guess is that our current page structure isn't great.

**Comment by vedmant** [comment]
@Watson-B Can I find this images in figma?

**Comment by vedmant** [comment]
I refactored component a bit, updated styles, removed all extra, should be published to beta in 5 mins. @ikosovec Could you please test.

**Comment by ikosovec** [comment]
From my perspective, this looks good both on desktop and on mobile. I tested it a lot and didn't find a single thing that's not working right. Thanks for the awesome job @vedmant

**Comment by Watson-B** [comment]
@vedmant apologies for the delay, the post frames are posted to the left of the post row in this figma file https://www.figma.com/file/FkptxrJSaBpU3mslMFnWm4/Daily-Idea-Mobile-Desktop-Copy?node-id=322%3A231. I'm leaving a comment on them to help you find them.
