### ISSUE TITLE
The "Create Idea" page is not according to the design

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#727]
The design(https://www.figma.com/file/FkptxrJSaBpU3mslMFnWm4/Daily-Idea-Mobile-Desktop-Copy?node-id=326%3A386):
![image](https://user-images.githubusercontent.com/16639403/99529765-a5513180-29a0-11eb-9403-fade7487d78f.png)

Actual state:
![image](https://user-images.githubusercontent.com/16639403/99529848-c9147780-29a0-11eb-8172-5c8ccffeb68e.png)

Should we prioritize this @ezl ?

**Comment by ezl** [comment]
@ikosovec i don't want to move directly to the designed version. i think i want something in between. Will add to design kanban board to discuss with @Watson-B
