### ISSUE TITLE
Swiping ideas doesn't work on mobile

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#738]
I'm using Galaxy Note10+ and Google Chrome mobile.
Swiping ideas doesn't work - it actually does nothing. I can't switch between ideas.

**Comment by vedmant** [comment]
@ikosovec I tested it on my OnePlus 7T and on chrome mobile mode, works ok, I don't have Galaxy Note10+ to test, I'll try to run Android emulator also.

**Comment by vedmant** [comment]
Tried in emulator on Galaxy Nexus, also work ok, couldn't find Note in devices for emulator

**Comment by ikosovec** [comment]
@vedmant it works for me now. Weird, maybe it was a regression bug that got fixed in the meantime. Closing.
