### ISSUE TITLE
Make body text mandatory?

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#740]
Cards with no body text look a bit weird. Check out the screenshot:
![image](https://user-images.githubusercontent.com/16639403/99990106-b7254100-2db3-11eb-8c81-28dbaee25ccd.png)

I think we shoud consider making the body text mandatory - maybe even limit it to about 50 minimum characters.

What do you think @ezl ?

**Comment by ezl** [comment]
Prefer not to make it mandatory -- i want it to be easy to just put a quick idea down.

IMO an idea can sometimes be just a single line.
