### ISSUE TITLE
Landing page adjustments

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#741]
There's a few issues with the current landing page, and mostly they are related to the site's responsiveness.

1. If I reduce the width, a DAILYIDEA image will pop up on a smaller viewport width. Screenshot:
![image](https://user-images.githubusercontent.com/16639403/99996384-efc91880-2dbb-11eb-8f17-d4910cfeccdf.png)

2. The fonts seem a bit off on all kinds of viewports. Are they all bold? Can we maybe make a design review on that part, please @Watson-B ?

3. On smaller viewports, the content scrolls down too much.

**Comment by Watson-B** [comment]
@ikosovec The original design has all three text elements using the 45 Book weight of Avenir LT Std, which should be equivalent to 350 I think. Right now, they're all displaying for me in the 700 weight though. 
Breaking it down from the original design:
"Every Day, Log an Idea" - size: 48 px; weight: 350;
"A project, a startup idea, a work idea" [we should also be consistent here, right now the second 'a' is capitalized] & "Practice generating ideas to become an idea machine" - size: 20px; weight: 350;

**Comment by vedmant** [comment]
Yes front cards don't following design properly, I generally don't like how it's done with too much abstraction and putting text into variables, there is no need for this abstraction at all, it have to be just html. @ezl can I refactor this front cards together with fixing design?

**Comment by ezl** [comment]
Yes please, @vedmant

**Comment by vedmant** [comment]
Ok, done, I had to fit cards content into a bit smaller cards height, how it looks on my screen (MacBook 16"), generally I added flex columns to let it stretch a bit on larger screens.

**Comment by ikosovec** [comment]
This looks good to me now. You might want to double-check this as well @ezl
