### ISSUE TITLE
Make login work from "daily idea" email

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#743]
When clicking on a "Idea for <day>" email to submit your idea, the link is alreayd expired, even if it was just sent a few hours ago.

<img width="335" alt="Daily Idea  Idea for Tue Nov 24 2020 - ericzliu@gmail com - Gmail 2020-11-24 06-34-07" src="https://user-images.githubusercontent.com/157627/100101258-3a2fb100-2e1f-11eb-90ba-25fdb3497014.png">

**Comment by vedmant** [comment]
@ezl Still can't reproduce, it works when I test, can you send me full link, I'll decode token and check payload.

**Comment by ezl** [comment]
forwarded with notes.

**Comment by vedmant** [comment]
@ezl I see that token is correct, it has your email and expiration date is 2020-12-05T12:00:06.000Z this is weird that it's not working, I don't have enough experience with Cognito to debug it, I'll google and try to find something about it. Maybe @aldarund has more experience with AWS and Cognito. I noticed there is: `Account Status	Enabled / FORCE_CHANGE_PASSWORD` can that be the reason? I I'll check how status can be changed.

**Comment by vedmant** [comment]
Actually I think i found the problem, checking it

**Comment by vedmant** [comment]
@ezl Can you try now it should be fixed. But I updated secret token, so it will work on next emails from now.

**Comment by ezl** [comment]
@vedmant confirmed this now works for me. closing ticket.
