### ISSUE TITLE
Close modals with "Esc" button

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#748]
This seems like an industry standard for me. I'm that type of user who closes all of their modals by clicking the Esc button. When I can't do it on pages, I get kind of frustrated. Modals are being closed by clicking outside of the modal or the "X" in the top right. I think closing modals with Esc is a quick implementation and helps users like me.

**Comment by vedmant** [comment]
@ikosovec Ok, I added esc key to lightbox, standard vuetify dialogs already had it.

**Comment by ikosovec** [comment]
Looking good on beta!
