### ISSUE TITLE
Investigate the really long loading time on Login (production)

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#749]
For logs: Nov 25th, around 5:20 CET I tried logging in and got a loading spinner of over 45 sec.
Can we investigate why this was happening?

**Comment by vedmant** [comment]
For me it takes about 10-15 secs, still long, but this is how AWS works, graphql api responds up to 2 secs sometimes, also cognito was responding in about 3.7 seconds in total, I'n not an AWS expert to investigate why it works so slow. Maybe @aldarund has some ideas.

**Comment by ikosovec** [comment]
For me it's working much better now, I think this is related to the server issues we had the other day.
