### ISSUE TITLE
Login emails sending expired links

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#750]
I tried logging in, got the email, the link is expired:
![image](https://user-images.githubusercontent.com/16639403/100255161-7b20e600-2f43-11eb-9151-6357f89785e2.png)
The app sent me a new link, it's also expired.

**Comment by vedmant** [comment]
@ikosovec Weird, for me it works ok, can you send a link you have, that's expired

**Comment by ikosovec** [comment]
This is working fine now. As I wrote on Slack, it looks like there was a server issue in that time period with logins.
