### ISSUE TITLE
Beta is not sending login emails

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#751]
Tried logging in to beta.dailyidea.com.
Got a really long spinner like in #749 
Spinner stopped, I didn't get any success screen. In fact, nothing changed.
I didn't receive any emails after that.

**Comment by vedmant** [comment]
@ikosovec It works ok for me, does it happed every time for you?

**Comment by ikosovec** [comment]
This is working fine now. As I wrote on Slack, it looks like there was a server issue in that time period with logins.
