### ISSUE TITLE
"Sorry, we didn't find an account registered to this email." on production

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#752]
Might be connected to #749 and #750 
I am getting this error on production:
![image](https://user-images.githubusercontent.com/16639403/100255733-2f227100-2f44-11eb-8162-645f76cf9dc8.png)

I'm quite confident I have an account. I got a link for #750 10 minutes before.

**Comment by vedmant** [comment]
@ikosovec This is weird, for me login works fine, also this error should only show when it actually didn't find an email. Do you have this behaviour consistent? I just tried to login with your email and it worked ok.

**Comment by ikosovec** [comment]
This is working fine now. As I wrote on Slack, it looks like there was a server issue in that time period with logins.
