### ISSUE TITLE
The "Hooray" modal after I log in might need an UX change

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#755]
Steps:
- I'm not logged in
- I click on "Like" on an idea
- I enter my email to log in
- I get the email, confirm it
- I get to this modal (over the original idea I tried to like):
![image](https://user-images.githubusercontent.com/16639403/100542181-ee2ea300-3248-11eb-84a5-1953abb8da59.png)

In my personal opinion - this screen does not have the design guidelines applied. What do you think @ezl ?

**Comment by ezl** [comment]
Agreed, this does not follow the design style of the other emails, so we should update.

@ikosovec are you aware of where the emails are in the figma file? (basically, lets first assess whether a design EXISTS, but hasn't been implemented vs does not yet exist and needs to be created). If it doesn't exist, can you work with @Watson-B to get it made and implemented please?

**Comment by ikosovec** [comment]
Yep, I have access to all designs. I might've misunderstood something, but I thought the app has been implemented according to the design already. I'll be more cautious regarding this.
@Watson-B - I'm having a hard time finding the design for this modal in Figma, could you please give me a hand?

**Comment by Watson-B** [comment]
I looked through the design files and I can't find a design for that modal. I'm happy to mock one up, but can we discuss the choices at the bottom first? 

I think giving the user three choices might be unnecessary. If I'm understanding correctly,the goal of the modal is to show the user that even though they had to navigate to their email, we didn't lose track of the original action they were trying to make. I think there are other visual ways we can show the user that their action was taken without requiring additional interaction from them. I think adding in extra required clicks and taps can make the experience clunkier.

**Comment by ezl** [comment]
@Watson-B I agree that too many choices might be a bad idea.

what do you propose? 

I think this may also relate to the fairly long comment I made on https://github.com/ezl/dailyidea.com/issues/679 about how we should handhold and guide users down a specific path.

**Comment by ikosovec** [comment]
@Watson-B I'm not sure if this somehow slipped under the radar so I'd just like to check the status of this one.

**Comment by Watson-B** [comment]
@ikosovec I was doing some exploration on this, but haven't had the chance to debrief with @ezl on this yet. I was thinking something along the lines of this:


![2020-12-15-10-33-24](https://user-images.githubusercontent.com/65913664/102257829-18779600-3ec2-11eb-8e7f-d5403e11a901.gif)


It may be way too extra though. My thought was, that it would be something special to let them know the action wasn't lost, and be sort of like a hidden moment of joy.

**Comment by ikosovec** [comment]
That's pretty cool! :) 
Let's see what the boss @ezl says
