### ISSUE TITLE
Liking an idea while you're logged out doesn't increase the "Liked" counter

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#756]
Steps:
- I'm not logged in
- I click on "Like" on an idea
- I enter my email to log in
- I get the email, confirm it
- I get to this modal shown in #755 
- Close the modal, get back to the card I tried to like. The "liked" icon is highlighted, as if I liked it, but the counter is not increased, as seen here:
![image](https://user-images.githubusercontent.com/16639403/100542324-7f9e1500-3249-11eb-9638-83f48dd45852.png)

**Comment by ikosovec** [comment]
Clicking it again: I get an "Idea unliked" and the icon is not filled again:
![image](https://user-images.githubusercontent.com/16639403/100542357-b116e080-3249-11eb-9c68-df2d171fca74.png)

The counter goes back up when I click it:
![image](https://user-images.githubusercontent.com/16639403/100542362-bb38df00-3249-11eb-80e3-7621ebded457.png)

**Comment by ikosovec** [comment]
Tested on beta (https://beta.dailyidea.com/profile/vedmant)
Started with:
![image](https://user-images.githubusercontent.com/16639403/100788178-03f0c380-3415-11eb-9926-fa43298ba85c.png)
Clicked "Like":
![image](https://user-images.githubusercontent.com/16639403/100788213-0e12c200-3415-11eb-9263-3b04aa10c027.png)

Behaviour looks fine on the Explore page.
Started with:
![image](https://user-images.githubusercontent.com/16639403/100788281-28e53680-3415-11eb-959a-7bbbec2b5276.png)
Clicked "Like":
![image](https://user-images.githubusercontent.com/16639403/100788301-2f73ae00-3415-11eb-968b-157e417207b7.png)
This is fine.
I go back to profile after that, still liked:
![image](https://user-images.githubusercontent.com/16639403/100788353-3e5a6080-3415-11eb-8ea9-527cff58df93.png)
I "Unlike":
![image](https://user-images.githubusercontent.com/16639403/100788396-4adeb900-3415-11eb-9104-e4f7b3996342.png)
Go back to the idea on Explore:
![image](https://user-images.githubusercontent.com/16639403/100788423-54682100-3415-11eb-8bb1-a62914c68dc5.png)
Click "Like":
![image](https://user-images.githubusercontent.com/16639403/100788440-5cc05c00-3415-11eb-9b23-a08e7e7ed891.png)
Click "Unlike" afterwards:
![image](https://user-images.githubusercontent.com/16639403/100788466-65189700-3415-11eb-9018-ad362ae36893.png)

**Comment by ikosovec** [comment]
Steps:
- I go to explore - like an idea - counter goes up (OK)
- I go to profile, find the idea - the counter is correct (OK)
- I unlike the idea on the profile page - the counter goes down (OK)
- I go back to explore, find the idea - the icon is not filled (OK), and the counter is still one up, although I unliked (not OK)
- Refreshing the page reduces the counter by one, making it correct

I think there's a state saved when navigating from profile to explore and the number is not adjusted. Please check.

**Comment by vedmant** [comment]
Fixed with https://github.com/ezl/dailyidea.com/pull/781

**Comment by ikosovec** [comment]
Looks good now!
