### ISSUE TITLE
#20. share idea - add user name and recepient name?

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#76]

**Comment by patelravi** [comment]
Api is needs to be implemented to send idea email.

**Comment by patelravi** [comment]
@aldarund in design, user provides his name, friend's name and email id.

But the api is only taking email id.

**Comment by aldarund** [comment]
@ezl i dont see in mail template friend name used. where its supposed to be used?

**Comment by ezl** [comment]
in `/email_designs/share_idea.html`

the email content requires

Hi _____ (person idea is being sent to),

______ sent you an idea (person who is sending the idea).

These should be names.
