### ISSUE TITLE
Landing page cards are scrollable on some devices

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#768]
This is a weird one. @ezl is using the same screen resolution as myself:
![image](https://user-images.githubusercontent.com/16639403/100914583-8cce3480-34d3-11eb-9869-53f058030dbd.png)
You can check the behaviour of the cards on his computer here: https://monosnap.com/file/y5d0JSPRPjvGuX8vx5oRAPvRa8rLqI
We tested both on Firefox and on Chrome.

Here's how it looks on my computer (perfectly fine):
![image](https://user-images.githubusercontent.com/16639403/100914698-b38c6b00-34d3-11eb-96d4-6fb565c3046c.png)

@vedmant do you maybe know why this is happening?

**Comment by vedmant** [comment]
@ikosovec @ezl Yes, this design just don't fit in smaller screens, I added scrolling intentionally otherwise content is cut. I see only solutions is to change design, make content vertically smaller.

**Comment by vedmant** [comment]
@ikosovec Is this still relevant?

**Comment by ezl** [comment]
lets close this ticket for now. cards have changed a lot since this was created, so if it's an issue going forward, we'll recreate it later.
