### ISSUE TITLE
#21. create idea: not using most recent styled version

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#77]

**Comment by patelravi** [comment]
According to design, in mobile view "Add New Tag" button is given, how will user add tags here?
Will there be a popup? or we had implemented multiple chips input box for that.

I think the chip box is the better option since for each new tag add, user will have to make more clicks.

![image](https://user-images.githubusercontent.com/7405840/68182597-c7f3f080-ffbf-11e9-8d4b-40b2dd474989.png)


Our existing implementation:
![image](https://user-images.githubusercontent.com/7405840/68182640-ef4abd80-ffbf-11e9-9ed6-01c20300fdb7.png)

**Comment by aldarund** [comment]
@ezl can you answer ravi questions, those are valid ones? Here how we have it now https://c2n.me/44BcSrm.png

**Comment by ezl** [comment]
@aldarund --
point is to make the style look like this: https://monosnap.com/file/GArlF7jyMW6osRXBvsjzdJC90nZPHf (in DI_mobile2.xd)

Regarding how to handle tags -- no preference.. just wahtever you choose/whatever is easiest.

**Comment by aldarund** [comment]
@ezl and what to do with wysiwyg panel?

**Comment by ezl** [comment]
@aldarund for wsywig panel: toggle to hide/show

https://projects.invisionapp.com/share/9FURIEU8PAY#/screens/392654443

**Comment by ezl** [comment]
related: https://github.com/ezl/dailyidea.com/issues/124

**Comment by aldarund** [comment]
was fixed some time ago

**Comment by ezl** [comment]
@aldarund 

checked this -- not the correct version.

see the screenshot in this email thread above -- no lines, no boxes.
