### ISSUE TITLE
Redirect to "All ideas" doesn't work

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#784]
Steps:
- Not logged in, try liking a random idea
- Get email, confirm -> get redirected to the idea
- Modal of "We liked that idea for you" is opened
- At the bottom of the modal, an URL is redirecting me to check out "All ideas". The URL is: https://beta.dailyidea.com/ideas/all
- The page in question looks like this (it's empty):
![image](https://user-images.githubusercontent.com/16639403/101672538-468a4f80-3a56-11eb-850f-f09320893f7b.png)

**Comment by vedmant** [comment]
@ikosovec This is old page that's not used anymore, I'll change link in the email to http://localhost:3000/ideas-cards this page redirects to last idea
