### ISSUE TITLE
Updated welcome cards

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#787]

**Comment by Watson-B** [comment]
Redesign of the welcome cards to work on smaller screensizes without needing to scroll.

[Desktop Prototype](https://www.figma.com/proto/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=25%3A10&viewport=2788%2C-1519%2C0.4245905578136444&scaling=min-zoom)
[Mobile Prototype](https://www.figma.com/proto/DhNZp4BVEv0n6a1EUBe23P/Daily-Idea-Mobile-Prototype?node-id=4%3A440&viewport=2346%2C382%2C0.3053310513496399&scaling=min-zoom)

Desktop PNGs
<img width="1480" alt="card1" src="https://user-images.githubusercontent.com/65913664/101822029-9b24dd80-3add-11eb-850b-c956a60dd8c3.png">
<img width="1480" alt="card2" src="https://user-images.githubusercontent.com/65913664/101822033-9bbd7400-3add-11eb-878f-aa970036945d.png">
<img width="1480" alt="card3" src="https://user-images.githubusercontent.com/65913664/101822035-9c560a80-3add-11eb-81a5-c569e4fd4615.png">


Mobile PNGs
<img width="320" alt="welcome-1" src="https://user-images.githubusercontent.com/65913664/101822069-a972f980-3add-11eb-9df7-6a065a30ca4a.png">
<img width="320" alt="welcome-2" src="https://user-images.githubusercontent.com/65913664/101822071-aa0b9000-3add-11eb-8c17-436ce7f23d8c.png">
<img width="320" alt="welcome-3" src="https://user-images.githubusercontent.com/65913664/101822074-aa0b9000-3add-11eb-9cc7-8e2134dc47e9.png">

Welcome GIFs
![card-1](https://user-images.githubusercontent.com/65913664/101821976-8b0cfe00-3add-11eb-9dfc-5f9db71ca046.gif)
![card-2](https://user-images.githubusercontent.com/65913664/101821984-8cd6c180-3add-11eb-9a75-813a65d3330d.gif)
![card-3](https://user-images.githubusercontent.com/65913664/101821986-8d6f5800-3add-11eb-8199-9a6c01f0f2e9.gif)

**Comment by Watson-B** [comment]
@ezl Think these are ready to move forward?

**Comment by ezl** [comment]
ready. moving to dev.

**Comment by vedmant** [comment]
@Watson-B On desktop I see all 3 cards has image with right arrow press, is this correct?

**Comment by Watson-B** [comment]
@vedmant I'm open to doing left and right arrows on cards 2 and 3. My thought though was to keep the user focused on just one action to get through the welcome cards and onto the ideas, and so just highlighting the right arrow key. I think if we are training the user that right means next, it is implied that left means previous. Showing both left and right though is more explicit about what controls are available, so I think that makes sense too.

**Comment by vedmant** [comment]
@Watson-B Can I find this designs on figma somewhere? I'll need better understanding of elements / fonts sizes.

**Comment by Watson-B** [comment]
@vedmant posting the screens I've been working on in the "Updated Designs" page. Here's the link:
https://www.figma.com/file/FkptxrJSaBpU3mslMFnWm4/Daily-Idea-Mobile-Desktop-Copy?node-id=1121%3A0

I've been working on a separate file for prototyping reasons, and I think I copied everything over, but let me know if you're having trouble finding anything or there's a better way to organize it for you.
