### ISSUE TITLE
Active/Hover States & Transitions for "Explore" "Post" "My Ideas"

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#788]

**Comment by Watson-B** [comment]
### **Active States**
When a user first visits Daily Idea and sees the welcome cards, "Explore" does not show up as active. It's not that it's inactive either since it is still black compared to the gray of "Post" and "My Ideas". Since we are feeding them into the explore feed, is there a reason we aren't showing it active at this point? 

<img width="958" alt="inactive-welcome" src="https://user-images.githubusercontent.com/65913664/101824857-a7ab3500-3ae1-11eb-882c-bdb3ebd0e64d.png">
<img width="318" alt="inactive-welcome-1" src="https://user-images.githubusercontent.com/65913664/101824859-a843cb80-3ae1-11eb-82f7-7fa9d7e8b781.png">

Normal active for reference
![image](https://user-images.githubusercontent.com/65913664/101825061-f658cf00-3ae1-11eb-919f-efd405af0a92.png)


If the user clicks "Post" or "My Ideas", and is not logged in, the tabs do not update to show them being active. Even though, it is required for the user to be logged in to complete these actions, I think it is worth it to show the tabs updating to active to immediately convey that the user's intended action was registered. As a side note, since we are going with a single email input field modal for both sign up and login, what about redesigning that card to save a click and just showing the input field from the card?

<img width="1160" alt="wrong-state" src="https://user-images.githubusercontent.com/65913664/101824874-ae39ac80-3ae1-11eb-8b5d-9ee26d64b104.png">

###  **Inconsistencies**
We have different stylings for the inactive tab. When I'm logged out, the inactive state is gray, whereas when I'm logged in the inactive state is black. I think we should unify this to one style, I'm leaning towards the gray inactive state to make it recede in visual hierarchy, but I'm open to the other.
<img width="1165" alt="inconsistent inactive colors" src="https://user-images.githubusercontent.com/65913664/101825412-6cf5cc80-3ae2-11eb-9488-c22fe92b83a1.png">
<img width="935" alt="inconsistent inactive colors-1" src="https://user-images.githubusercontent.com/65913664/101825417-6cf5cc80-3ae2-11eb-8700-1797be25b1f8.png">


### **Hover + Transitions**
We currently don't have a styled focused/hover state for the top nav. When tabbing through the page, you get the following: 
<img width="610" alt="focused" src="https://user-images.githubusercontent.com/65913664/101826379-c4486c80-3ae3-11eb-8a74-c2297f440545.png">
I think we can improve the feel of the site with some small tweaks that help the visuals mirror the UX changes that are improving how seamless and smooth the platform is. (apologies - a bit of dead time at the beginning of the gif)
![tab-transition](https://user-images.githubusercontent.com/65913664/101827452-32d9fa00-3ae5-11eb-9084-b7487047dc4b.gif)

**Comment by Watson-B** [comment]
@ezl pinging you for thoughts/feedback on this.

**Comment by ezl** [comment]
@Watson-B I like this a lot. However, I'm not sure how easy it is to implement.

Overall my opinion on this is that if we can implement it with relatively low effort, let's do it. If not, let's skip it.

@vedmant can you provide a difficulty estimate for this? What's your best estimate for # of hours to implement?

**Comment by ezl** [comment]
@vedmant, IMO the thing I'm not sure about is whether we can have the yellow underlining bar slide BETWEEN these elements. However, one way we might be able to do something that achieves the same goals is to just have css transitions where the line *disappears by shrinking* from the deslected link and *appears by growing from zero to full length* in the new selected link.

This won't have the same effect as sliding between the elements, but it does achieve the visual callout that indicates a shift from one item to another.

@Watson-B would that work?

**Comment by Watson-B** [comment]
@ezl Yeah, I think that's a great solution that accomplishes the same goal.

**Comment by ezl** [comment]
ok.

@vedmant so the decision on this ticket is:

(A) if you believe you can make the bar slide BETWEEN the menu options as indicated in the original animation by @Watson-B, then this is the first choice
(B) if not, or if you think it's excessively complex, then the second choice is to use CSS transform to make the underline show and hide, like in this: https://medium.com/front-end-weekly/creating-a-awesome-underline-text-effect-in-css-fbb1e677ff1d

**Comment by vedmant** [comment]
@ezl I can make a moving bar, the only problem is that whole page changes, also we have whole screen animation, so sliding bar will just not be visible or animation can be reset when whole page is re-rendered (I need to check this).

**Comment by ezl** [comment]
lets go for that. let's make it move on hover instead of click for now and see if that's enough to trick @Watson-B 😉

**Comment by ikosovec** [comment]
@ezl should we prioritize this for development? It's in the "maybe" column, so I was thinking about moving it to "up next".

**Comment by ezl** [comment]
yep! thanks @ikosovec

**Comment by vedmant** [comment]
Noticed that links have a bit different height, it's visible with sliding underline, not sure if this is important to fix.

**Comment by ezl** [comment]
@vedmant I'm not sure what you're referring to regarding different heights -- I checked and the links appear to be the same height for me.

Also, I really like the actual sliding!!! @Watson-B check out the sliding behavior on beta.dailyidea!

@vedmant I'll close this issue and create 2 new, separate issues:

1. about link heights (what you referenced, but I don't understand)
2. extending this sliding behavior to other places with menus
