### ISSUE TITLE
Mobile Card Swipe

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#789]

**Comment by Watson-B** [comment]
When swiping through ideas on mobile, if you lift your finger early, the card stops moving but still transitions to the next card. This creates jerky/stuttery experience when browsing on mobile. Is it possible to have the swipe animation finish regardless of where you lift your finger during the swipe animation? Not sure if I'm explaining that correctly; I'm attaching a GIF with me swiping through and lifting my finger at different points to highlight what I'm talking about.
![mobile-swipe](https://user-images.githubusercontent.com/65913664/101838418-6a50a280-3af5-11eb-9c6a-6ba854a15b2a.gif)

**Comment by ezl** [comment]
@Watson-B I see what you're saying.

@vedmant  + @ikosovec do you also understand?

@vedmant I believe in the past we actually animated the card swiping off the screen if the next/previous action was toggled. Can we reinstate that?

**Comment by ikosovec** [comment]
Yep, I think I got it. 
Up to @vedmant now to check if we can somehow improve this part.

**Comment by vedmant** [comment]
@ikosovec As I understand this is about card freezing and not animating away?

**Comment by vedmant** [comment]
I added a fix, it was a typo in variable name.

**Comment by Watson-B** [comment]
The new swipe feels great!

**Comment by ezl** [comment]
thank you all! @vedmant for fixing it quickly, @Watson-B for being detail oriented and find it, and @ikosovec for being on the ball and taking over this :)
