### ISSUE TITLE
Changing all "Sign up" & "Login" flows to the easy "Take me to Gmail" style

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#791]

**Comment by Watson-B** [comment]
We talked last week about changing all instances where an unauthorized user takes an action that requires authentication to the simple login flow that does the work for the user. I was thinking about it in regards to the card we currently show users when they visit "Post" and "My Ideas" that prompts them to "Sign Up" or "Log In". 

<img width="1160" alt="current" src="https://user-images.githubusercontent.com/65913664/101839750-c61c2b00-3af7-11eb-830d-173f01c9571d.png">

What if rather than giving them a choice and requiring them to click, we show the input field on the card or instantly open the email input modal instead. 

<img width="1480" alt="post-card" src="https://user-images.githubusercontent.com/65913664/101839768-ce746600-3af7-11eb-8221-b6fce9d1a8f3.png">
<img width="1480" alt="post-modal" src="https://user-images.githubusercontent.com/65913664/101839771-cfa59300-3af7-11eb-82ba-b9f86f0acf40.png">


Then after they've submitted their email, we show them the "Take me to my inbox button"

<img width="1480" alt="post-modal-confirm" src="https://user-images.githubusercontent.com/65913664/101839778-d46a4700-3af7-11eb-9c02-3b8b8b605eee.png">

**Comment by Watson-B** [comment]
@ezl Is this in line with what you were thinking?

**Comment by ezl** [comment]
@Watson-B let's discuss this in our weekly sync :)

**Comment by ezl** [comment]
@Watson-B we discussed this -- any further input needed from me at this time?

**Comment by Watson-B** [comment]
@ezl No, did the audit of messaging across all actions, just need to finish it. Should have it done tomorrow.

**Comment by Watson-B** [comment]
@ezl After our last conversation, I refined the flows and placed them in a flow chart. Let me know what you think. https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A1292

**Comment by ezl** [comment]
Just leaving a note so everyone knows that @Watson-B and I are actively discussing this issue as of Jan 6. 

For now, please leave this issue open, but we may amend/update and create other tickets related to this shortly.

If this is not resolved (new issues created and this one closed OR clear directive given on this issue) by Jan 13, feel free to ping me again.

**Comment by ezl** [comment]
closing. after discussion with ~w and ~i, no need for this issue anymore as it will be addressed by other issues.
