### ISSUE TITLE
The "Make idea private" flow is buggy

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#793]
Steps:
- Log in, go to my profile
- Select an idea, click on "Make Private"
- Visually, nothing changes. Afterwards, we get 2 bugs:
1. I can click on "Make Private" again. 
2. I can share the idea, although I clicked on "Make private". Sharing via email - I will not receive the email. Sharing via link - I'll get a 404.

Refreshing the page fixes the problem. I can "Make idea public" and the "share" icon is disabled.

**Comment by vedmant** [comment]
Fixed, there is one more thing, in explore page menu dropdown is not updated when visibility changed.

**Comment by ikosovec** [comment]
Okay, it looks fine while in profile. Please let me know when you fix it on the explore page as well.

**Comment by vedmant** [comment]
Merged a workaround, it's some weird bug with computed property not updating
