### ISSUE TITLE
The "private idea" concept is confusing for me

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#794]
Basically if it weren't for #775 , I wouldn't know that we have this feature. So I decided to play around a bit. Here's a few questions that popped onto my mind.

1) First of all, I tried creating a private idea. There's currently no option to do that. I knew that there was a "private idea" functionality, but I expected it to be available to me during the creation of the idea. Maybe we should make it possible to select a private idea option while creating the idea?

2) Next coming up, I went to my profile and expected I can make the idea private then. Other than the disabled "share" icon, I do not know what idea is private or not. Maybe we should consider adding an indicator that it's private.
 The flow is buggy so I opened a ticket here: #793 

@ezl @Watson-B

**Comment by Watson-B** [comment]
@ikosovec I agree, this was something that I was working on with the desktop prototype.
I came up with a toggle during the post creation. I have a screenshot down below.
<img width="1480" alt="post" src="https://user-images.githubusercontent.com/65913664/101947174-df2ee580-3ba4-11eb-9b6c-b5321b54d550.png">

If you go to the "Post" tab on the [the prototype](https://www.figma.com/proto/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=25%3A10&viewport=2831%2C-1443%2C0.4385293424129486&scaling=min-zoom), you can click on it to see it in action.

I haven't had a chance to talk to @ezl about this yet, so not sure if he likes this direction.

I'll work on an indicator to show if ideas are private or not.

**Comment by ikosovec** [comment]
I really like the proposal @Watson-B, I'm looking forward to seeing the indicator as well.

**Comment by ezl** [comment]
@ikosovec I'm good with this -- lets put this in for implementation

@Watson-B lets sync up on this when we chat -- will schedule a time with you.

**Comment by ikosovec** [comment]
Moving the first part to development.
Waiting for the indicator from 2nd part.

**Comment by Watson-B** [comment]
@ikosovec What do you think about this? Reusing the pill from the pending comment design, and just adding the no-visibility icon.

<img width="1480" alt="private" src="https://user-images.githubusercontent.com/65913664/102260874-c173c000-3ec5-11eb-9dd4-da2365531581.png">

**Comment by vedmant** [comment]
I'll work on create post page private switch, I'll need to make container wider then. Also editor buttons may not fit on mobile, and I don't have much control, they are part of the editor, I can only apply CSS.

About private label lets create a new issue for that?

**Comment by vedmant** [comment]
@Watson-B There is no this kind switch you added on the image, Vuetify has following switches https://vuetifyjs.com/en/components/switches/ creating something like custom like you added will take additional time. Not sure how it's important to use that specific switch, if not I'd suggest to use switch from Vuetify.

**Comment by vedmant** [comment]
I'll use this layout on mobile https://prnt.sc/w40z3f

**Comment by vedmant** [comment]
Added switch, merged to dev

**Comment by Watson-B** [comment]
@vedmant That makes sense, it was just something I was working on while doing some exploration. I don't think the styling of the switch is critical, it's more just something that is nice to have, so I think the vuetify switches will work. 

Re: mobile, I think the formatting buttons being grouped so closely together might make them hard to hit, is it possible to break up the post button and the formatting options. Something like this?
<img width="320" alt="welcome-3" src="https://user-images.githubusercontent.com/65913664/102386472-f5adb600-3f83-11eb-877d-f7d30476dbcc.png">

**Comment by ikosovec** [comment]
> @ikosovec What do you think about this? Reusing the pill from the pending comment design, and just adding the no-visibility icon.
> 
> <img alt="private" width="1480" src="https://user-images.githubusercontent.com/65913664/102260874-c173c000-3ec5-11eb-9dd4-da2365531581.png">

This is pretty cool. It also uses UI elements that we already have so that's an extra as well. 
@ezl what do you think?

**Comment by vedmant** [comment]
@Watson-B 

> Re: mobile, I think the formatting buttons being grouped so closely together might make them hard to hit, is it possible to break up the post button and the formatting options. Something like this?

Sure, could you create a separate ticket for this

**Comment by Watson-B** [comment]
@ikosovec @vedman I talked with @ezl about this yesterday, and he brought up a good point, that public/private might not be clear to users. Is it possible to have a tooltip for the toggle that changes?

![private_public_toggle](https://user-images.githubusercontent.com/65913664/102656134-4100c980-4128-11eb-9c1c-03c8fd250ebc.gif)

Either that or maybe adding an info icon:
![private_public_toggle_info](https://user-images.githubusercontent.com/65913664/102659204-e23e4e80-412d-11eb-8182-17c4f9a1040d.gif)

Heads up, currently the text "private" does not change when the toggle is clicked, it says private for both active and inactive.
<img width="596" alt="current-1" src="https://user-images.githubusercontent.com/65913664/102659288-039f3a80-412e-11eb-9337-8a2a2304c37d.png">
<img width="86" alt="current-2" src="https://user-images.githubusercontent.com/65913664/102659289-0437d100-412e-11eb-8cd5-77982a0efbc9.png">

I know this is a down the road item, but took a first stab at the modal for when private ideas are a paid feature. 
<img width="1480" alt="private_paid_modal" src="https://user-images.githubusercontent.com/65913664/102659341-1b76be80-412e-11eb-99e8-bb4d46fe75ab.png">

**Comment by vedmant** [comment]
@Watson-B 

> Heads up, currently the text "private" does not change when the toggle is clicked, it says private for both active and inactive.

Yes, it was not intended to change.

Ok, so what's left in this task?

As understand, add a tooltip, make label show private / public. Dialog?

@ikosovec Could we split this things into separate tasks?

**Comment by ikosovec** [comment]
> @ikosovec Could we split this things into separate tasks?
Ofcourse!
Tooltip: #813 
Label: #814
Dialogue (in Icebox for now, not a priority): #815

Do we need any more tickets? Was this mobile layout comment fixed @vedmant ? https://github.com/ezl/dailyidea.com/issues/794#issuecomment-748163660

**Comment by vedmant** [comment]
This should be done I think
