### ISSUE TITLE
Issue after deleting idea

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#803]
I spotted buggy behavior after deleting idea, it redirect to old page, also doesn't remove idea from cached ideas.

**Comment by ikosovec** [comment]
This works when I go to my profile, pick a random idea (don't open it!) -> click on 3 dots -> click on "delete idea" -> confirm

If I open the idea first (open the idea modal), behaviour like described in #824 appears.
When I confirm deletion after #824 , the page does not refresh.

**Comment by vedmant** [comment]
@ikosovec I see, thanks
