### ISSUE TITLE
Updating layout for Post Formatting Buttons on mobile

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#805]
@vedmant @ikosovec Creating a ticket to update the layout for the post-formatting buttons on mobile from the current layout to the following:
<img width="320" alt="welcome-3" src="https://user-images.githubusercontent.com/65913664/102647032-f37d6000-4119-11eb-86ba-e0f83c2d5596.png">
Let me know if there is anything else you need for this.

**Comment by ikosovec** [comment]
Looks good for now. Will check again when #813 gets re-implemented with a button. Closing this ticket.
