### ISSUE TITLE
Requesting Log In on Mobile > Requesting Log In on Desktop

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#806]
I encountered an issue, not quite a bug, but could be confusing for users. I had previously requested a log in while on mobile, which gave me the four digit confirmation code. Then later, I requested a log on my desktop, and clicked the take me to Gmail button. 

![image](https://user-images.githubusercontent.com/65913664/102663367-92fc1c00-4135-11eb-9dd0-4b63f618d291.png)

This takes me to the thread of emails, but shows the mobile email, its code, and the login link above the fold.

![image](https://user-images.githubusercontent.com/65913664/102663353-8c6da480-4135-11eb-8407-4ca980027358.png)

If I click the link, it takes me to the 4 digit code input; however, the code no longer allows me to login in. Which now does not work.

![image](https://user-images.githubusercontent.com/65913664/102654184-fb8ecd00-4124-11eb-81f0-1490513ab3a9.png)

The issue here is that the user needs to know to scroll to the second email in the thread to get the magic button to login. Is there a way we can direct them to the most recent email? Or have it so they aren't threaded? @ezl @ikosovec

**Comment by ezl** [comment]
Interesting. This is a really valid point.

It's definitely an unintended negative consequence of the extra complexity we added around login being different on mobile devices vs desktop (numbers vs click through).

In the long run, I think we'll have to probably think about what we want to do with auth. I think we've introduced too much complexity and I don't think we've gained anything from it.

short term:

(A) @vedmant is it possible to force gmail to NOT thread messages?
(B) @Watson-B what is the advantage of having the number thing at all instead of just making "click through" be the path for all authentication? I can't recall why this was a better choice.

**Comment by ikosovec** [comment]
> (A) @vedmant is it possible to force gmail to NOT thread messages?

I have a workaround in mind which might do the trick. It's a bit dirty, but it's the only thing coming to my mind at the moment.
Currently the title looks like this: **[Daily Idea] Log in link for ivan@expgaming.org**

Maybe we can add "mobile" and "desktop" keywords to the email title:
- [Daily Idea] Mobile log in link for ivan@expgaming.org
- [Daily Idea] Desktop log in link for ivan@expgaming.org

That way we'll get the emails threaded according to their origin, and also clearly communicate to the users what device they're logging in from. 

I know it's not the best idea, but it might do the trick. :)

**Comment by Watson-B** [comment]
@ezl The goal with the number thing for mobile was that the user would see the required code without having to tap away from the browser. 
![image](https://user-images.githubusercontent.com/65913664/102734274-4c085500-42f4-11eb-96ea-49a42938f52c.png)

In hindsight, I think you're right, it added too much complexity without enough benefit. If we consolidate to just doing a magic button would that be the easiest solution? I think there still might be a hiccup with the threaded login links, since the early links would be expired.

**Comment by vedmant** [comment]
I personally think it's much more convenient to login with social networks. Then it just takes one or two clicks to login and no need to go to email client. But this will require backend work https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social-idp.html

**Comment by ezl** [comment]
Lots of valid points all around.

(A) @Watson-B I had forgotten about that point that with email notifications, a user can log in using the numbers without leaving the app
(B) @ikosovec I agree that this will help mitigate the issue and at least thread FEWER messages than previously PLUS it will separate mobile from desktop
(C) @vedmant I agree that social login is easy

In retrospect, I think the entire auth system might need a rethink.

However, I do not have the appetite for this at this time. I really don't want to rebuild our auth at least until we have real users, so right now, I think I prefer to just put a bandaid on it until we either (A) choose to rewrite or (B) decide we're sticking with this and want to invest more.

As a result, I propose we just deprioritize this ticket, move it out of the current queue for execution, but leave it open for the future.

@Watson-B I recognize that it's an unideal interaction, but as you have alluded to, it might be a corner case. Is it ok with you if we just kick this can down the road until "real" users complain about it loudly or until we rewrite?

**Comment by Watson-B** [comment]
@ezl Yeah, I'm onboard with that. I think @ikosovec 's idea for labeling emails based on origin is a good short-term fix too. When we do look at it again, @vedmant 's call for social logins makes sense for a lot of the hiccups with the other approaches we've discussed.
