### ISSUE TITLE
A tooltip or an info icon when creating private ideas

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#813]
Origin ticket: #794 

@Watson-B's comment:
> ![private_public_toggle](https://user-images.githubusercontent.com/65913664/102656134-4100c980-4128-11eb-9c1c-03c8fd250ebc.gif)
> 
> Either that or maybe adding an info icon:
> ![private_public_toggle_info](https://user-images.githubusercontent.com/65913664/102659204-e23e4e80-412d-11eb-8182-17c4f9a1040d.gif)

We need a decision on whether we'll go with the info icon or the tooltip when hovering over the toggle control.
@Watson-B - how would the hover behave on mobile? I'm leaning towards the info icon as a better solution.

**Comment by Watson-B** [comment]
@ikosovec I agree, that seems like a good approach.

**Comment by ikosovec** [comment]
This is currently implemented as the first proposal - to make the tooltip hovering over the toggle.
As I anticipated, this does not work on mobile.

@vedmant can we please implement it according to the 2nd proposal - make an info icon instead of the tooltip showing over when hovering the toggle.

> ![private_public_toggle_info](https://user-images.githubusercontent.com/65913664/102659204-e23e4e80-412d-11eb-8182-17c4f9a1040d.gif)

**Comment by vedmant** [comment]
@Watson-B I couldn't find this in Figma, could you attach that i in circle icon in svg?

**Comment by Watson-B** [comment]
@vedmant Here you are [info.zip](https://github.com/ezl/dailyidea.com/files/5751468/info.zip)

**Comment by ikosovec** [comment]
This looks good. Also, love the micro transition on the entry of the tooltip. :)
