### ISSUE TITLE
Let unauthenticated users share an idea

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#82]
Unauthenticated share idea doesn't work -- send fails.

On Authenticated share idea, we should preopulate the user's name.

**Comment by patelravi** [comment]
APi to send email needs to be developed.

**Comment by patelravi** [comment]
@aldarund Please specify how to use the api implemented when implemented.

**Comment by ezl** [comment]
If an unauthenticated user tries to share an idea, this is what should happen:

1. same modal pops up with "share idea", asking for:
your name, your friends name, your friend's email.

2. we email your friend the same thing.

For now, that's the end of it. In the future, we streamline the send process so we can market to both parties to turn them into users and send them ideas

Future: https://github.com/ezl/dailyidea.com/issues/146

**Comment by ezl** [comment]
Unauthenticated share idea doesn't work -- send fails.

On Authenticated share idea, we should preopulate the user's name.
