### ISSUE TITLE
A quick flicker of the front page when I go to "My ideas"

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#823]
Steps:
- Logged in user
- Go to home page dailyidea.com
- Click on "My ideas"
- Between the loading state finishing and the profile page, for a brief moment we can see a flash of the homepage

Recorded a video to show it: https://monosnap.com/file/mVvbecJXRLqHJoqKvjnMPWdENq5PFZ

**Comment by vedmant** [comment]
I noticed this also, for some reason when nuxt finishes loading asyncdata it takes few moments to re-render the page, I'll check why there is a delay.

**Comment by vedmant** [comment]
@aldarund Maybe you know this issue, there is quite noticeable delay between when asyncData finished and component mounted. This causes loading screen to disappear before new page was rendered, here is the sequence:

start loading
asyncData next page
finish loading
beforeDestroy previous page
mounted next page

Delay between asyncData and mounted next page is about 1 second. Not sure what part of nuxt calls loading finish() method and when, can it call loading finish() when next page was mounted?

**Comment by vedmant** [comment]
As I quick fix I'll just add a 1 sec delay before loading screen disappears, but it's just a workaround, proper fix will be to understand why nuxt is hiding loading screen before next component mount, I can crate an issue in Nuxt repo for this.

**Comment by ikosovec** [comment]
The flicker is gone. Closing this.
