### ISSUE TITLE
Follow & Following Numbers on My Ideas Page

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#826]
@ikosovec We currently have followers and following listing on the My Ideas page, but don't have that functionality implemented yet. Can we hide these until that functionality is ready? 

![image](https://user-images.githubusercontent.com/65913664/103035643-9a983800-451c-11eb-9826-a459be519dea.png)

**Comment by ikosovec** [comment]
Moving it up on the priority list.
