### ISSUE TITLE
#27. settings pages

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#83]

**Comment by patelravi** [comment]
@aldarund  Need api to return user's name and email id to show on settings page.

**Comment by ezl** [comment]
put in stubs for what you think the functionality is supposed to be.

"Me": Name, personal info, photo (everything on the profile page).

Email: these are email toggles -- make these work

Account - this just tells if the user has a paid or free account, plus the ability to change password.

**Comment by ezl** [comment]
closing
