### ISSUE TITLE
Mobile Card iPhone X

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#835]
@ikosovec On mobile, the bottom of the card goes below the bottom nav on my (375px x 812px) iPhone X.  @ezl isn't experiencing this issue on his (320px x 568px) iPhone.

![crop1](https://user-images.githubusercontent.com/65913664/103387115-ecaa0200-4ab6-11eb-868e-71362aacbb41.png)

![crop2](https://user-images.githubusercontent.com/65913664/103387116-ecaa0200-4ab6-11eb-87d1-6ac267a9348d.png)

I don't think it's a big issue on the welcome cards, but it's the same once the user swipes to the ideas. Since the user can't scroll on those screens, and needs to tap to open the lightbox to scroll, I think showing the bottom edges of the card will help make it clear that that is the intended action.

**Comment by ikosovec** [comment]
I have moved this ticket to development, thanks @Watson-B.

@vedmant can you start your work on this - or is there any help that you might need with this ticket from the design perspective?

**Comment by vedmant** [comment]
@ikosovec I currently see that card is fully visible on iPhone X, at least in Chrome emulator, I'll try this on iOS simulator, maybe it works differently on actual device.

**Comment by vedmant** [comment]
Yeah, I see it's different in iOS, simulator, ok, I'll adjust it for simulator

**Comment by vedmant** [comment]
It's really weird, there is a huge difference between chrome emulator and actual ios https://prnt.sc/wi526w I'll adjust to ios, but it may look to small on other devices.

**Comment by vedmant** [comment]
I think it makes sense to calculate actual screen area with JS and make the card fit it. I'll try this approach.

**Comment by vedmant** [comment]
Ok, I merged solution with JS calculated heights. Generally I think the layout could be done better, I noticed things that can be improved.

**Comment by ikosovec** [comment]
@Watson-B could you please test the new behaviour on your device on the beta version of the app?

**Comment by Watson-B** [comment]
@ikosovec just tested, and it works now. @vedmant I agree, the layout can use improvements, will mocking the card layout for a range of mobile screen sizes help here? I'm working through other UI fixes right now, and can add that to my list.

**Comment by vedmant** [comment]
@Watson-B Yes at least to have mobile layout for tall and short screens will help, there can be up to 2x difference in height.

**Comment by Watson-B** [comment]
@vedmant Sounds good, I'll work on those layouts.

**Comment by Watson-B** [comment]
@ikosovec @vedmant [This Figma](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=385%3A2) page has sample layouts for iPhone SE (320 x 568), Android 5 (360 x 640), iPhone 11 Pro (375 x 812), and iPhone 11 Pro Max samples (414 x 896). Let me know if there is anything else I can do.

**Comment by vedmant** [comment]
@Watson-B Cool, no need for all the intermediate sizes, jsut smallest and largest mobile size. I just need to understand what elements are stretched.

**Comment by ikosovec** [comment]
Does this ticket need any more work @vedmant ?
If so, can we move it from "merged" to "up next"?
If everything's completed - we should move towards testing and closing it.

**Comment by vedmant** [comment]
I think this all done

**Comment by ikosovec** [comment]
Thanks! :)

@Watson-B can we get one final approval from your end before we can close this ticket?
