### ISSUE TITLE
Post Title Crops during post creation on mobile (iPhone X)

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#836]
Getting an issue where the post title crops during the post creation. @ikosovec 
![post-crop-1](https://user-images.githubusercontent.com/65913664/103444551-fa2dcc00-4c1d-11eb-8097-7fa685587483.png)
![post-crop-2](https://user-images.githubusercontent.com/65913664/103444553-fac66280-4c1d-11eb-8eac-5c60d9e8650e.png)

**Comment by vedmant** [comment]
This also happens only in actual iOS, and ok in chrome emulator.

**Comment by vedmant** [comment]
Also noticed that bottom bar and post button is not visible, I'll fix it in this ticket.

**Comment by ikosovec** [comment]
@Watson-B could you also please test this one out, since it's also iPhone X related?

**Comment by Watson-B** [comment]
Looks great @vedmant ! 
<img width="351" alt="IMG-9765" src="https://user-images.githubusercontent.com/65913664/104047445-81d38780-5196-11eb-9cca-592929ce968e.png">
<img width="351" alt="IMG-9766" src="https://user-images.githubusercontent.com/65913664/104047448-826c1e00-5196-11eb-8d22-dd1e891b482f.png">
<img width="352" alt="IMG-9767" src="https://user-images.githubusercontent.com/65913664/104047449-826c1e00-5196-11eb-9acd-6cb21fc19208.png">
