### ISSUE TITLE
My profile page on beta gives me a 404

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#839]
So I was trying to access my profile (https://beta.dailyidea.com/profile/Ivan) and I get a 404.

Could we investigate why this is happening please?

**Comment by vedmant** [comment]
@ikosovec I see that you typed Ivan with capital, it works with all lower case https://beta.dailyidea.com/profile/ivan . @ezl Should I make it case not sensitive?

**Comment by ikosovec** [comment]
@vedmant keep in mind that I did not enter this URL manually. 
I got there from here: https://beta.dailyidea.com/i/ax83di/test-idea-again?category=new
Clicking here:
![image](https://user-images.githubusercontent.com/16639403/103486424-19834f80-4dfe-11eb-9435-bcdcf36df4c6.png)

**Comment by ikosovec** [comment]
I suggest we make it non-case sensitive.

**Comment by vedmant** [comment]
@ikosovec I see, the link there uses name instead of slug, I'll fix this. Yeah makes sense to make it non case sensitive.

**Comment by vedmant** [comment]
@ikosovec Ok, done, will be deployed in 10 mins

**Comment by ikosovec** [comment]
Looks good now, thanks. :)
