### ISSUE TITLE
#28. default load 25 ideas instead of 10 on idea api (@aldarund? or better to implement this from the frontend by changing the query?)

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#84]

**Comment by patelravi** [comment]
Implemented on both public ideas and my ideas.

**Comment by aldarund** [comment]
its done

**Comment by ezl** [comment]
didn't seem done in all cases -- can you grep the codebase to look for other instances of idea api calls and make sure they are ALL 25 ideas?

**Comment by ezl** [comment]
@aldarund

**Comment by aldarund** [comment]
done again
