### ISSUE TITLE
What should happen when we click on the Comment button on a private idea?

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#844]
Currently clicking on the Comment button of a private idea is throwing a 404. 
We probably need a better solution.

**Comment by Watson-B** [comment]
![image](https://user-images.githubusercontent.com/65913664/109086522-91fce300-76c0-11eb-8afb-14d949d69d91.png)
Can you clarify @ikosovec? I think I'm misunderstanding the problem. I tried clicking the comment icon in the action bar when looking at My Ideas and leaving a comment once the idea was opened, both worked.

**Comment by ikosovec** [comment]
Looks like this has been fixed in the meantime. I'm closing this ticket.
