### ISSUE TITLE
Make links have the same height

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#846]
Created this new ticket based on @vedmant's comment on #788 regarding links having different heights.

> Noticed that links have a bit different height, it's visible with sliding underline, not sure if this is important to fix.
> 
> _Originally posted by @vedmant in https://github.com/ezl/dailyidea.com/issues/788#issuecomment-755295821_

I (@ezl) was not able to observe this issue, but just created this ticket for us to follow up. @vedmant, can you screenshot what you are referring to please?

**Comment by vedmant** [comment]
This is what I mean about heights:

<img width="376" alt="Screenshot at Jan 07 13-20-07" src="https://user-images.githubusercontent.com/5052406/103887045-213b4080-50eb-11eb-8aec-984a07b40c72.png">
<img width="259" alt="Screenshot at Jan 07 13-20-29" src="https://user-images.githubusercontent.com/5052406/103887052-23050400-50eb-11eb-80b4-bee245740245.png">

65px vs 62px and sliding line also moved vertically a bit between this two items

**Comment by ezl** [comment]
I see this height difference too now.

IMO, I couldn't even detect this.

If it's a quick fix (30 min or less), just do it please.  If not, let's just put this in the backlog, and resolve it later when other tickets are done.
