### ISSUE TITLE
Extend underline sliding behavior for menu options in navigation

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#847]
Really like the work on the main nav sliding bar that was done here:
https://github.com/ezl/dailyidea.com/issues/788

@Watson-B should we extend this behavior to other menus as well?

1. Settings page menu options
<img width="946" alt="image" src="https://user-images.githubusercontent.com/157627/103818537-55046080-502e-11eb-85b5-15d92f086b2f.png">

2. New / Top subnavigation in "Explore"
<img width="627" alt="image" src="https://user-images.githubusercontent.com/157627/103818605-782f1000-502e-11eb-9914-4ab30f107c5a.png">

**Comment by Watson-B** [comment]
@ezl if it's not too much work, yeah I think it would make for a more cohesive experience.

**Comment by ezl** [comment]
ok sounds good. @vedmant can we refactor to make it so all our menus behave in the same way?

**Comment by vedmant** [comment]
@ezl Sure, I'll probably make a single wrapper component for this.

**Comment by ezl** [comment]
lovely. let's do it. :)

**Comment by ikosovec** [comment]
This looks good to me.
@ezl if you want you can also check and confirm it. I'm closing this ticket.
