### ISSUE TITLE
create a way to indicate that an idea is private in your own personal idea list

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#849]
right now, you can tell because the share button is disabled, but i think we should make it more obvious.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/157627/103819562-4a4acb00-5030-11eb-8632-0a4260abe41d.png">

(the second one is private)

cc @Watson-B

**Comment by Watson-B** [comment]
![private](https://user-images.githubusercontent.com/65913664/103827995-07d4be80-502f-11eb-8b75-bb3002f8e38f.png)
@ezl thoughts? Reuses the pending comment ui

**Comment by ezl** [comment]
looks good to me -- lets do it. can you provide the SVG of the crossed out eye icon to @vedmant please?

**Comment by Watson-B** [comment]
@vedmant here is the crossed out eye icon [private-eye.zip](https://github.com/ezl/dailyidea.com/files/5783005/private-eye.zip)
