### ISSUE TITLE
Be more specific about when we want the explainer cards to show up

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#850]
The current logic is (I believe): "if the user tries to view an idea for the first time on this browser, then show the explainer card".

This works well for the case of:
1. First time ever user lands on landing page
2. Then scrolls through landing page cards (3 of them)
3. when they reach the first idea card, we explicitly show them that they can swipe for more ideas.

In this case, this is really good.

In several other cases, this is really bad. For example:
* someone shares a specific idea with a friend. friend clicks the link, then the first thing they see is the explainer (and not the actual idea)
* an existing user logs in from a new browser to view an idea or to update one of their own ideas. when they finish authenticating and get directed to the idea, they get blocked by the explainer.

@Watson-B and I will discuss this and be more explicit about when to show the explainer card.

**Comment by ikosovec** [comment]
The explainer card in its current version is only displayed when the user lands on the landing page and swipes through the cards before their first idea card.

If the user hasn't seen the cards before, we show them the banner. (@Watson-B)

**Comment by Watson-B** [comment]
The referenced banner.

![image](https://user-images.githubusercontent.com/65913664/104633379-e63d8d80-5653-11eb-8b59-36b0402372d2.png)

Tickets #859 #860 #861 #862 #863 show where in each respective flow this banner appears.

**Comment by ezl** [comment]
Closed in favor of #865 for clarity.
