### ISSUE TITLE
Wercker deploy-mail-dev deploy fails every time

### ISSUE THREAD

**Issue by vedmant** [ezl/dailyidea.com#852]
I noticed that deploy-mail-dev started to fail every time, I'll try to run this on local to check. Looks like it timeouts on Installing requirements

https://app.wercker.com/ezlnvureflgas/dailyidea.com/runs/deploy-mail-dev/5ff6ed0ecce6890008115433?step=5ff6eedab61ea500085694ec

**Comment by vedmant** [comment]
Ok, I increased timeouts, last deploy worked ok, I'll be watching if next deploys fails

**Comment by ikosovec** [comment]
@vedmant could we close this ticket? Did we fix it?

**Comment by vedmant** [comment]
@ikosovec Yes, it works ok now
