### ISSUE TITLE
Updating the login/signup copy - Like

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#859]
@ikosovec This ticket references [this Figma page](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A1292). The goal is to better guide an unauthorized user when they click on something that requires authorization. I'm breaking the tickets based on action taken, but the flow is similar for Like, Save, Comment (just with specific copy for the action). 

When an unauthorized user clicks the like button, we present them with the following modal.

![unauth_like](https://user-images.githubusercontent.com/65913664/104627227-9c50a980-564b-11eb-824a-95e557f8bc81.png)

After the user enters their email, the flow branches and guides them depending on whether they are a returning user/new user and whether they have a Gmail inbox or not.

![image](https://user-images.githubusercontent.com/65913664/104627443-dfab1800-564b-11eb-8074-c05ab905423c.png)

When the user opens the email, the subject and copy inside specifically reference the action they took.

![image](https://user-images.githubusercontent.com/65913664/104627746-46303600-564c-11eb-9a5a-45c3bfabacda.png)

After the user clicks the button, they see a loading screen confirming that the action they originally set out to do is being taken.

![image](https://user-images.githubusercontent.com/65913664/104628303-ee45ff00-564c-11eb-82d6-ccfb09b481bb.png)

If it is a returning user, they are then shown the idea with the like icon filled, the confetti, and a confirmation toast. If it is a returning user, they are then shown a modal above the original idea, asking for their name.

![image](https://user-images.githubusercontent.com/65913664/104628498-26e5d880-564d-11eb-9b02-0f4678049047.png)

Once the new user enters their name, they see the like icon filled, the confetti, and the confirmation toast. After this fades, we will show a second toast with the tip for new users on using arrow keys to navigate.

![image](https://user-images.githubusercontent.com/65913664/104628678-5b599480-564d-11eb-9a92-0772f2311194.png)

**Comment by vedmant** [comment]
@Watson-B Very cool, I like logical tree you created in Figma!

**Comment by vedmant** [comment]
@Watson-B Also noticed that I can now export SVG from Figma, so no need to attach images.

**Comment by vedmant** [comment]
There are some issues with adding custom icons to be used in Vuetify buttons, I'll need to move Vuetify into es module to make it able to compile required vue components. For now I can skip this and use Material Design Icons, they are a bit different.

**Comment by vedmant** [comment]
@ikosovec I'll need to do all this modals together, they interdependent (https://github.com/ezl/dailyidea.com/issues/862 https://github.com/ezl/dailyidea.com/issues/861 https://github.com/ezl/dailyidea.com/issues/860)

**Comment by vedmant** [comment]
@ezl Can I also do a bit of refactoring here, there are things that could be done better.

**Comment by vedmant** [comment]
@Watson-B Also noticed that in the flow we are missing ask name dialog, this is when user doesn't exists.

@ezl @ikosovec Also I'll create another issue where I can list all the actual work I need to do for this list of issues.

**Comment by ezl** [comment]
re: refactoring -- sounds good, @vedmant - I trust your judgment on these decisions, so if you think it makes sense to do, let's do it.

**Comment by vedmant** [comment]
@ezl Refactoring makes sense for project quality, especially when things were changed few times, without refactoring it's the way to the full mess in code.

**Comment by Watson-B** [comment]
> 
> 
> @Watson-B Also noticed that in the flow we are missing ask name dialog, this is when user doesn't exists.
> 
> @ezl @ikosovec Also I'll create another issue where I can list all the actual work I need to do for this list of issues.

Hey @vedmant, apologies, I'm not sure I understand. We have this modal further on in the flow.
![image](https://user-images.githubusercontent.com/65913664/105746092-de9fa380-5ef3-11eb-8897-c7dddb3083e1.png)
Do you have something else in mind?

**Comment by Watson-B** [comment]
In regards to the Material Design Icons, would that be a short-term solution until further down the road? I'm asking because the design language they use on that set is different than the language we use on ours, so mixing will create inconsistencies. Not a massive deal, but definitely not ideal.

**Comment by vedmant** [comment]
@Watson-B About name dialog, I also added comments here https://github.com/ezl/dailyidea.com/issues/871 this create quite some technical issues, so need to consult with @ezl if we should spend time on this.

> In regards to the Material Design Icons, would that be a short-term solution until further down the road? 

Actually I just found a way to do this, so disregard this please.
