### ISSUE TITLE
Updating the login/signup copy - Share

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#862]
See [this Figma page](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A1292) for reference. 

Due to confusion with the current share modal, we're breaking apart the input fields for entering the friend's email address and entering the user's own name.

![image](https://user-images.githubusercontent.com/65913664/104630276-7200eb00-564f-11eb-9123-90479ab53da8.png)

If the user clicks copy link to clipboard, the modal will flip and show a confirmation that the link was clipped. Linking the CSS flips @ezl posted to slack here: [first one](https://codepen.io/james_gillen/full/NGwqML), [second one](https://codepen.io/kharrop/full/zBjBLx).
![image](https://user-images.githubusercontent.com/65913664/104630566-c0ae8500-564f-11eb-93b7-07ac9dcdec4b.png)

After the user enters the necessary information to share, they are presented the Idea Shared toast, and a modal prompting them to enter their email and subscribe to Daily Idea. 

![image](https://user-images.githubusercontent.com/65913664/104630721-fc494f00-564f-11eb-9411-928bc5c917ab.png)

This then leads the user into the same flow as the one explained in the Like ticket #859 with updated copy and illustrations specific to this flow.

**Comment by vedmant** [comment]
@Watson-B @ezl  Is it important to have slider implementation in the modal? Cause it will take quite some additional time to create simple swiper (I can't reuse cards swiper in the modal). It will save hour or two if I just use separate modals instead of slider.

**Comment by ezl** [comment]
@vedmant - I'm not sure I understand the question. I want to make sure we're on the same page before we implement anything.

1. By "slider" do you mean the card flipping transition?

If so, then I'm willing to forgo the flipping, provided you close the original one and show the new one. Then at a future time, we can consider if we want to add some sort of transition.

2. You mention the "swiper" and reference a "sliding" effect -- It sounds to me like you are describing the idea swiping (left/right) transition that we use between ideas. If so, then that is *not* what we were attempting. Watson linked 2 examples of card *flipping* examples on codepen (we don't have to use those specific ones, just examples).

Anyways, let's first confirm that we are on the same page about what was originally requested, then if it makes more sense, we can cut back on the interaction and just do 2 modals.

**Comment by vedmant** [comment]
@ezl I meant swiper analog, as it had dots below so I assumed, the first image when first modal has active dot on the left, and next active on the right, are those two different modals?

Missed in description that modal should flip to show copy to clipboard version, I think it should not be hard to implement unless there are some issues with vuetify as we use their modal. It makes it harder to implement custom features and design when using Vuetify.

**Comment by Watson-B** [comment]
@vedmant so the dots are just to convey to the user that they should expect a 2nd step (addressing who it's from) after they've completed the first step (where it's being sent). If the user clicks "copy to clipboard instead" that's when the modal would flip. Otherwise, if they enter the email address and click next, then it goes to the second step (asking who to say the idea is from), no flip needed in this case.

**Comment by vedmant** [comment]
@Watson-B So no sliding effect, it just opens new modal? Or replaces content in the current one?

**Comment by Watson-B** [comment]
@vedmant correct, no sliding. 

Since I'm unsure of the technical side of opening v. replacing, I have a couple of questions before I can answer those. 
If it opened a new modal:
- Would it open on-top of the previous modal?
- Would there be a transition time as the first one closes and the second one opens?

Visually, I think it would look best to just have the next step instantly appear after they click next, so that the process of sharing is as fast as possible.

**Comment by vedmant** [comment]
@Watson-B You can see how it's done now on https://beta.dailyidea.com/i/o82uln/top-of-new-ideas-stack?category=new when you like idea and type not registered user modal, this is how it opens new modal.

> Visually, I think it would look best to just have the next step instantly appear after they click next, so that the process of sharing is as fast as possible.

Then I just replace content, it's also simpler than two modals.
