### ISSUE TITLE
Updating the login/signup copy - click the Post tab

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#863]
See [this Figma page](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A1292) for reference.

When an unauthorized user clicks on the Post tab. We're updating the card displayed to the following.
![image](https://user-images.githubusercontent.com/65913664/104631461-20f1f680-5651-11eb-929a-a39758b65901.png)

When the user enters their email address, they are then launched into the email flow explained in #859 with specific copy, illustration, and email subject for this action. The completed flow results guiding the user to the unlocked Post tab.
![image](https://user-images.githubusercontent.com/65913664/104631715-80e89d00-5651-11eb-99d3-4645b2baadad.png)

**Comment by vedmant** [comment]
@ezl I see this also has a new email for creating post, we didn't have that email before, this will require also some edits on backend to make it redirect to create idea, not sure if it should be done in this ticket or we create a new one?

**Comment by ikosovec** [comment]
> @ezl I see this also has a new email for creating post, @ikosovec probably needs a new ticket.

Opened it here: #880
