### ISSUE TITLE
Update to "Request a new link" modal

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#868]
See [this Figma](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A1292) page for reference.

Updated the illustration, copy, and modal design to be consistent with the rest of the login flows.

![image](https://user-images.githubusercontent.com/65913664/105252966-62900f00-5b33-11eb-8903-508007cf4c39.png)

**Comment by ezl** [comment]
@Watson-B - I just want to say I really love the illustrations you've done. :)

**Comment by vedmant** [comment]
Also covered this in https://github.com/ezl/dailyidea.com/issues/871 , for like / save / comment flow, other login flows have to be redone to use resend dialog.
