### ISSUE TITLE
#31. On mobile chrome on iOS the “x days ago” library seems to have broken https://files.slack.com/files-pri/TL0L52RHB-FQ37SMP6Z/image_from_ios.jpg

### ISSUE THREAD

**Issue by patelravi** [ezl/dailyidea.com#87]

**Comment by patelravi** [comment]
This issue comes when the date is not being returned from the api.

Checked just now on beta.dailyidea.com, its working fine.

![image](https://user-images.githubusercontent.com/7405840/68101455-c0671580-fef3-11e9-9d4e-37db0bd4ba1e.png)

**Comment by ezl** [comment]
removed done tag -- just checked, still showing error on beta.

google for bug reports on mobile chrome or try a simulator.
