### ISSUE TITLE
UI Update - Post Settings Dropdown going off the screen on Mobile

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#870]
On mobile, the dropdown for post settings currently goes off the screen. ![dropdown](https://user-images.githubusercontent.com/65913664/105256871-73dd1980-5b3b-11eb-9fad-2afe5a235c70.png)

**Comment by ikosovec** [comment]
This looks good on my device.
@watson-b since you reported the ticket, could you please check if this is fine on your device now?

I checked on both Samsung Note10+ and iPhone 12.
