### ISSUE TITLE
Rethink scrolling / full screen view for ideas on desktop

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#875]
Currently, our desktop view for an idea shows VERY little actual content.

The idea is the star, but it currently only takes up about 20% of the total screen area:

<img width="1437" alt="Xnip2021-01-24_20-09-24" src="https://user-images.githubusercontent.com/157627/105653584-c8f19600-5e81-11eb-9453-e30b725fbd80.png">

This ticket is currently not ready for execution. Placeholder for discussion for future about how to improve this.

Potentially related - changing comments -- do we really want that there? or can comments live in a different component that is only displayed on click?

Edit: I'm a nerd, so I did the math. 17.8% of that screen is the actual idea area.

**Comment by ikosovec** [comment]
> Potentially related - changing comments -- do we really want that there? or can comments live in a different component that is only displayed on click?

I was thinking about this for the last few weeks as well. Maybe we can keep the UX that has been present on internet threads for decades - and pull the comments down below the content?

Also, on this topic - thinking out loud - maybe we can adjust the currently existing design slightly, and use the cards as a _preview_ of the whole ticket? A pattern that can be found on news articles, forums, reddit, etc.

I can imagine how the regular DAU will use the app - by comparing myself to using reddit or another forum.
I can see the regular user opening DI and scrolling through the "Explore" tickets and reading titles. If the title got their attention, they'll go more into detail. I guess in this case we could show them only a preview of the idea - removing comments completely, and then giving them the full feature once they "dig deeper" in the idea - similar what you get on reddit.

What do you think?

**Comment by Watson-B** [comment]
@ezl @ikosovec I did some mocks exploring how to get more of the initial idea above the fold and different ways the comments can live "inside" the idea. One thing I stayed away from though was making the cards wider, and moving past optimal line length for readability.

**Full Idea / No comments**
<img width="1480" alt="full idea" src="https://user-images.githubusercontent.com/65913664/108926727-d3738c80-75f3-11eb-9569-d75d8ddb23f6.png">

**Full Idea / Smaller Icons**
<img width="1480" alt="full idea - small icons" src="https://user-images.githubusercontent.com/65913664/108926756-e5edc600-75f3-11eb-8696-f9231e125c70.png">

**Full Idea / Smaller Title**
<img width="1480" alt="full idea - smaller title" src="https://user-images.githubusercontent.com/65913664/108926790-f9992c80-75f3-11eb-9a32-3c6bac6b5c85.png">

Then as @ikosovec was suggesting, when a user has gauged that an idea preview is interesting, they would be taken "inside" where the comments would live. 

**Full Page Idea**
<img width="1480" alt="idea full page" src="https://user-images.githubusercontent.com/65913664/108926876-1a618200-75f4-11eb-9a2b-22823ebef5f9.png">

**Pop-out**
<img width="1480" alt="idea pop out" src="https://user-images.githubusercontent.com/65913664/108926912-2cdbbb80-75f4-11eb-9e10-67de22561fb6.png">

We could then put the comments and chance to input a comment at the bottom.

**Input above comments**
<img width="1480" alt="comment input above comments" src="https://user-images.githubusercontent.com/65913664/108926989-5268c500-75f4-11eb-93de-867bbcedf6db.png">

**Input Sticky Scrolled**
<img width="1480" alt="scrolled" src="https://user-images.githubusercontent.com/65913664/108927037-657b9500-75f4-11eb-83d7-e47b0f51af9d.png">


**Input Sticky At Bottom**
<img width="1480" alt="full scrolled" src="https://user-images.githubusercontent.com/65913664/108927041-66acc200-75f4-11eb-9149-1975958b7a84.png">

Depending on behavior users start interacting with the site/eachother, I think there are probably some other steps we can take. Going to put these here, just so they don't get lost down the road.

Currently, users can't resize an image in there post, and in the idea preview the image is displayed full-size. I think we can do more here depending on what types of images are being included.
**Image Resize**
![resize](https://user-images.githubusercontent.com/65913664/108927263-cc994980-75f4-11eb-804e-b6411a883d3e.png)

Another pattern I saw recently was a comment sidebar when focused on a particular article. I had a thought that if users end up referencing specific points in a post, this might be a beneficial direction.
<img width="1480" alt="comment sidebar" src="https://user-images.githubusercontent.com/65913664/108927335-f488ad00-75f4-11eb-80ae-41aca2b935d1.png">

**Comment by ikosovec** [comment]
I prefer the full page display instead of the popup display.

The other propositions look good to me, and I don't really like the comments being on the right side (last image). Not sure if I've seen that position in any websites (I might be wrong!).

I think what we're leaning towards is similar experience which our target users are already getting on other non-idea-niche social media (Reddit, Facebook, Instagram?, Twitter?, etc.) - so getting as close to that UX and object positions should be our goal. I think we're getting really close to that with these propositions. Once again, that's only my train of thought and I could be wrong regarding this.

Definitely this is something for @ezl to review and share his thoughts on this.

**Comment by ezl** [comment]
@ikosovec I will discuss this in my weekly meeting with @Watson-B 

My gut feel on the full screen vs popup display though is that I prefer the popup display.

Since this is opposite of your intuition, I wanted to explain my perspective.

(A) Aesthetically, and as a STANDALONE screen, I prefer the full screen as well. However:
(B) In the context of the scrolling/swiping/browing pattern, I think it's important to know that the user just "entered a different mode" (viewing ONE idea), and that they can go BACK to the old one (browsing) by clicking escape or X (or the generally accepted "quit" patterns).

So I feel that it helps with DISTINGUISHING the 2 patterns from one another.

-- 

Regarding my current thoughts on the rest of it:

I think we need to separate the comment entry ideas into a separate issue. All of the "idea detail" ideas already remove the comments, which help with the original purpose for this ticket ("rethink scrolling / full screen view for ideas on desktop").

The question of how to enter comments from the secondary screen can be addressed separately, so combining them into a single ticket makes it harder for us to discuss and close the single issue (if they are separable, which I believe they are)

So for the purposes of this ticket, @ikosovec can you create a separate ticket regarding the comment entry screens from @Watson-B?

Then we can just use this screen for discussing the new proposed "idea detail" view -- Will first discuss with @Watson-B but my gut reaction is to use the screen that @Watson-B created titled *pop-out* with:
 
(A) popup/overlay
(B) smaller title
(C) smaller icons
(D) no comment entry

**Comment by ikosovec** [comment]
> I think we need to separate the comment entry ideas into a separate issue. All of the "idea detail" ideas already remove the comments, which help with the original purpose for this ticket ("rethink scrolling / full screen view for ideas on desktop").
> 
> The question of how to enter comments from the secondary screen can be addressed separately, so combining them into a single ticket makes it harder for us to discuss and close the single issue (if they are separable, which I believe they are)
> 
> So for the purposes of this ticket, @ikosovec can you create a separate ticket regarding the comment entry screens from @Watson-B?

Created a new ticket as proposed here: #903

**Comment by ezl** [comment]
Thank you for creating the new ticket regarding the full screen view, @ikosovec.

I've discussed this with @Watson-B and I no longer feel strongly about my initial gut choice of having the overlay (style "pop out" from above.

After discussion with @Watson-B we decided on "Full Page Idea", which is more in line with @ikosovec original thoughts. Rationale: Reddit and basically all "forum" sites essentially support the context switch mode rather than the overlay style so it's probably a valid pattern.

Additionally, I've created 2 separate tickets for future discussion that were included in @Watson-B 's original post here regarding:

Image resizing: #905 
How to enter comments: #904

**Comment by ezl** [comment]
(A) the original purpose of #875 based on the screenshot I posted in the original ticket creation is to make it so while SWIPING/SCROLLING through ideas on desktop, you can see MORE of the idea content.

(B) Watson created a bunch of really nice screen options, but I failed to understand that there were two TYPES of screens. the first 3 he proposed are for the "swiping" view. Then the rest are for if someone CLICKS it / clicks "read more" on desktop. I confused these and therefore I made a mistake by choosing a "click in" choice, which does NOT solve the original problem of "not enough visible on screen while swiping"

(C) I think for the SWIPING view, we need to choose a solution (all are fine, but I like full idea smaller title.

(D) it's not clear to me that we NEED a "click in" view here. Scrolling on the swipe view might be sufficient (that's what we already do). 

(E) if so, then my proposed solution is simply to make the initial screenshot look like @Watson-B's "full idea / smaller title" option. then the task is simply something like:

- [ ] remove comment section
- [ ] make minor adjustments to idea header by shrinking title etc

**Comment by ezl** [comment]
no longer necessary. since #949 supercedes
