### ISSUE TITLE
32. make carriage return work for form entry

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#89]
if someone presses enter on a form, it should submit it.

examples where this doesn't work:

1. login screen
2. signup screen
3. submit idea

find any other examples of forms or submit buttons also and fix

**Comment by patelravi** [comment]
Done for login screen and signup screen.

On Idea Create:
May not be a good idea.
1. Idea title is a text area, when user preses enter, it takes to new line in text area, should that be changed to normal text box?
2. On trix editor, user may want to got to new line, instead of submitting form.

**Comment by ezl** [comment]
agree, don't implement on submit idea.

**Comment by aldarund** [comment]
works on login and signup
