### ISSUE TITLE
Design update - going to "My ideas"

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#894]
Original thread: #879 

@vedmant wrote:

> I see this section in Figma is also quite different from what we have now, there is new "Oops you’re not logged in." screen (on actual my ideas page? I see menu is active).
> 
> Also the same auth flow applied there, but currently it just redirects on separate login page which doesn't keep maintain redirect link after login. So before I can implement loading message "going to My Ideas..." I'll need to redo how authentication on my ideas page works and add new "Oops you’re not logged in." screen.
> I think it needs a separate issue.

@ezl I'm tagging you as we agreed - to continue the discussion here.

**Comment by vedmant** [comment]
There are following subtasks:

- [ ] My ideas page should open for not logged in user, and show "Oops you’re not logged in." card
- [ ] User new AuthFlow to authentication on my ideas page
- [ ] New separate email "Looks like you tried to visit My Ideas ..." ??


@Watson-B @ezl One question, do we really need separate email for almost each type of login? We already have 8 different emails just to login user, this one will be 9th. Having this many emails makes it difficult to maintain in case of any change in emails.

**Comment by ezl** [comment]
@vedmant for now, please take no action on this flow. Based on your feedback, I'd like to review it with @Watson-B again first, then we will likely come back to discuss with you.

@Watson-B  I reviewed the CURRENT flow we have already, and to be honest, it already feels very close (from the USER experience, maybe not the actual code though).

Right now, in both the new Figma design and the current live site, basically:

1. press "my ideas" while not authenticated
2. user is shown a "not authenticated, log in or sign up" screen.
3. click on one of those
4. user email authentication process begins

Can we revisit this "my ideas not authenticated" path when we chat soon? moving this issue to design/to do

**Comment by Watson-B** [comment]
@vedmant I spoke with @ezl about the emails and "Oops you're not logged in" flow for My Ideas, and we decided to add this last email. Regarding future changes, now that we have the redesigned flow and the messaging is in line with what we're looking for in a guided experience there shouldn't be any changes to these anytime soon.

**Comment by vedmant** [comment]
@ikosovec @ezl There is another issue here, user own profile page is basically on the same URL as any other profile. Means the same page like http://localhost:3000/profile/vedmant works as other user profile preview as well as own user profile page. If I require user to authorize to open this page means user will not be able to view any other user profile page. 

There are two options how to solve this:

1. Create a separate page for own user profile, maybe just `/profile`?
2. When clicking on My ideas, don't redirect to /profile/{user} page, instead open Auth flow dialog in place. Then in email it will redirect to /profile/{user} with authentication.

**Comment by ikosovec** [comment]
I'd go with the one option you think would be best.

**Comment by ezl** [comment]
i think we have some miscommunication on this issue now, so please do not take any action.

@vedmant my goal is to make as few changes to [this particular "branch" ("User Clicks My Ideas") in the Messaging Tree page of Figma](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A3978) as possible.

To help me with that, can you get some information for me please?

(A) From what I can tell, for the CURRENT website, in the top nav, shows the actual *target* for "My Ideas" link is `/profile/{username}` if `user is authenticated` else `/auth/unauthorized`. (This is what I see, but this seems different in implementation from, for example, a pattern that always links to the same page, but a decorator on the target page checks for authentication and redirects or displays different content). Is my assessment accurate?

(B) If so, how many OTHER links in the entire site are there that link to directly to `/auth/unauthorized`? If it's a small number, can you itemize them or tag them in the code?

**Comment by vedmant** [comment]
@ezl 

(A) Yes, currently it redirects to /auth/unauthorized and this is a generic page, from the screen on Figma I understood that not logged in screen is specific to My ideas page, and so is located on /profile/{username} page (and to make specific authentication for My ideas this have to be specific not logged in screen for  /profile/{username} page only). And this is where the issue arises,  /profile/{username} can be accessed by not logged in user to see user profile, so it should not show not logged in screen.

(B) I see that a `authenticated` middleware redirects to /auth/unauthorized, so this means any page that has `middleware: 'authenticated',` will redirect to this page. Currently I see it's set for settings page, /profile/{username}/saved, /profile/edit and from My Ideas link.

**Comment by ezl** [comment]
ok, thanks for updating me here. based on your responses, I am going to close this issue in favor of:

1. NOT changing the actual entire **FLOW** for an unauthenticated user clicking on "my ideas" button in nav -- I believe the current flow is sufficient for now without a custom flow for this use case.
2. Creating just a single custom **PAGE** for an unauthenticated user that clicks the "my ideas" button in nav. This will just be a static page like `login-to-view-my-ideas` and it will just be a page is specific to IF the user clicks "my ideas" while unauthenticated. It will just be [this slide](https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A10613) with static links to initiate the default login and signup flows.
3. Update the images on the generic "unauthorized" page

**Comment by vedmant** [comment]
I'll remove this from project since it's closed
