### ISSUE TITLE
Bug (beta site): Clicking Edit Idea on My Ideas Page does not do anything.

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#898]
Steps to reproduce:
1. Log In
2. Go to My Ideas
3. Click options for an idea
![image](https://user-images.githubusercontent.com/65913664/108927493-3d406600-75f5-11eb-8c4f-ec39d2342f30.png)

4. Click edit idea

Nothing is happening when Edit Idea is clicked; however, delete and make private both work.

**Comment by vedmant** [comment]
@ikosovec Btw, what it should do, open a lightbox in edit mode?

**Comment by Watson-B** [comment]
@vedmant @ezl wants to revisit the edit an idea flow. I'm finishing up the mocks for it and will post later today.

**Comment by ikosovec** [comment]
> @vedmant @ezl wants to revisit the edit an idea flow. I'm finishing up the mocks for it and will post later today.
This is done through #874

**Comment by ezl** [comment]
the idea was that edit should lead to editing the idea. Currently, clicking on it doesn't nothing at all.

@vedmant I believe this will be resolved by https://github.com/ezl/dailyidea.com/issues/916 if we move this to a full screen.

**Comment by ikosovec** [comment]
We can probably deprioritize this as well since #916 will change the logic and layout.
