### ISSUE TITLE
Share idea

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#9]
On every idea, have a share button.

Emulate the share functionality of reddit:

On desktop, it should have:

1. Copy link https://monosnap.com/file/ntfybeJvyvj2tEAHOePZJtdheomxLm
2. Also add a "send via email" option -- small form takes your name, friend's name, and an email address and sends an email to a friend. (for now just send plaintext, "Hi John, Eric thought you would be interested in this idea! <insert link>. we can design this email later.)

**Comment by patelravi** [comment]
An api is needed which will take idea id, from user name, from email id, destination user name and destination email id. And send idea details email as a part of share functionality.

Hence added back-end label.
