### ISSUE TITLE
hover states on desktop left/right buttons on browse

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#902]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/157627/109588861-070c5600-7acf-11eb-84ed-01cdb0a5f0d6.png">

cc @Watson-B

**Comment by Watson-B** [comment]
Good catch, it was in the prototype but hadn't caught that it was on live. The default state is on the left and uses #A7A7E7. On hover, it fades to the icon on the right which uses #5A41BA for the stroke and #E8E8F4 for the fill.
<img width="189" alt="hover-sample" src="https://user-images.githubusercontent.com/65913664/110045722-f7278880-7cff-11eb-9147-e9bda67e3cb9.png">
