### ISSUE TITLE
Standalone comment entry pages

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#904]
Separated from multi-issue discussion https://github.com/ezl/dailyidea.com/issues/875

In the above issue we are changing the idea detail display. This will require us to update the comment entry style, but since this is not yet decided how we will do it, creating a separate ticket for the screens/flows required for that.

**Comment by Watson-B** [comment]
@ikosovec I talked with @ezl about this, and we are going to go with the following comment style.
We are going to remove comments from the swiping view and the full page view. On the full page view, the comments and "join the conversation" input will be replaced by a link "view all X comments" or "start the conversation" if there are no comments. When the user clicks the comment icon it will open a modal with all of the comments and the option to input one.

![updated-full-page-comment](https://user-images.githubusercontent.com/65913664/111876168-c62f9080-895a-11eb-8eb4-faa842358527.gif)

**Comment by ikosovec** [comment]
Thanks for the info @Watson-B!

**Comment by Watson-B** [comment]
Updated and broken apart in #949
