### ISSUE TITLE
Image Placement

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#909]
Originally referenced in #874 and ties into issue #905, creating a breaking it into a smaller issue just focusing on how the images move.

> Currently, when a user attaches an image, they can only drag to relocate the image. There is complete freedom in where the user places the image, they can place it mid-sentence if they want, but without more controls, the end result is less than ideal.
image. I have two approaches in mind. First, take a page out of Google Docs, and allow images to be resized and to have text wrap.

<img width="1480" alt="wrap" src="https://user-images.githubusercontent.com/65913664/110047520-e3315600-7d02-11eb-866f-1c37a91422e4.png">
<img width="1480" alt="edit image resize" src="https://user-images.githubusercontent.com/65913664/110047397-abc2a980-7d02-11eb-8e9b-8bf604748465.png">
<img width="1480" alt="w(rap)ip" src="https://user-images.githubusercontent.com/65913664/110047400-acf3d680-7d02-11eb-899e-02d88dc769ea.png">

> The second would be the simpler approach, and would follow how Evernote treats images. Evernote allows users to resize images, but rather than total freedom to place images wherever. They make it so the image can only be dropped in line breaks, resulting in a better end looking post.

<img width="1480" alt="edit image move" src="https://user-images.githubusercontent.com/65913664/110047402-ad8c6d00-7d02-11eb-85f4-5d518d870182.png">

**Comment by vedmant** [comment]
vedmant  12:50 AM
@Ivan Kosovec @ezl It will require to replace editor with something like https://tiptap.dev/ and create custom component for images, rewrite images / files uploading, not sure how much time it can take, maybe around 5-10 hours

vedmant  12:57 AM
Maybe it’s also possible with trix, but I have experience with tiptap, plus I think it’s better in general, also it’s written in Vue and uses Prosemirror under the hood, witch is very flexible and powerful

vedmant  1:03 AM
Another option to use Quill, looks like it have image resize already  https://codepen.io/knekk/pen/odwELZ but I didn’t have experience with it (edited) 
1:05
Here is some discussion about it https://news.ycombinator.com/item?id=18998042

**Comment by ikosovec** [comment]
I suggest going with tiptap since @vedmant has experience in it already and from technical perspective he suggest we move forward with it.

**Comment by ezl** [comment]
I'm personally a little bit wary of the tiptap rewrite. While I think we'll likely do it eventually (if so, maybe just do it now), what I'm worried about is **"what are we solving, what are we risking?"**

So first, let's be clear about what we're GAINING:

1. Image sizing / placement as per @Watson-B's screenshots
2. ctrl-z problem that we ignored from #452 
3. more control over the toolbar
4. easier to work with / headless / more control

Is that it? Or are there any more? Do we have any specific features or bugs?

In contrast, I believe the risks we face are implementation difficulty (does tiptap make images easy?) and breaking something that "basically works" (trix maybe harder to work with, but personally I'm not **_*UN*_**-happy with it)

So what I'd like to know is:

1. @Watson-B @vedmant @ikosovec can you think of any UX or feature based GAINS or issues we are trying to fix/add to this?
2. @vedmant do you feel pretty confident about being able to replace trix with tip tap in <10 hours? (I understand it's just an estimate, not a promise, but just want to get a sense of your level of confidence. if you're confident now, but after beginning, that changes, that's OK, and please just lmk.)

**Comment by vedmant** [comment]
> Is that it? Or are there any more? Do we have any specific features or bugs?

Potentially we can add any feature, like people mentions, other ideas mentions (https://tiptap.dev/suggestions), markdown shortcuts (https://tiptap.dev/markdown-shortcuts, something like Slack has) any custom elements like todo or checklists, embeds, etc...  

> In contrast, I believe the risks we face are implementation difficulty (does tiptap make images easy?)

For me it's much simpler to work with Tiptap than with any other editor, especially when it should be fully customized.

> 2.@vedmant do you feel pretty confident about being able to replace trix with tip tap in <10 hours? (I understand it's just an estimate, not a promise, but just want to get a sense of your level of confidence. if you're confident now, but after beginning, that changes, that's OK, and please just lmk.)

Yes, I already worked with it (added custom emojis control using png images: https://prnt.sc/10m3hgj) so I can reuse that code and experience. As I understand what we need right now is to recreate only: images uploading, files uploading? Then add resizing to images, plus some time for adjusting layout, custom toolbar and details.

**Comment by ezl** [comment]
ok, this is a no brainer. I'm ready to execute this. Let's go for it.

In that case, I believe there are several components to this:

1. replace trix with tip tap 
2. make images controllable as described by watson
3. then also fix #452 which we originally closed because we don't think it's feasible with trix

**Comment by vedmant** [comment]
Images resize example https://glitch.com/edit/#!/toothsome-shoemaker?path=README.md%3A1%3A0

**Comment by vedmant** [comment]
Ok, it took a bit more time, I had to rewrite that example completely as I couldn't figure out hot to pass prosemirror nodeView to tiptap, there were issues with selection as well, but not this looks much cleaner and I made is as a Vue component.

There is one issue, looks like backend html sanitizer removes width style from images. I'll need fo fix this as well.

**Comment by vedmant** [comment]
There is one thing left, I see in examples image floating is also can be changed, it will be another task that also may take significant time. Should we create another ticket for this?

**Comment by ezl** [comment]
what do you mean about "floating" -- can you create a separate ticket for that please @vedmant ?

**Comment by vedmant** [comment]
@ezl I mean this:
<img width="359" alt="Screenshot at Mar 24 16-38-42" src="https://user-images.githubusercontent.com/5052406/112328967-738a0780-8cbf-11eb-993b-fee4616a82bc.png">
<img width="602" alt="Screenshot at Mar 24 16-38-53" src="https://user-images.githubusercontent.com/5052406/112328982-74bb3480-8cbf-11eb-9a1c-e753d1e23a9f.png">

Also it has floating menu, tiptap has support for this, but it's also a piece of work.
The question is if we need this.

**Comment by ikosovec** [comment]
From Slack discussions - we have concluded that we do not need a text wrapper.
