### ISSUE TITLE
?next get args?

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#926]
Should we consider allowing for get args like `?next=/profile/me` or `?next=/idea/blah-blah`

or do we have that?

for after redirects on auth events?

example of this in django: https://stackoverflow.com/questions/3441436/the-next-parameter-redirect-django-contrib-auth-login

**Comment by vedmant** [comment]
@ezl Yes we use next query param for redirects: https://github.com/ezl/dailyidea.com/blob/012aa5dfc8cd2208f9b1c71b2ea6cf6fe0de7e5e/front/pages/auth/verify.vue#L82

**Comment by ikosovec** [comment]
Awesome, thanks for the quick reply. Closing!
