### ISSUE TITLE
Create separate single page for if unauthorized user clicks on "My Ideas" in top nav

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#928]
(Replacement for trying to replace the entire FLOW for if an unauth user clicks on My Ideas, from https://github.com/ezl/dailyidea.com/issues/894)

Currently, in the top nav, if the user is not authenticated, the "My Ideas" link destination is hard coded to the generic "not authetnicated page" : https://github.com/ezl/dailyidea.com/blob/045b928510bd50d1c0b640341ba83470cff756a9/front/components/layout/Links.vue#L27

Instead, let's direct them to a SPECIFIC "not authenticated page". https://www.figma.com/file/VTAWAu8G6jtzpWYulfpw9m/Daily-Idea?node-id=202%3A10613

--

Further, @Watson-B would it make sense to include a sentence about WHY a user would want to have their own ideas? or that they can see all their saved ideas? Or is that too much text?

**Comment by vedmant** [comment]
@Watson-B A question about size and vertical alignment of this cards when screen size changes. For example right now it has fixed padding from the top and width is 70% of the screen (https://prnt.sc/10mzz66 https://prnt.sc/10mzzgo). But this might be not what you intended in the design, could you describe this more detailed?

**Comment by Watson-B** [comment]
@ezl I don't think it's too much, I think we just need to find the right copy. I took a few stabs at it, but I don't think I've found the right tone yet.
![why-1](https://user-images.githubusercontent.com/65913664/111395004-1a93f100-8679-11eb-902e-b656312e95f3.png)
![why-2](https://user-images.githubusercontent.com/65913664/111395006-1b2c8780-8679-11eb-856f-16be6e739f54.png)
![save](https://user-images.githubusercontent.com/65913664/111395012-1e277800-8679-11eb-8641-d06749b8a033.png)
![quote](https://user-images.githubusercontent.com/65913664/111395025-254e8600-8679-11eb-89d9-116f367c1f01.png)

@vedmant Given the screen size, I think the padding looks fine. After looking at these two images, I think I missed something when we discussed scaling in #869 that warrants further discussion. If we are trying to optimize card size for legibility, the line length should be between 50-75 characters. I could be wrong, but in the linked images, it looks like the copy size stays the same while the card grows wider. I think we should either set a maximum width for the cards/nav, scale up the text on cards/nav, or some combo of the two. Increasing text/element size would maintain legibility and negate some Fitt's law problems that would occur if the user is using a very large screen and the nav elements remain small. Thoughts?

**Comment by ezl** [comment]
Let's not let the copy stop us from allowing @vedmant to have a "My Ideas" specific unauthorized page.

@vedmant please proceed with:

main: Oops you're not logged in.
subtext: Save the best ideas on the internet to read later with an account

**Comment by vedmant** [comment]
@ikosovec The page was already created, I just updated text to `Save the best ideas on the internet to read later with an account.`

**Comment by ezl** [comment]
beautiful.
