### ISSUE TITLE
Share in FB messenger / Twitter

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#929]
Add share on FB + twitter functionality

<img width="858" alt="image" src="https://user-images.githubusercontent.com/157627/111192961-a4639180-8587-11eb-92d6-f4d9131786a1.png">

@vedmant you can start working on the functionality?

@Watson-B can you mock up this screen for desktop with the FB and Twitter buttons added? (i don't think we need this for mobile, because on mobile we're already triggering the native device share)

**Comment by vedmant** [comment]
@ezl There is no much I can do before I see how it looks in the design, adding share popup is simple.

**Comment by Watson-B** [comment]
@ezl a couple of passes on how this could work. 

First, would be the pattern sites like giphy, pinterest, and techcrunch use. 
Pros: This is a common pattern, and doesn't make assumptions about how a user prefers to share.
Cons: Requires an extra click to share via email.

![image](https://user-images.githubusercontent.com/65913664/111388328-4ceb2180-866c-11eb-87fb-38d21eeea5bb.png)

The second would be to place share buttons down below with the "copy link instead"
Pros: It keeps everything on one card, and just requires adding buttons. I'm guessing this would be easier from an implementation perspective. Thoughts @vedmant?
Cons: It creates a very long modal. 

![image](https://user-images.githubusercontent.com/65913664/111388613-d7338580-866c-11eb-8c91-94182b478594.png)

With this share direction, I moved the pagination pips closer to the next button to make it clear the are associated with the share via email.

**Comment by ezl** [comment]
let's go with the first pattern (all 3 in line, require extra click for email).

**Comment by ikosovec** [comment]
I also really like the 1st option the best. :)

**Comment by vedmant** [comment]
@Watson-B There is one issue, this dialog is flippable, means other side have to be the same size as front side, you made it much taller other side will be half empty.
