### ISSUE TITLE
36. Automatically log in on signup account confirmation

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#94]
When a user signs up, we currently send them a confirmation email.
When that email is clicked, it should both:
(A) verify the account (what is currently being done with this?)
(B) log the user in.

Currently the user isn't being logged in.

What happens right now when the email account confirmation link is clicked?

**Comment by patelravi** [comment]
@aldarund marking you on this issue since login api sends email at login, so changes will be required there.

**Comment by ezl** [comment]
not done.

**Comment by aldarund** [comment]
cognito dont really support such flow :(

**Comment by ezl** [comment]
lets discuss this. i feel like there must be a way to hack this or chain the actions together.

**Comment by aldarund** [comment]
The  one time code to login is generated by our lambda cognito function and sent to mail.
https://github.com/ezl/dailyidea.com/blob/dev/back/users/src/defineAuthChallenge.js - here we define the challenge.
https://github.com/ezl/dailyidea.com/blob/dev/back/users/src/verifyAuthChallenge.js and here we verifying challenge answer.

So to login we need to 1) generate challenge 2) post that generated challenge from client to api

i dont see how we could fit here automatic signin.

**Comment by ezl** [comment]
if i understand correctly, this doesn't work because there are multiple round trips between the client and our server in order to 1. verify the email address for account creation, then 2. log the account in.
```
1. the email verification request is initiated in the client (collect email).
2. this email is posted to the server, which then generates a verification token and sent to the email.

at this point, the user is on the website, but NOT authenticated.
in order to authenticate, the user must then

3. click a button to request an auth token be generated and emailed
4. click the link in the email, which verifies the token

```

therefore, multiple trips.

is that correct?

the flow i WANT is that for a user, it feels like there's only one step. you:

1. enter your email address
2. receive an email
3. click the button in the email

tada! now you're (A) verified, and (B) logged in

if I'm understanding the multiple round trip issue, then can we do the following:

1. on SIGNUP request, we basically automatically create the account and answer the question ourselves internally to verify the account (don't actually require the user to do so), and automatically send them the AUTH challenge

2. when they click the button in their email, they will be AUTHENTICATING. We can assume if they authenticate that they have successfully verified their email.

@aldarund

**Comment by aldarund** [comment]
1 - we cant. that flow can be initiated only from client via login request

**Comment by ezl** [comment]
https://github.com/amazon-archives/amazon-cognito-identity-js/issues/186

seems like others are saying that they can achieve it in an insecure fashion by internally storing the password. since we don't actually EVER use password auth, this is a non issue for us.

**Comment by aldarund** [comment]
Yes, im aware of this workaround. But the problem that we dont have password, we have one time code. So nothing that we can store on signup
