### ISSUE TITLE
Rotating quotes in emails

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#943]
**Issue:** @ezl pointed out that the quote in the Week in Numbers and log in email (from beta site) stays the same. "Daring ideas are like chessmen moved forward. They may be beaten, but they may start a winning game." Can we update this to rotate and feature a random quote from [this spreadsheet](https://docs.google.com/spreadsheets/d/1tB4AQWBD3zACNq8RauMWDFLnHf5chKOQ-PU28IJYlEE/edit#gid=0)
**Week in numbers email**
![image](https://user-images.githubusercontent.com/65913664/112240613-dc14ae00-8c05-11eb-859c-b241551a0652.png)

**Daily Idea Email**
The quote in the Daily Idea email does rotate, but appears to have a small pool to draw from ( I looked at about 20, and had a few repeats) Can we expand the pool to draw from the spreadsheet?
![image](https://user-images.githubusercontent.com/65913664/112240526-b9829500-8c05-11eb-9272-5af0693d0c9c.png)
![image](https://user-images.githubusercontent.com/65913664/112240537-c0a9a300-8c05-11eb-95c5-c269235209ee.png)

**Comment by ikosovec** [comment]
@vedmant can you look into this please?
