### ISSUE TITLE
Slow loading time when logging in

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#944]
@vedmant, @ezl and I were discussing the load times and potentially using them as a time to show users tips about tagging or quotes on ideas. Talking about it though, we realized the macro issue was that load times are a bit slow when logging in. I ran a rough test logging in from the "don't worry it's me" magic link 10 times and clocked an average of 4.93 seconds. I ran the test without clearing browsing data or using a new browser window (with the exception of the first log in - 6.97s)

**Disclaimer about margin of error:** I used the stopwatch on my phone, and clicked start on the timer at the same time as the magic button "Don't worry it's me", and hit stop as soon as the idea loaded. Using humanbenchmark.com, I tested my reaction speed and have 211ms reaction speed. I did not adjust the average to reflect this. There was one outlier for loading where I clocked 9.73 seconds, but I discarded that since I'm assuming that was something on my end and not reflective of the site.

Can anyone confirm if they are getting similar numbers? If so, how difficult would it be to improve the loading speed?

**Comment by vedmant** [comment]
@Watson-B Yes it loads quite slow and the bottleneck is AWS Cognito here, this will work much faster when we switch to Django backend.

Here is more details about steps for AWS signin:

cognito/signInUser 2021-03-24T09:02:57.915Z
cognito/answerCustomChallenge 2021-03-24T09:03:02.307Z
userData/fetchUserData 2021-03-24T09:03:03.419Z
finished login 2021-03-24T09:03:03.420Z

So it's like 6 seconds to login, most of the time takes `cognito/signInUser`. (@aws-amplify/auth `Auth.signIn()`)

**Comment by Watson-B** [comment]
Okay, in that case until we do the backend rewrite, can we add rotating quotes to the loading screen without slowing things down even more?

Something like this:
<img width="1480" alt="quote on load" src="https://user-images.githubusercontent.com/65913664/112572890-6dbc2100-8da8-11eb-9c73-96debef7e5dd.png">

**Comment by vedmant** [comment]
@Watson-B Sure, I can add random quote from the list, where to I get list of quotes?

**Comment by Watson-B** [comment]
@vedmant Awesome, thanks! We can use [this list](https://docs.google.com/spreadsheets/d/1tB4AQWBD3zACNq8RauMWDFLnHf5chKOQ-PU28IJYlEE/edit#gid=0).
