### ISSUE TITLE
37. create idea page -- shouldn't be accessible if not logged in.

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#95]
https://beta.dailyidea.com/ideas/create is publicly accessible. however, trying to enter an idea fails.

make it so this page redirects to the login page with a message for the user: "Oops, you're not logged in. Please log in first to enter an idea."

**Comment by patelravi** [comment]
@aldarund should we implement nuxt auth module for this? 

Or just login check at page load  and redirecting to 404 will do?
