### ISSUE TITLE
Transition from Idea in swipe view to full page idea

### ISSUE THREAD

**Issue by Watson-B** [ezl/dailyidea.com#955]
@ikosovec suggested an animated transition from the swipe view idea to the full screen idea. Here is a mock of that transition.
![idea-transition](https://user-images.githubusercontent.com/65913664/113438500-8b3b4d00-939d-11eb-9576-23279fa8cf47.gif)

**Comment by ikosovec** [comment]
Love it! :)
Moving to dev.

**Comment by vedmant** [comment]
To make this animation possible I'll need to do #949 differently, not in a dialog, but using the same card state and disabling swiper. @ikosovec It's good that you added this task before I completed #949, otherwise I had to redo that one almost completely.
