### ISSUE TITLE
Make "comment attempt by unauth account" flow post comment at end

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#959]
@vedmant I tried this yesterday on beta.dailyidea.com (currently at [this commit](https://github.com/ezl/dailyidea.com/commit/0d3d03db90b8b0c51a5e48919ff13bb2a0ec0ec5)).

It it didn't work as I expected.

The behavior I observed is

1. From an unauthenticated account, attempt to post a comment
2. This will result in being asked for an email address to complete posting
3. I entered an EXISTING user email address (my own gmail)
4. I was directed to click the link in my email.
5. I clicked the link
6. I was directed to a waiting page. After it succeeded, the light bulbs turned green and said "going to post"
7. The idea loaded (no confirmation message or streamers/animation)
8. The comment was NOT posted (I tried refreshing the idea)
9. Loading a new browser and navigating to the idea, I did NOT see the comment

Steps 1-6 were as expected. However:

- On step 7, I expected a confirmation message and animation, as designed by @Watson-B (unless we decided to remove this? If so, please lmk) 
- On step 8, I expected the comment to have been correctly posted

@ikosovec can you please confirm if you can reproduce this bug?

**Comment by vedmant** [comment]
@ezl I see, I think #949 broke the comments functionality as comments are not loaded anymore when page is opened, I'll check this.

**Comment by ikosovec** [comment]
The comment was posted in step 8.
When I clicked on the "Post comment" button in the email it went through all the steps 1-6 as explained by @ezl . But I was not prompted to post. It posted automatically.

@Watson-B should there be a step before posting the comment automatically?

**Comment by vedmant** [comment]
Yes it should post automatically, this is how it worked before.

**Comment by ikosovec** [comment]
Okay, this ticket is then finished from my perspective.
Although I do think that we should maybe implement a dialogue between steps 7 and 8 so I'll open a ticket for @Watson-B to review this: #975
