### ISSUE TITLE
38. changes to login success page

### ISSUE THREAD

**Issue by ezl** [ezl/dailyidea.com#96]
https://beta.dailyidea.com/auth/login/success

1. Include the email address that was sent to:

```
We've sent a login email to you at <strong{{ email_address}}</strong>. Please click the button in that email to log in to Daily Idea.
```

2. What happens when you click "Didn't get it" link below?

**Comment by patelravi** [comment]
1. Made the changes.
2. Right now no logic is specified, we can write to send email again, but we need to put something like captcha to prevent to many emails going.
