### ISSUE TITLE
"Go to Post" copy in email while trying to create a Post as a non-logged in user

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#964]
- I go to beta.dailyidea.com, I am not logged in
- I click on "Post"
- Login Email dialogue opens up, I enter my email
- I receive the email:
![image](https://user-images.githubusercontent.com/16639403/114074656-e50fab80-98a4-11eb-953a-94a995702d32.png)

I have a feeling that "Go to Post" is a bit confusing. At first I thought it's mistakenly sent the wrong email flow.
I would suggest switching the copy to:
- "Continue writing"
- "Write a Post"
- or something like this.

**Comment by Watson-B** [comment]
Agreed, will make the updates with the new email designs.

**Comment by Watson-B** [comment]
This is updated in #993
