### ISSUE TITLE
"The only way anybody can log in to your account is via links sent to your email."

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#965]
This is the copy we're sending out with the authorization emails:
![image](https://user-images.githubusercontent.com/16639403/114075010-564f5e80-98a5-11eb-8843-dd67e7a8aac9.png)

I would change the copy to: "The only way to can log in to your account is via links sent to your email."

The above copy is telling me that someone else can log in to my account. I find that a bit confusing and would like to remove the "anybody" part. I find it odd.

**Comment by Watson-B** [comment]
I agree, I'm working on an email overhaul and will update this.

**Comment by Watson-B** [comment]
This is updated in #987 - #997
