### ISSUE TITLE
Comments are not scrollable

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#970]
Steps:
- I'm logged in, go to beta.dailyidea.com
- Navigate to an idea which has a lot of comments, for example: https://beta.dailyidea.com/i/4a4jbm/test?category=new
- By clicking either the comment button, or going full screen and then opening all the comments, I get a dialogue screen which is not scrollable:
![image](https://user-images.githubusercontent.com/16639403/114078548-5e110200-98a9-11eb-9922-b96a50e60b8c.png)

Expected: it should be scrollable.

**Comment by vedmant** [comment]
@ikosovec Hm, weird, I had that issue and fixed it, it's scrollable in my case: https://monosnap.com/file/bKO2n5kTBLG0s2WQ8n4bBtyEfOpm3u

**Comment by ikosovec** [comment]
I have tested this on another computer. 
It is scrollable on my Mac, using the same browser (Google Chrome, latest build).

On my Windows machine, it is not.

What OS are you using @vedmant ?

**Comment by vedmant** [comment]
@ikosovec I'm on Mac, that's weird that it's not scrollable on Windows, I can install windows virtual machine and test it again

**Comment by ikosovec** [comment]
@vedmant I actually tried several browsers before going back to Chrome and it looked good in any combination of Windows <> browser.

So I decided to reinstall Chrome on my Windows machine and it works as intended now:
![image](https://user-images.githubusercontent.com/16639403/114302434-49ab5000-9ac9-11eb-805f-03eacf9b79d8.png)

That's really weird.
