### ISSUE TITLE
When trying to "comment attempt by unauth account" do we need a dialogue before posting the idea?

### ISSUE THREAD

**Issue by ikosovec** [ezl/dailyidea.com#975]
Original discussion thread can be found here: #959 

Here are the steps (as described by @ezl and edited by myself on step 8):

1. From an unauthenticated account, attempt to post a comment
2. This will result in being asked for an email address to complete posting
3. I entered an EXISTING user email address (my own gmail)
4. I was directed to click the link in my email.
5. I clicked the link
6. I was directed to a waiting page. After it succeeded, the light bulbs turned green and said "going to post"
7. The idea loaded (no confirmation message or streamers/animation)
8. The comment was posted (no dialogue or any information)

My question here would be whether or not we need to add a step between steps 7 and 8 to ask the user whether it's OK to post the comment.

My rationale here is that they're bouncing 2 times between apps:
- They're leaving DailyIdea to their email to authorize
- They're returning back from their email to DI to post

Since their focus went off DI, I think there should be a step in between coming back from email (authorized) and actually posting the comment on the idea.

**Comment by Watson-B** [comment]
Interesting question. I think your point about them bouncing twice before the action is taken is a good one, and so a refocus of the original intent is needed. What if rather than a question asking if it is okay to post the comment though, there is a visual indicator (banner/streamers) that the comment has been posted? My logic here is that if they stuck through the whole process of leaving to go to their inbox and then clicking the link to come back, they're committed to posting, and they just need the reminded/indicator that their original intent has been tracked by the site and taken.

**Comment by ikosovec** [comment]
Got it. 
Maybe another angle - what if we just made a draft of their comment? Like, return them to the point where they left off before opening the email.

Leave the comment in draft mode, let them read through it one more time, maybe edit something, correct their grammar, etc.

I think we already have the data for that since the comment is being posted when being authorized. Right, @vedmant?

**Comment by ezl** [comment]
@vedmant my preference is NOT to add an extra confirmation step.

@ikosovec I hear your POV, but IMO, the fact that they clicked through from their email *IS* a sufficient confirmation from the user of their intent to post. I see your point that between the event (step 5) when they click the "confirm post" in their email and (step 8) when the comment officially posts, there are 2 apps and 3 screens. However, as a counterpoint, once the user CLICKS the confirmation in their email (step 5), if the user does NOTHING, this will complete all the way to step 8 with no intervention. Therefore, the user clicks this button:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/157627/114409564-30111380-9b70-11eb-8204-3f1cc3ffdfb1.png">

then if they just close their eyes and wait, the button will be posted. IMO, adding an additional confirmation screen is unnecessary friction.

@vedmant and @Watson-B  There *IS* now a "success" banner at the top of the screen on successful post completion, but no streamers. @vedmant are we using the streamers flair anywhere? or is this just not one of the cases for streamers?

**Comment by vedmant** [comment]
@ezl I'm not really sure what do you mean by "streamers flair"?

About comments, I think it's more important to add edit comment function.

**Comment by ezl** [comment]
@vedmant I apologize!  😇 -- I also didn't know the best way to describe what I was talking about. I see that it has been described in other tickets as "confetti". I was referring to this animation of the ribbons coming down:

https://user-images.githubusercontent.com/65913664/108918753-b97f7d00-75e6-11eb-8955-40a68ecda6a8.gif

> About comments,  I think it's more important to add edit comment function.

You mean that this is a separate issue, but important for us to add, correct?

**Comment by vedmant** [comment]
@ezl Oh, I see, I've seen this animation but there were not specific ticket to implement this. Also not sure how to implement this with JS, gif overlay is also a bad idea.

**Comment by ezl** [comment]
ok, no problem. the streamers are "extra" -- no need to implement this for now. adding to future ticket for execution (#979)

for now then i believe there is no need to add the extra dialog as originally proposed, so I think we should close this ticket.

@vedmant can you just create a separate ticket to add edit comment functionality and close this?

**Comment by vedmant** [comment]
@ezl Sure
